<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\AlertTriggersResponse;
use PayrixLib\Models\AlertTriggersResponseItem;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;

/**
 * Builder for model AlertTriggersResponseItem
 *
 * @see AlertTriggersResponseItem
 */
class AlertTriggersResponseItemBuilder
{
    /**
     * @var AlertTriggersResponseItem
     */
    private $instance;

    private function __construct(AlertTriggersResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Alert Triggers Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new AlertTriggersResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param AlertTriggersResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Alert Triggers Response Item object.
     */
    public function build(): AlertTriggersResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
