<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\AuthTokensPutRequest;

/**
 * Builder for model AuthTokensPutRequest
 *
 * @see AuthTokensPutRequest
 */
class AuthTokensPutRequestBuilder
{
    /**
     * @var AuthTokensPutRequest
     */
    private $instance;

    private function __construct(AuthTokensPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auth Tokens Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthTokensPutRequest());
    }

    /**
     * Sets used field.
     *
     * @param int|null $value
     */
    public function used(?int $value): self
    {
        $this->instance->setUsed($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Auth Tokens Put Request object.
     */
    public function build(): AuthTokensPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
