<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\AuthTokensPostRequest;

/**
 * Builder for model AuthTokensPostRequest
 *
 * @see AuthTokensPostRequest
 */
class AuthTokensPostRequestBuilder
{
    /**
     * @var AuthTokensPostRequest
     */
    private $instance;

    private function __construct(AuthTokensPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auth Tokens Post Request Builder object.
     *
     * @param string $login
     * @param string $customer
     * @param string $token
     */
    public static function init(string $login, string $customer, string $token): self
    {
        return new self(new AuthTokensPostRequest($login, $customer, $token));
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Auth Tokens Post Request object.
     */
    public function build(): AuthTokensPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
