<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\ChargebackDocumentsResponse;
use PayrixLib\Models\ChargebackDocumentsResponseItem;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;

/**
 * Builder for model ChargebackDocumentsResponseItem
 *
 * @see ChargebackDocumentsResponseItem
 */
class ChargebackDocumentsResponseItemBuilder
{
    /**
     * @var ChargebackDocumentsResponseItem
     */
    private $instance;

    private function __construct(ChargebackDocumentsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Chargeback Documents Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargebackDocumentsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param ChargebackDocumentsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Chargeback Documents Response Item object.
     */
    public function build(): ChargebackDocumentsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
