<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\ChargebackMessageResultResponse;
use PayrixLib\Models\ChargebackMessageResultsResponseItem;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;

/**
 * Builder for model ChargebackMessageResultsResponseItem
 *
 * @see ChargebackMessageResultsResponseItem
 */
class ChargebackMessageResultsResponseItemBuilder
{
    /**
     * @var ChargebackMessageResultsResponseItem
     */
    private $instance;

    private function __construct(ChargebackMessageResultsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Chargeback Message Results Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargebackMessageResultsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param ChargebackMessageResultResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Chargeback Message Results Response Item object.
     */
    public function build(): ChargebackMessageResultsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
