<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\DecisionActionsPostRequest;
use PayrixLib\Models\DecisionRulesPostRequest;
use PayrixLib\Models\DecisionsPostRequest;
use PayrixLib\Models\OrgsPostRequest;
use PayrixLib\Models\WatchlistsPostRequest;

/**
 * Builder for model DecisionsPostRequest
 *
 * @see DecisionsPostRequest
 */
class DecisionsPostRequestBuilder
{
    /**
     * @var DecisionsPostRequest
     */
    private $instance;

    private function __construct(DecisionsPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Decisions Post Request Builder object.
     *
     * @param string $login
     * @param string $application
     * @param string $level
     * @param string $type
     * @param string $target
     * @param int $action
     * @param string $value
     * @param string $period
     * @param int $start
     */
    public static function init(
        string $login,
        string $application,
        string $level,
        string $type,
        string $target,
        int $action,
        string $value,
        string $period,
        int $start
    ): self {
        return new self(
            new DecisionsPostRequest(
                $login,
                $application,
                $level,
                $type,
                $target,
                $action,
                $value,
                $period,
                $start
            )
        );
    }

    /**
     * Sets org field.
     *
     * @param string|OrgsPostRequest|null $value
     */
    public function org($value): self
    {
        $this->instance->setOrg($value);
        return $this;
    }

    /**
     * Sets entity field.
     *
     * @param string|null $value
     */
    public function entity(?string $value): self
    {
        $this->instance->setEntity($value);
        return $this;
    }

    /**
     * Sets decision field.
     *
     * @param string|null $value
     */
    public function decision(?string $value): self
    {
        $this->instance->setDecision($value);
        return $this;
    }

    /**
     * Sets division field.
     *
     * @param string|null $value
     */
    public function division(?string $value): self
    {
        $this->instance->setDivision($value);
        return $this;
    }

    /**
     * Sets partition field.
     *
     * @param string|null $value
     */
    public function partition(?string $value): self
    {
        $this->instance->setPartition($value);
        return $this;
    }

    /**
     * Sets sequence field.
     *
     * @param int|null $value
     */
    public function sequence(?int $value): self
    {
        $this->instance->setSequence($value);
        return $this;
    }

    /**
     * Unsets sequence field.
     */
    public function unsetSequence(): self
    {
        $this->instance->unsetSequence();
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param int|null $value
     */
    public function amount(?int $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Unsets amount field.
     */
    public function unsetAmount(): self
    {
        $this->instance->unsetAmount();
        return $this;
    }

    /**
     * Sets period Factor field.
     *
     * @param int|null $value
     */
    public function periodFactor(?int $value): self
    {
        $this->instance->setPeriodFactor($value);
        return $this;
    }

    /**
     * Sets schedule field.
     *
     * @param string|null $value
     */
    public function schedule(?string $value): self
    {
        $this->instance->setSchedule($value);
        return $this;
    }

    /**
     * Sets schedule Factor field.
     *
     * @param int|null $value
     */
    public function scheduleFactor(?int $value): self
    {
        $this->instance->setScheduleFactor($value);
        return $this;
    }

    /**
     * Sets finish field.
     *
     * @param int|null $value
     */
    public function finish(?int $value): self
    {
        $this->instance->setFinish($value);
        return $this;
    }

    /**
     * Sets low field.
     *
     * @param int|null $value
     */
    public function low(?int $value): self
    {
        $this->instance->setLow($value);
        return $this;
    }

    /**
     * Sets high field.
     *
     * @param int|null $value
     */
    public function high(?int $value): self
    {
        $this->instance->setHigh($value);
        return $this;
    }

    /**
     * Sets use Cache field.
     *
     * @param int|null $value
     */
    public function useCache(?int $value): self
    {
        $this->instance->setUseCache($value);
        return $this;
    }

    /**
     * Sets cache Time field.
     *
     * @param int|null $value
     */
    public function cacheTime(?int $value): self
    {
        $this->instance->setCacheTime($value);
        return $this;
    }

    /**
     * Sets options field.
     *
     * @param int|null $value
     */
    public function options(?int $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Sets additional Options field.
     *
     * @param int|null $value
     */
    public function additionalOptions(?int $value): self
    {
        $this->instance->setAdditionalOptions($value);
        return $this;
    }

    /**
     * Sets error Message field.
     *
     * @param string|null $value
     */
    public function errorMessage(?string $value): self
    {
        $this->instance->setErrorMessage($value);
        return $this;
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Sets decision Actions field.
     *
     * @param DecisionActionsPostRequest[]|null $value
     */
    public function decisionActions(?array $value): self
    {
        $this->instance->setDecisionActions($value);
        return $this;
    }

    /**
     * Sets decision Rules field.
     *
     * @param DecisionRulesPostRequest[]|null $value
     */
    public function decisionRules(?array $value): self
    {
        $this->instance->setDecisionRules($value);
        return $this;
    }

    /**
     * Sets decisions field.
     *
     * @param DecisionsPostRequest[]|null $value
     */
    public function decisions(?array $value): self
    {
        $this->instance->setDecisions($value);
        return $this;
    }

    /**
     * Sets watchlist field.
     *
     * @param WatchlistsPostRequest[]|null $value
     */
    public function watchlist(?array $value): self
    {
        $this->instance->setWatchlist($value);
        return $this;
    }

    /**
     * Initializes a new Decisions Post Request object.
     */
    public function build(): DecisionsPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
