<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\DetailsProperties;

/**
 * Builder for model DetailsProperties
 *
 * @see DetailsProperties
 */
class DetailsPropertiesBuilder
{
    /**
     * @var DetailsProperties
     */
    private $instance;

    private function __construct(DetailsProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Details Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new DetailsProperties());
    }

    /**
     * Sets current field.
     *
     * @param int|null $value
     */
    public function current(?int $value): self
    {
        $this->instance->setCurrent($value);
        return $this;
    }

    /**
     * Sets last field.
     *
     * @param int|null $value
     */
    public function last(?int $value): self
    {
        $this->instance->setLast($value);
        return $this;
    }

    /**
     * Sets has More field.
     *
     * @param bool|null $value
     */
    public function hasMore(?bool $value): self
    {
        $this->instance->setHasMore($value);
        return $this;
    }

    /**
     * Initializes a new Details Properties object.
     */
    public function build(): DetailsProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
