<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\DivisionsPutRequest;

/**
 * Builder for model DivisionsPutRequest
 *
 * @see DivisionsPutRequest
 */
class DivisionsPutRequestBuilder
{
    /**
     * @var DivisionsPutRequest
     */
    private $instance;

    private function __construct(DivisionsPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Divisions Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new DivisionsPutRequest());
    }

    /**
     * Sets login field.
     *
     * @param string|null $value
     */
    public function login(?string $value): self
    {
        $this->instance->setLogin($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets change Management Enabled field.
     *
     * @param int|null $value
     */
    public function changeManagementEnabled(?int $value): self
    {
        $this->instance->setChangeManagementEnabled($value);
        return $this;
    }

    /**
     * Sets min Password Length field.
     *
     * @param int|null $value
     */
    public function minPasswordLength(?int $value): self
    {
        $this->instance->setMinPasswordLength($value);
        return $this;
    }

    /**
     * Sets min Password Complexity field.
     *
     * @param int|null $value
     */
    public function minPasswordComplexity(?int $value): self
    {
        $this->instance->setMinPasswordComplexity($value);
        return $this;
    }

    /**
     * Initializes a new Divisions Put Request object.
     */
    public function build(): DivisionsPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
