<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\Details;
use PayrixLib\Models\EntityRefsResponse;
use PayrixLib\Models\EntityRefsResponseItem;
use PayrixLib\Models\ErrorItem;

/**
 * Builder for model EntityRefsResponseItem
 *
 * @see EntityRefsResponseItem
 */
class EntityRefsResponseItemBuilder
{
    /**
     * @var EntityRefsResponseItem
     */
    private $instance;

    private function __construct(EntityRefsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Entity Refs Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new EntityRefsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param EntityRefsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Entity Refs Response Item object.
     */
    public function build(): EntityRefsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
