<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\DisbursementsResponse;
use PayrixLib\Models\EntityRefsResponse;
use PayrixLib\Models\EntriesResponse;
use PayrixLib\Models\EntryOriginsResponse;
use PayrixLib\Models\LoginsResponse;

/**
 * Builder for model EntryOriginsResponse
 *
 * @see EntryOriginsResponse
 */
class EntryOriginsResponseBuilder
{
    /**
     * @var EntryOriginsResponse
     */
    private $instance;

    private function __construct(EntryOriginsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Entry Origins Response Builder object.
     */
    public static function init(): self
    {
        return new self(new EntryOriginsResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets created field.
     *
     * @param string|null $value
     */
    public function created(?string $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets modified field.
     *
     * @param string|null $value
     */
    public function modified(?string $value): self
    {
        $this->instance->setModified($value);
        return $this;
    }

    /**
     * Sets creator field.
     *
     * @param string|LoginsResponse|null $value
     */
    public function creator($value): self
    {
        $this->instance->setCreator($value);
        return $this;
    }

    /**
     * Sets modifier field.
     *
     * @param string|null $value
     */
    public function modifier(?string $value): self
    {
        $this->instance->setModifier($value);
        return $this;
    }

    /**
     * Sets entry field.
     *
     * @param string|EntriesResponse|null $value
     */
    public function entry($value): self
    {
        $this->instance->setEntry($value);
        return $this;
    }

    /**
     * Sets disbursement field.
     *
     * @param string|DisbursementsResponse|null $value
     */
    public function disbursement($value): self
    {
        $this->instance->setDisbursement($value);
        return $this;
    }

    /**
     * Sets cancellation field.
     *
     * @param string|EntriesResponse|null $value
     */
    public function cancellation($value): self
    {
        $this->instance->setCancellation($value);
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets funding field.
     *
     * @param string|EntityRefsResponse|null $value
     */
    public function funding($value): self
    {
        $this->instance->setFunding($value);
        return $this;
    }

    /**
     * Sets platform field.
     *
     * @param string|null $value
     */
    public function platform(?string $value): self
    {
        $this->instance->setPlatform($value);
        return $this;
    }

    /**
     * Sets fbo field.
     *
     * @param string|null $value
     */
    public function fbo(?string $value): self
    {
        $this->instance->setFbo($value);
        return $this;
    }

    /**
     * Initializes a new Entry Origins Response object.
     */
    public function build(): EntryOriginsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
