<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\FeeRulesPutRequest;

/**
 * Builder for model FeeRulesPutRequest
 *
 * @see FeeRulesPutRequest
 */
class FeeRulesPutRequestBuilder
{
    /**
     * @var FeeRulesPutRequest
     */
    private $instance;

    private function __construct(FeeRulesPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fee Rules Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new FeeRulesPutRequest());
    }

    /**
     * Sets fee field.
     *
     * @param string|null $value
     */
    public function fee(?string $value): self
    {
        $this->instance->setFee($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets application field.
     *
     * @param string|null $value
     */
    public function application(?string $value): self
    {
        $this->instance->setApplication($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Sets grouping field.
     *
     * @param string|null $value
     */
    public function grouping(?string $value): self
    {
        $this->instance->setGrouping($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Fee Rules Put Request object.
     */
    public function build(): FeeRulesPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
