<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;
use PayrixLib\Models\FundsResponse;
use PayrixLib\Models\FundsResponseItem;

/**
 * Builder for model FundsResponseItem
 *
 * @see FundsResponseItem
 */
class FundsResponseItemBuilder
{
    /**
     * @var FundsResponseItem
     */
    private $instance;

    private function __construct(FundsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Funds Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new FundsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param FundsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Funds Response Item object.
     */
    public function build(): FundsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
