<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\InvoiceParametersResponseItem;
use PayrixLib\Models\InvoiceParametersResponseResult;

/**
 * Builder for model InvoiceParametersResponseResult
 *
 * @see InvoiceParametersResponseResult
 */
class InvoiceParametersResponseResultBuilder
{
    /**
     * @var InvoiceParametersResponseResult
     */
    private $instance;

    private function __construct(InvoiceParametersResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Invoice Parameters Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new InvoiceParametersResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param InvoiceParametersResponseItem|null $value
     */
    public function response(?InvoiceParametersResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Invoice Parameters Response Result object.
     */
    public function build(): InvoiceParametersResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
