<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\InvoiceItemsResponseItem;
use PayrixLib\Models\InvoiceItemsResponseResult;

/**
 * Builder for model InvoiceItemsResponseResult
 *
 * @see InvoiceItemsResponseResult
 */
class InvoiceItemsResponseResultBuilder
{
    /**
     * @var InvoiceItemsResponseResult
     */
    private $instance;

    private function __construct(InvoiceItemsResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Invoice Items Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new InvoiceItemsResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param InvoiceItemsResponseItem|null $value
     */
    public function response(?InvoiceItemsResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Invoice Items Response Result object.
     */
    public function build(): InvoiceItemsResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
