<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;
use PayrixLib\Models\IplistsResponse;
use PayrixLib\Models\IplistsResponseItem;

/**
 * Builder for model IplistsResponseItem
 *
 * @see IplistsResponseItem
 */
class IplistsResponseItemBuilder
{
    /**
     * @var IplistsResponseItem
     */
    private $instance;

    private function __construct(IplistsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Iplists Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new IplistsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param IplistsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Iplists Response Item object.
     */
    public function build(): IplistsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
