<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\LoginsPutRequest;

/**
 * Builder for model LoginsPutRequest
 *
 * @see LoginsPutRequest
 */
class LoginsPutRequestBuilder
{
    /**
     * @var LoginsPutRequest
     */
    private $instance;

    private function __construct(LoginsPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Logins Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new LoginsPutRequest());
    }

    /**
     * Sets login field.
     *
     * @param string|null $value
     */
    public function login(?string $value): self
    {
        $this->instance->setLogin($value);
        return $this;
    }

    /**
     * Sets partition field.
     *
     * @param string|null $value
     */
    public function partition(?string $value): self
    {
        $this->instance->setPartition($value);
        return $this;
    }

    /**
     * Sets division field.
     *
     * @param string|null $value
     */
    public function division(?string $value): self
    {
        $this->instance->setDivision($value);
        return $this;
    }

    /**
     * Sets parent Division field.
     *
     * @param string|null $value
     */
    public function parentDivision(?string $value): self
    {
        $this->instance->setParentDivision($value);
        return $this;
    }

    /**
     * Sets roles field.
     *
     * @param int|null $value
     */
    public function roles(?int $value): self
    {
        $this->instance->setRoles($value);
        return $this;
    }

    /**
     * Sets confirmed field.
     *
     * @param int|null $value
     */
    public function confirmed(?int $value): self
    {
        $this->instance->setConfirmed($value);
        return $this;
    }

    /**
     * Sets username field.
     *
     * @param string|null $value
     */
    public function username(?string $value): self
    {
        $this->instance->setUsername($value);
        return $this;
    }

    /**
     * Sets password field.
     *
     * @param string|null $value
     */
    public function password(?string $value): self
    {
        $this->instance->setPassword($value);
        return $this;
    }

    /**
     * Sets first field.
     *
     * @param string|null $value
     */
    public function first(?string $value): self
    {
        $this->instance->setFirst($value);
        return $this;
    }

    /**
     * Sets middle field.
     *
     * @param string|null $value
     */
    public function middle(?string $value): self
    {
        $this->instance->setMiddle($value);
        return $this;
    }

    /**
     * Sets last field.
     *
     * @param string|null $value
     */
    public function last(?string $value): self
    {
        $this->instance->setLast($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets allowed Resources field.
     *
     * @param string|null $value
     */
    public function allowedResources(?string $value): self
    {
        $this->instance->setAllowedResources($value);
        return $this;
    }

    /**
     * Sets restricted Resources field.
     *
     * @param string|null $value
     */
    public function restrictedResources(?string $value): self
    {
        $this->instance->setRestrictedResources($value);
        return $this;
    }

    /**
     * Sets portal Access field.
     *
     * @param int|null $value
     */
    public function portalAccess(?int $value): self
    {
        $this->instance->setPortalAccess($value);
        return $this;
    }

    /**
     * Sets mfa Enabled field.
     *
     * @param int|null $value
     */
    public function mfaEnabled(?int $value): self
    {
        $this->instance->setMfaEnabled($value);
        return $this;
    }

    /**
     * Sets mfa Secret field.
     *
     * @param string|null $value
     */
    public function mfaSecret(?string $value): self
    {
        $this->instance->setMfaSecret($value);
        return $this;
    }

    /**
     * Sets mfa Enrolled Date field.
     *
     * @param string|null $value
     */
    public function mfaEnrolledDate(?string $value): self
    {
        $this->instance->setMfaEnrolledDate($value);
        return $this;
    }

    /**
     * Sets mfa Type field.
     *
     * @param string|null $value
     */
    public function mfaType(?string $value): self
    {
        $this->instance->setMfaType($value);
        return $this;
    }

    /**
     * Sets address 1 field.
     *
     * @param string|null $value
     */
    public function address1(?string $value): self
    {
        $this->instance->setAddress1($value);
        return $this;
    }

    /**
     * Sets address 2 field.
     *
     * @param string|null $value
     */
    public function address2(?string $value): self
    {
        $this->instance->setAddress2($value);
        return $this;
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets state field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets zip field.
     *
     * @param string|null $value
     */
    public function zip(?string $value): self
    {
        $this->instance->setZip($value);
        return $this;
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets phone field.
     *
     * @param string|null $value
     */
    public function phone(?string $value): self
    {
        $this->instance->setPhone($value);
        return $this;
    }

    /**
     * Sets fax field.
     *
     * @param string|null $value
     */
    public function fax(?string $value): self
    {
        $this->instance->setFax($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Logins Put Request object.
     */
    public function build(): LoginsPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
