<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\MembersPutRequest;

/**
 * Builder for model MembersPutRequest
 *
 * @see MembersPutRequest
 */
class MembersPutRequestBuilder
{
    /**
     * @var MembersPutRequest
     */
    private $instance;

    private function __construct(MembersPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Members Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new MembersPutRequest());
    }

    /**
     * Sets merchant field.
     *
     * @param string|null $value
     */
    public function merchant(?string $value): self
    {
        $this->instance->setMerchant($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets first field.
     *
     * @param string|null $value
     */
    public function first(?string $value): self
    {
        $this->instance->setFirst($value);
        return $this;
    }

    /**
     * Sets middle field.
     *
     * @param string|null $value
     */
    public function middle(?string $value): self
    {
        $this->instance->setMiddle($value);
        return $this;
    }

    /**
     * Sets last field.
     *
     * @param string|null $value
     */
    public function last(?string $value): self
    {
        $this->instance->setLast($value);
        return $this;
    }

    /**
     * Sets ssn field.
     *
     * @param string|null $value
     */
    public function ssn(?string $value): self
    {
        $this->instance->setSsn($value);
        return $this;
    }

    /**
     * Sets citizenship field.
     *
     * @param string|null $value
     */
    public function citizenship(?string $value): self
    {
        $this->instance->setCitizenship($value);
        return $this;
    }

    /**
     * Sets dob field.
     *
     * @param int|null $value
     */
    public function dob(?int $value): self
    {
        $this->instance->setDob($value);
        return $this;
    }

    /**
     * Sets gender field.
     *
     * @param string|null $value
     */
    public function gender(?string $value): self
    {
        $this->instance->setGender($value);
        return $this;
    }

    /**
     * Sets dl field.
     *
     * @param string|null $value
     */
    public function dl(?string $value): self
    {
        $this->instance->setDl($value);
        return $this;
    }

    /**
     * Sets dlstate field.
     *
     * @param string|null $value
     */
    public function dlstate(?string $value): self
    {
        $this->instance->setDlstate($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets ownership field.
     *
     * @param int|null $value
     */
    public function ownership(?int $value): self
    {
        $this->instance->setOwnership($value);
        return $this;
    }

    /**
     * Sets primary field.
     *
     * @param int|null $value
     */
    public function primary(?int $value): self
    {
        $this->instance->setPrimary($value);
        return $this;
    }

    /**
     * Sets credit Score field.
     *
     * @param int|null $value
     */
    public function creditScore(?int $value): self
    {
        $this->instance->setCreditScore($value);
        return $this;
    }

    /**
     * Sets credit Score Date field.
     *
     * @param string|null $value
     */
    public function creditScoreDate(?string $value): self
    {
        $this->instance->setCreditScoreDate($value);
        return $this;
    }

    /**
     * Sets significant Responsibility field.
     *
     * @param int|null $value
     */
    public function significantResponsibility(?int $value): self
    {
        $this->instance->setSignificantResponsibility($value);
        return $this;
    }

    /**
     * Sets politically Exposed field.
     *
     * @param int|null $value
     */
    public function politicallyExposed(?int $value): self
    {
        $this->instance->setPoliticallyExposed($value);
        return $this;
    }

    /**
     * Sets mailing Address 1 field.
     *
     * @param string|null $value
     */
    public function mailingAddress1(?string $value): self
    {
        $this->instance->setMailingAddress1($value);
        return $this;
    }

    /**
     * Sets mailing Address 2 field.
     *
     * @param string|null $value
     */
    public function mailingAddress2(?string $value): self
    {
        $this->instance->setMailingAddress2($value);
        return $this;
    }

    /**
     * Sets mailing City field.
     *
     * @param string|null $value
     */
    public function mailingCity(?string $value): self
    {
        $this->instance->setMailingCity($value);
        return $this;
    }

    /**
     * Sets mailing State field.
     *
     * @param string|null $value
     */
    public function mailingState(?string $value): self
    {
        $this->instance->setMailingState($value);
        return $this;
    }

    /**
     * Sets mailing Country field.
     *
     * @param string|null $value
     */
    public function mailingCountry(?string $value): self
    {
        $this->instance->setMailingCountry($value);
        return $this;
    }

    /**
     * Sets mailing Postal Code field.
     *
     * @param string|null $value
     */
    public function mailingPostalCode(?string $value): self
    {
        $this->instance->setMailingPostalCode($value);
        return $this;
    }

    /**
     * Sets treasury Prime Roles field.
     *
     * @param array|null $value
     */
    public function treasuryPrimeRoles(?array $value): self
    {
        $this->instance->setTreasuryPrimeRoles($value);
        return $this;
    }

    /**
     * Sets timezone field.
     *
     * @param string|null $value
     */
    public function timezone(?string $value): self
    {
        $this->instance->setTimezone($value);
        return $this;
    }

    /**
     * Sets address 1 field.
     *
     * @param string|null $value
     */
    public function address1(?string $value): self
    {
        $this->instance->setAddress1($value);
        return $this;
    }

    /**
     * Sets address 2 field.
     *
     * @param string|null $value
     */
    public function address2(?string $value): self
    {
        $this->instance->setAddress2($value);
        return $this;
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets state field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets zip field.
     *
     * @param string|null $value
     */
    public function zip(?string $value): self
    {
        $this->instance->setZip($value);
        return $this;
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets phone field.
     *
     * @param string|null $value
     */
    public function phone(?string $value): self
    {
        $this->instance->setPhone($value);
        return $this;
    }

    /**
     * Sets fax field.
     *
     * @param string|null $value
     */
    public function fax(?string $value): self
    {
        $this->instance->setFax($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Members Put Request object.
     */
    public function build(): MembersPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
