<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\MerchantsResponseItem;
use PayrixLib\Models\MerchantsResponseResult;

/**
 * Builder for model MerchantsResponseResult
 *
 * @see MerchantsResponseResult
 */
class MerchantsResponseResultBuilder
{
    /**
     * @var MerchantsResponseResult
     */
    private $instance;

    private function __construct(MerchantsResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchants Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantsResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param MerchantsResponseItem|null $value
     */
    public function response(?MerchantsResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Merchants Response Result object.
     */
    public function build(): MerchantsResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
