<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\MessagesPostRequest;
use PayrixLib\Models\MessageThreadsPostRequest;

/**
 * Builder for model MessageThreadsPostRequest
 *
 * @see MessageThreadsPostRequest
 */
class MessageThreadsPostRequestBuilder
{
    /**
     * @var MessageThreadsPostRequest
     */
    private $instance;

    private function __construct(MessageThreadsPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Message Threads Post Request Builder object.
     *
     * @param string $login
     * @param string $sender
     * @param string $recipient
     * @param string $subject
     */
    public static function init(string $login, string $sender, string $recipient, string $subject): self
    {
        return new self(new MessageThreadsPostRequest($login, $sender, $recipient, $subject));
    }

    /**
     * Sets forlogin field.
     *
     * @param string|null $value
     */
    public function forlogin(?string $value): self
    {
        $this->instance->setForlogin($value);
        return $this;
    }

    /**
     * Sets hold field.
     *
     * @param string|null $value
     */
    public function hold(?string $value): self
    {
        $this->instance->setHold($value);
        return $this;
    }

    /**
     * Sets entity Return field.
     *
     * @param string|null $value
     */
    public function entityReturn(?string $value): self
    {
        $this->instance->setEntityReturn($value);
        return $this;
    }

    /**
     * Sets opposing Message Thread field.
     *
     * @param string|null $value
     */
    public function opposingMessageThread(?string $value): self
    {
        $this->instance->setOpposingMessageThread($value);
        return $this;
    }

    /**
     * Sets folder field.
     *
     * @param string|null $value
     */
    public function folder(?string $value): self
    {
        $this->instance->setFolder($value);
        return $this;
    }

    /**
     * Sets messages field.
     *
     * @param MessagesPostRequest[]|null $value
     */
    public function messages(?array $value): self
    {
        $this->instance->setMessages($value);
        return $this;
    }

    /**
     * Initializes a new Message Threads Post Request object.
     */
    public function build(): MessageThreadsPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
