<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;
use PayrixLib\Models\NoteDocumentsResponse;
use PayrixLib\Models\NoteDocumentsResponseItem;

/**
 * Builder for model NoteDocumentsResponseItem
 *
 * @see NoteDocumentsResponseItem
 */
class NoteDocumentsResponseItemBuilder
{
    /**
     * @var NoteDocumentsResponseItem
     */
    private $instance;

    private function __construct(NoteDocumentsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Note Documents Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new NoteDocumentsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param NoteDocumentsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Note Documents Response Item object.
     */
    public function build(): NoteDocumentsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
