<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\NoteDocumentsResponseItem;
use PayrixLib\Models\NoteDocumentsResponseResult;

/**
 * Builder for model NoteDocumentsResponseResult
 *
 * @see NoteDocumentsResponseResult
 */
class NoteDocumentsResponseResultBuilder
{
    /**
     * @var NoteDocumentsResponseResult
     */
    private $instance;

    private function __construct(NoteDocumentsResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Note Documents Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new NoteDocumentsResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param NoteDocumentsResponseItem|null $value
     */
    public function response(?NoteDocumentsResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Note Documents Response Result object.
     */
    public function build(): NoteDocumentsResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
