<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\OrgEntitiesResponseItem;
use PayrixLib\Models\OrgEntitiesResponseResult;

/**
 * Builder for model OrgEntitiesResponseResult
 *
 * @see OrgEntitiesResponseResult
 */
class OrgEntitiesResponseResultBuilder
{
    /**
     * @var OrgEntitiesResponseResult
     */
    private $instance;

    private function __construct(OrgEntitiesResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Org Entities Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new OrgEntitiesResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param OrgEntitiesResponseItem|null $value
     */
    public function response(?OrgEntitiesResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Org Entities Response Result object.
     */
    public function build(): OrgEntitiesResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
