<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\OrgFlowActionsPutRequest;

/**
 * Builder for model OrgFlowActionsPutRequest
 *
 * @see OrgFlowActionsPutRequest
 */
class OrgFlowActionsPutRequestBuilder
{
    /**
     * @var OrgFlowActionsPutRequest
     */
    private $instance;

    private function __construct(OrgFlowActionsPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Org Flow Actions Put Request Builder object.
     *
     * @param string $orgFlow
     * @param string $org
     * @param string $action
     */
    public static function init(string $orgFlow, string $org, string $action): self
    {
        return new self(new OrgFlowActionsPutRequest($orgFlow, $org, $action));
    }

    /**
     * Initializes a new Org Flow Actions Put Request object.
     */
    public function build(): OrgFlowActionsPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
