<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\OrgsVASPinlessDebitConversionsPutRequest;

/**
 * Builder for model OrgsVASPinlessDebitConversionsPutRequest
 *
 * @see OrgsVASPinlessDebitConversionsPutRequest
 */
class OrgsVASPinlessDebitConversionsPutRequestBuilder
{
    /**
     * @var OrgsVASPinlessDebitConversionsPutRequest
     */
    private $instance;

    private function __construct(OrgsVASPinlessDebitConversionsPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Orgs VAS Pinless Debit Conversions Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new OrgsVASPinlessDebitConversionsPutRequest());
    }

    /**
     * Sets org field.
     *
     * @param string|null $value
     */
    public function org(?string $value): self
    {
        $this->instance->setOrg($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Orgs VAS Pinless Debit Conversions Put Request object.
     */
    public function build(): OrgsVASPinlessDebitConversionsPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
