<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\OrgsVASSaferPaymentsPutRequest;

/**
 * Builder for model OrgsVASSaferPaymentsPutRequest
 *
 * @see OrgsVASSaferPaymentsPutRequest
 */
class OrgsVASSaferPaymentsPutRequestBuilder
{
    /**
     * @var OrgsVASSaferPaymentsPutRequest
     */
    private $instance;

    private function __construct(OrgsVASSaferPaymentsPutRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Orgs VAS Safer Payments Put Request Builder object.
     */
    public static function init(): self
    {
        return new self(new OrgsVASSaferPaymentsPutRequest());
    }

    /**
     * Sets org field.
     *
     * @param string|null $value
     */
    public function org(?string $value): self
    {
        $this->instance->setOrg($value);
        return $this;
    }

    /**
     * Sets default Program field.
     *
     * @param string|null $value
     */
    public function defaultProgram(?string $value): self
    {
        $this->instance->setDefaultProgram($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Orgs VAS Safer Payments Put Request object.
     */
    public function build(): OrgsVASSaferPaymentsPutRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
