<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\BillingsPostRequest;
use PayrixLib\Models\FeeModifiersPostRequest;
use PayrixLib\Models\FeesPostRequest;
use PayrixLib\Models\InvoiceParametersPostRequest;
use PayrixLib\Models\OrgEntitiesPostRequest;
use PayrixLib\Models\OrgsPostRequest;
use PayrixLib\Models\PayoutFlowsPostRequest;
use PayrixLib\Models\ProfitSharesPostRequest;
use PayrixLib\Models\ReservesPostRequest;
use PayrixLib\Models\SecretsPostRequest;

/**
 * Builder for model OrgsPostRequest
 *
 * @see OrgsPostRequest
 */
class OrgsPostRequestBuilder
{
    /**
     * @var OrgsPostRequest
     */
    private $instance;

    private function __construct(OrgsPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Orgs Post Request Builder object.
     */
    public static function init(): self
    {
        return new self(new OrgsPostRequest());
    }

    /**
     * Sets login field.
     *
     * @param string|null $value
     */
    public function login(?string $value): self
    {
        $this->instance->setLogin($value);
        return $this;
    }

    /**
     * Unsets login field.
     */
    public function unsetLogin(): self
    {
        $this->instance->unsetLogin();
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets billings field.
     *
     * @param BillingsPostRequest[]|null $value
     */
    public function billings(?array $value): self
    {
        $this->instance->setBillings($value);
        return $this;
    }

    /**
     * Sets fee Modifiers field.
     *
     * @param FeeModifiersPostRequest[]|null $value
     */
    public function feeModifiers(?array $value): self
    {
        $this->instance->setFeeModifiers($value);
        return $this;
    }

    /**
     * Sets fees field.
     *
     * @param FeesPostRequest[]|null $value
     */
    public function fees(?array $value): self
    {
        $this->instance->setFees($value);
        return $this;
    }

    /**
     * Sets invoice Parameters field.
     *
     * @param InvoiceParametersPostRequest[]|null $value
     */
    public function invoiceParameters(?array $value): self
    {
        $this->instance->setInvoiceParameters($value);
        return $this;
    }

    /**
     * Sets org Entities field.
     *
     * @param OrgEntitiesPostRequest[]|null $value
     */
    public function orgEntities(?array $value): self
    {
        $this->instance->setOrgEntities($value);
        return $this;
    }

    /**
     * Sets payout Flows field.
     *
     * @param PayoutFlowsPostRequest[]|null $value
     */
    public function payoutFlows(?array $value): self
    {
        $this->instance->setPayoutFlows($value);
        return $this;
    }

    /**
     * Sets profit Shares field.
     *
     * @param ProfitSharesPostRequest[]|null $value
     */
    public function profitShares(?array $value): self
    {
        $this->instance->setProfitShares($value);
        return $this;
    }

    /**
     * Sets reserves field.
     *
     * @param ReservesPostRequest[]|null $value
     */
    public function reserves(?array $value): self
    {
        $this->instance->setReserves($value);
        return $this;
    }

    /**
     * Sets secrets field.
     *
     * @param SecretsPostRequest[]|null $value
     */
    public function secrets(?array $value): self
    {
        $this->instance->setSecrets($value);
        return $this;
    }

    /**
     * Initializes a new Orgs Post Request object.
     */
    public function build(): OrgsPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
