<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\OrgsVASRevenueBoostsPostRequest;

/**
 * Builder for model OrgsVASRevenueBoostsPostRequest
 *
 * @see OrgsVASRevenueBoostsPostRequest
 */
class OrgsVASRevenueBoostsPostRequestBuilder
{
    /**
     * @var OrgsVASRevenueBoostsPostRequest
     */
    private $instance;

    private function __construct(OrgsVASRevenueBoostsPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Orgs VAS Revenue Boosts Post Request Builder object.
     *
     * @param string $org
     */
    public static function init(string $org): self
    {
        return new self(new OrgsVASRevenueBoostsPostRequest($org));
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Orgs VAS Revenue Boosts Post Request object.
     */
    public function build(): OrgsVASRevenueBoostsPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
