<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\BinsResponse;
use PayrixLib\Models\PaymentResponse;

/**
 * Builder for model PaymentResponse
 *
 * @see PaymentResponse
 */
class PaymentResponseBuilder
{
    /**
     * @var PaymentResponse
     */
    private $instance;

    private function __construct(PaymentResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets method field.
     *
     * @param int|null $value
     */
    public function method(?int $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Sets number field.
     *
     * @param string|null $value
     */
    public function number(?string $value): self
    {
        $this->instance->setNumber($value);
        return $this;
    }

    /**
     * Sets routing field.
     *
     * @param string|null $value
     */
    public function routing(?string $value): self
    {
        $this->instance->setRouting($value);
        return $this;
    }

    /**
     * Sets bin field.
     *
     * @param string|BinsResponse|null $value
     */
    public function bin($value): self
    {
        $this->instance->setBin($value);
        return $this;
    }

    /**
     * Sets payment field.
     *
     * @param string|null $value
     */
    public function payment(?string $value): self
    {
        $this->instance->setPayment($value);
        return $this;
    }

    /**
     * Sets last Checked field.
     *
     * @param string|null $value
     */
    public function lastChecked(?string $value): self
    {
        $this->instance->setLastChecked($value);
        return $this;
    }

    /**
     * Sets last 4 field.
     *
     * @param string|null $value
     */
    public function last4(?string $value): self
    {
        $this->instance->setLast4($value);
        return $this;
    }

    /**
     * Sets mask field.
     *
     * @param string|null $value
     */
    public function mask(?string $value): self
    {
        $this->instance->setMask($value);
        return $this;
    }

    /**
     * Unsets mask field.
     */
    public function unsetMask(): self
    {
        $this->instance->unsetMask();
        return $this;
    }

    /**
     * Sets plaid Consumer Account field.
     *
     * @param string|null $value
     */
    public function plaidConsumerAccount(?string $value): self
    {
        $this->instance->setPlaidConsumerAccount($value);
        return $this;
    }

    /**
     * Unsets plaid Consumer Account field.
     */
    public function unsetPlaidConsumerAccount(): self
    {
        $this->instance->unsetPlaidConsumerAccount();
        return $this;
    }

    /**
     * Initializes a new Payment Response object.
     */
    public function build(): PaymentResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
