<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\PayoutFlowsResponseItem;
use PayrixLib\Models\PayoutFlowsResponseResult;

/**
 * Builder for model PayoutFlowsResponseResult
 *
 * @see PayoutFlowsResponseResult
 */
class PayoutFlowsResponseResultBuilder
{
    /**
     * @var PayoutFlowsResponseResult
     */
    private $instance;

    private function __construct(PayoutFlowsResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payout Flows Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new PayoutFlowsResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param PayoutFlowsResponseItem|null $value
     */
    public function response(?PayoutFlowsResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Payout Flows Response Result object.
     */
    public function build(): PayoutFlowsResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
