<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\AccountsPostRequest;
use PayrixLib\Models\PayoutPostRequest;

/**
 * Builder for model PayoutPostRequest
 *
 * @see PayoutPostRequest
 */
class PayoutPostRequestBuilder
{
    /**
     * @var PayoutPostRequest
     */
    private $instance;

    private function __construct(PayoutPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payout Post Request Builder object.
     *
     * @param string|AccountsPostRequest $account
     * @param string $entity
     * @param int $schedule
     * @param int $start
     * @param int $um
     * @param int $amount
     * @param int $skipOffDays
     */
    public static function init(
        $account,
        string $entity,
        int $schedule,
        int $start,
        int $um,
        int $amount,
        int $skipOffDays
    ): self {
        return new self(new PayoutPostRequest($account, $entity, $schedule, $start, $um, $amount, $skipOffDays));
    }

    /**
     * Sets login field.
     *
     * @param string|null $value
     */
    public function login(?string $value): self
    {
        $this->instance->setLogin($value);
        return $this;
    }

    /**
     * Sets billing field.
     *
     * @param string|null $value
     */
    public function billing(?string $value): self
    {
        $this->instance->setBilling($value);
        return $this;
    }

    /**
     * Sets payout Flow field.
     *
     * @param string|null $value
     */
    public function payoutFlow(?string $value): self
    {
        $this->instance->setPayoutFlow($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets schedule Factor field.
     *
     * @param int|null $value
     */
    public function scheduleFactor(?int $value): self
    {
        $this->instance->setScheduleFactor($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Unsets currency field.
     */
    public function unsetCurrency(): self
    {
        $this->instance->unsetCurrency();
        return $this;
    }

    /**
     * Sets minimum field.
     *
     * @param int|null $value
     */
    public function minimum(?int $value): self
    {
        $this->instance->setMinimum($value);
        return $this;
    }

    /**
     * Sets maximum field.
     *
     * @param int|null $value
     */
    public function maximum(?int $value): self
    {
        $this->instance->setMaximum($value);
        return $this;
    }

    /**
     * Sets float field.
     *
     * @param int|null $value
     */
    public function float(?int $value): self
    {
        $this->instance->setFloat($value);
        return $this;
    }

    /**
     * Sets secondary Descriptor field.
     *
     * @param string|null $value
     */
    public function secondaryDescriptor(?string $value): self
    {
        $this->instance->setSecondaryDescriptor($value);
        return $this;
    }

    /**
     * Sets same Day field.
     *
     * @param int|null $value
     */
    public function sameDay(?int $value): self
    {
        $this->instance->setSameDay($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Payout Post Request object.
     */
    public function build(): PayoutPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
