<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\ProfitShareRulesPostRequest;
use PayrixLib\Models\ProfitSharesPostRequest;

/**
 * Builder for model ProfitShareRulesPostRequest
 *
 * @see ProfitShareRulesPostRequest
 */
class ProfitShareRulesPostRequestBuilder
{
    /**
     * @var ProfitShareRulesPostRequest
     */
    private $instance;

    private function __construct(ProfitShareRulesPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Profit Share Rules Post Request Builder object.
     *
     * @param string|ProfitSharesPostRequest $profitShare
     * @param string $type
     * @param string $value
     */
    public static function init($profitShare, string $type, string $value): self
    {
        return new self(new ProfitShareRulesPostRequest($profitShare, $type, $value));
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets grouping field.
     *
     * @param string|null $value
     */
    public function grouping(?string $value): self
    {
        $this->instance->setGrouping($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Profit Share Rules Post Request object.
     */
    public function build(): ProfitShareRulesPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
