<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\EntitiesResponse;
use PayrixLib\Models\LoginsResponse;
use PayrixLib\Models\RevShareSchedulesResponse;

/**
 * Builder for model RevShareSchedulesResponse
 *
 * @see RevShareSchedulesResponse
 */
class RevShareSchedulesResponseBuilder
{
    /**
     * @var RevShareSchedulesResponse
     */
    private $instance;

    private function __construct(RevShareSchedulesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Rev Share Schedules Response Builder object.
     */
    public static function init(): self
    {
        return new self(new RevShareSchedulesResponse());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets created field.
     *
     * @param string|null $value
     */
    public function created(?string $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets modified field.
     *
     * @param string|null $value
     */
    public function modified(?string $value): self
    {
        $this->instance->setModified($value);
        return $this;
    }

    /**
     * Sets creator field.
     *
     * @param string|LoginsResponse|null $value
     */
    public function creator($value): self
    {
        $this->instance->setCreator($value);
        return $this;
    }

    /**
     * Sets modifier field.
     *
     * @param string|null $value
     */
    public function modifier(?string $value): self
    {
        $this->instance->setModifier($value);
        return $this;
    }

    /**
     * Sets entity field.
     *
     * @param string|EntitiesResponse|null $value
     */
    public function entity($value): self
    {
        $this->instance->setEntity($value);
        return $this;
    }

    /**
     * Sets forentity field.
     *
     * @param string|EntitiesResponse|null $value
     */
    public function forentity($value): self
    {
        $this->instance->setForentity($value);
        return $this;
    }

    /**
     * Sets start field.
     *
     * @param string|null $value
     */
    public function start(?string $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets end field.
     *
     * @param string|null $value
     */
    public function end(?string $value): self
    {
        $this->instance->setEnd($value);
        return $this;
    }

    /**
     * Sets share field.
     *
     * @param int|null $value
     */
    public function share(?int $value): self
    {
        $this->instance->setShare($value);
        return $this;
    }

    /**
     * Sets event field.
     *
     * @param int|null $value
     */
    public function event(?int $value): self
    {
        $this->instance->setEvent($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Rev Share Schedules Response object.
     */
    public function build(): RevShareSchedulesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
