<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\RevShareSchedulesPostRequest;

/**
 * Builder for model RevShareSchedulesPostRequest
 *
 * @see RevShareSchedulesPostRequest
 */
class RevShareSchedulesPostRequestBuilder
{
    /**
     * @var RevShareSchedulesPostRequest
     */
    private $instance;

    private function __construct(RevShareSchedulesPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Rev Share Schedules Post Request Builder object.
     *
     * @param string $entity
     * @param string $forentity
     * @param string $start
     * @param int $share
     * @param int $event
     */
    public static function init(string $entity, string $forentity, string $start, int $share, int $event): self
    {
        return new self(new RevShareSchedulesPostRequest($entity, $forentity, $start, $share, $event));
    }

    /**
     * Sets end field.
     *
     * @param string|null $value
     */
    public function end(?string $value): self
    {
        $this->instance->setEnd($value);
        return $this;
    }

    /**
     * Sets inactive field.
     *
     * @param int|null $value
     */
    public function inactive(?int $value): self
    {
        $this->instance->setInactive($value);
        return $this;
    }

    /**
     * Sets frozen field.
     *
     * @param int|null $value
     */
    public function frozen(?int $value): self
    {
        $this->instance->setFrozen($value);
        return $this;
    }

    /**
     * Initializes a new Rev Share Schedules Post Request object.
     */
    public function build(): RevShareSchedulesPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
