<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;
use PayrixLib\Models\TeamLoginResponse;
use PayrixLib\Models\TeamLoginResponseItem;

/**
 * Builder for model TeamLoginResponseItem
 *
 * @see TeamLoginResponseItem
 */
class TeamLoginResponseItemBuilder
{
    /**
     * @var TeamLoginResponseItem
     */
    private $instance;

    private function __construct(TeamLoginResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Team Login Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new TeamLoginResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param TeamLoginResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Team Login Response Item object.
     */
    public function build(): TeamLoginResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
