<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\TerminalTxnRefPostRequest;

/**
 * Builder for model TerminalTxnRefPostRequest
 *
 * @see TerminalTxnRefPostRequest
 */
class TerminalTxnRefPostRequestBuilder
{
    /**
     * @var TerminalTxnRefPostRequest
     */
    private $instance;

    private function __construct(TerminalTxnRefPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terminal Txn Ref Post Request Builder object.
     *
     * @param string $terminalTxn
     * @param string $ref
     * @param string $stage
     * @param string $platform
     */
    public static function init(string $terminalTxn, string $ref, string $stage, string $platform): self
    {
        return new self(new TerminalTxnRefPostRequest($terminalTxn, $ref, $stage, $platform));
    }

    /**
     * Initializes a new Terminal Txn Ref Post Request object.
     */
    public function build(): TerminalTxnRefPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
