<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\TerminalTxnsMetadatasPostRequest;

/**
 * Builder for model TerminalTxnsMetadatasPostRequest
 *
 * @see TerminalTxnsMetadatasPostRequest
 */
class TerminalTxnsMetadatasPostRequestBuilder
{
    /**
     * @var TerminalTxnsMetadatasPostRequest
     */
    private $instance;

    private function __construct(TerminalTxnsMetadatasPostRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terminal Txns Metadatas Post Request Builder object.
     *
     * @param string $terminalTxn
     * @param string $type
     * @param string $field
     * @param string $value
     */
    public static function init(string $terminalTxn, string $type, string $field, string $value): self
    {
        return new self(new TerminalTxnsMetadatasPostRequest($terminalTxn, $type, $field, $value));
    }

    /**
     * Initializes a new Terminal Txns Metadatas Post Request object.
     */
    public function build(): TerminalTxnsMetadatasPostRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
