<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\Details;
use PayrixLib\Models\ErrorItem;
use PayrixLib\Models\TerminalTxnsResponse;
use PayrixLib\Models\TerminalTxnsResponseItem;

/**
 * Builder for model TerminalTxnsResponseItem
 *
 * @see TerminalTxnsResponseItem
 */
class TerminalTxnsResponseItemBuilder
{
    /**
     * @var TerminalTxnsResponseItem
     */
    private $instance;

    private function __construct(TerminalTxnsResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terminal Txns Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new TerminalTxnsResponseItem());
    }

    /**
     * Sets data field.
     *
     * @param TerminalTxnsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorItem[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Terminal Txns Response Item object.
     */
    public function build(): TerminalTxnsResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
