<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models\Builders;

use Core\Utils\CoreHelper;
use PayrixLib\Models\TerminalTxnResultsResponseItem;
use PayrixLib\Models\TerminalTxnResultsResponseResult;

/**
 * Builder for model TerminalTxnResultsResponseResult
 *
 * @see TerminalTxnResultsResponseResult
 */
class TerminalTxnResultsResponseResultBuilder
{
    /**
     * @var TerminalTxnResultsResponseResult
     */
    private $instance;

    private function __construct(TerminalTxnResultsResponseResult $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terminal Txn Results Response Result Builder object.
     */
    public static function init(): self
    {
        return new self(new TerminalTxnResultsResponseResult());
    }

    /**
     * Sets response field.
     *
     * @param TerminalTxnResultsResponseItem|null $value
     */
    public function response(?TerminalTxnResultsResponseItem $value): self
    {
        $this->instance->setResponse($value);
        return $this;
    }

    /**
     * Initializes a new Terminal Txn Results Response Result object.
     */
    public function build(): TerminalTxnResultsResponseResult
    {
        return CoreHelper::clone($this->instance);
    }
}
