<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Controllers;

use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\QueryParam;
use Core\Request\Parameters\TemplateParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use PayrixLib\Exceptions\ApiException;
use PayrixLib\Exceptions\ErrorFourHundredException;
use PayrixLib\Models\FraudSightResultsResponseResult;

class FraudSightResultsController extends BaseController
{
    /**
     * Query a fraudSightResults.
     *
     * @param string $id The ID of this Fraud Sight Results.
     * @param string|null $requestToken A custom, one-time identifier for any API request (GET, PUT,
     *        POST, or DELETE). Blocks future requests with the same token for 48 hours, ensuring
     *        only the first request is processed. Valid values can contain 1-100 alphanumeric and
     *        special characters. See <a href="/apis/payrix/dev-int-
     *        guide/references/authentication/request-tokens" target="_blank">Request Tokens</a>
     *        for more information.
     * @param string|null $embed Use the embed query parameter to include full object(s) of related
     *        resource(s) directly within the API response. This allows retrieval of associated
     *        resources in a single request, reducing the need for multiple round-trips.
     *        Format: GET https://{server}.payrix.com/{endpoint}?embed={relatedObject}
     *
     * @return FraudSightResultsResponseResult Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getFraudSightResultsId(
        string $id,
        ?string $requestToken = null,
        ?string $embed = null
    ): FraudSightResultsResponseResult {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/valueAddedServices/fraudSightResults/{id}')
            ->auth('apiKey', 'sessionKey', 'txnSessionKey')
            ->parameters(
                TemplateParam::init('id', $id),
                HeaderParam::init('request-token', $requestToken),
                QueryParam::init('embed', $embed)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('400', ErrorType::init('Error', ErrorFourHundredException::class))
            ->type(FraudSightResultsResponseResult::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Query a fraudSightResults.
     *
     * @param string|null $requestToken A custom, one-time identifier for any API request (GET, PUT,
     *        POST, or DELETE). Blocks future requests with the same token for 48 hours, ensuring
     *        only the first request is processed. Valid values can contain 1-100 alphanumeric and
     *        special characters. See <a href="/apis/payrix/dev-int-
     *        guide/references/authentication/request-tokens" target="_blank">Request Tokens</a>
     *        for more information.
     * @param string|null $search Set this header to filter or sort the list of resources that the
     *        method returns.
     *        See [Searches](page:welcome#searches) for detailed information and examples on how
     *        to use search header.
     * @param string|null $totals To configure a request to return a total for all instances of a
     *        field in a result set,  use the totals header in the format
     *        `totals={operator}[]={key}`.  This will calculate the desired total and return it in
     *        the `details > totals` object of the response.  For instance, if you want to sum the
     *        `total` field of all transactions,  you would use the `sum` operator. The response
     *        will include the result set,  along with the calculated total in the `details`
     *        section. See [Collection Operators](page:welcome#collection-operators) for detailed
     *        information and examples on how to use totals header.
     * @param int|null $pageNumber Set this path parameter to request a specific page of records.
     *        For example, set `?page[number]=2` to retrieve the second page of records for this
     *        request.
     * @param int|null $pageLimit Set this path parameter to request up to a specific amount of
     *        records. By default 30 records are retrieved per page. The maximum limit that can be
     *        set is 100.
     *        For example, set `?page[limit]=50` to retrieve up to 50 records for this request.
     * @param string|null $embed Use the embed query parameter to include full object(s) of related
     *        resource(s) directly within the API response. This allows retrieval of associated
     *        resources in a single request, reducing the need for multiple round-trips.
     *        Format: GET https://{server}.payrix.com/{endpoint}?embed={relatedObject}
     *
     * @return FraudSightResultsResponseResult Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getFraudSightResults(
        ?string $requestToken = null,
        ?string $search = null,
        ?string $totals = null,
        ?int $pageNumber = null,
        ?int $pageLimit = null,
        ?string $embed = null
    ): FraudSightResultsResponseResult {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/valueAddedServices/fraudSightResults')
            ->auth('apiKey', 'sessionKey', 'txnSessionKey')
            ->parameters(
                HeaderParam::init('request-token', $requestToken),
                HeaderParam::init('search', $search),
                HeaderParam::init('totals', $totals),
                QueryParam::init('page[number]', $pageNumber),
                QueryParam::init('page[limit]', $pageLimit),
                QueryParam::init('embed', $embed)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('400', ErrorType::init('Error', ErrorFourHundredException::class))
            ->type(FraudSightResultsResponseResult::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
