<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Exceptions;

use PayrixLib\ApiHelper;

class ErrorFourHundredException extends ApiException
{
    /**
     * @var \PayrixLib\Models\ErrorFourHundredProperties[]|null
     */
    private $errors;

    /**
     * Returns Errors.
     * An array of zero or more errors that occurred when the API processed the request.
     *
     * @return \PayrixLib\Models\ErrorFourHundredProperties[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     * An array of zero or more errors that occurred when the API processed the request.
     *
     * @maps errors
     *
     * @param \PayrixLib\Models\ErrorFourHundredProperties[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Converts the ErrorFourHundredException object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorFourHundredException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ErrorFourHundredException', ['errors' => $this->errors], parent::__toString());
    }
}
