<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class AlertsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|LoginsResponse|null
     */
    private $login;

    /**
     * @var string|LoginsResponse|null
     */
    private $forlogin;

    /**
     * @var string|TeamsResponse|null
     */
    private $team;

    /**
     * @var string|DivisionsResponse|null
     */
    private $division;

    /**
     * @var string|PartitionsResponse|null
     */
    private $partition;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var AlertActionsResponse[]|null
     */
    private $alertActions;

    /**
     * @var AlertTriggersResponse[]|null
     */
    private $alertTriggers;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Login.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The identifier of the Login that created this resource.
     *
     * @maps login
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Forlogin.
     * The identifier of the Login that this Alert applies to.
     *
     * @return string|LoginsResponse|null
     */
    public function getForlogin()
    {
        return $this->forlogin;
    }

    /**
     * Sets Forlogin.
     * The identifier of the Login that this Alert applies to.
     *
     * @maps forlogin
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $forlogin
     */
    public function setForlogin($forlogin): void
    {
        $this->forlogin = $forlogin;
    }

    /**
     * Returns Team.
     * The identifier (ID) of the team that this Alert relates to. The Alert is triggered based on the
     * activity of this Team.
     *
     * @return string|TeamsResponse|null
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * Sets Team.
     * The identifier (ID) of the team that this Alert relates to. The Alert is triggered based on the
     * activity of this Team.
     *
     * @maps team
     * @mapsBy anyOf(anyOf(string,TeamsResponse),null)
     *
     * @param string|TeamsResponse|null $team
     */
    public function setTeam($team): void
    {
        $this->team = $team;
    }

    /**
     * Returns Division.
     * The identifier of the Division that this Alert applies to.
     *
     * @return string|DivisionsResponse|null
     */
    public function getDivision()
    {
        return $this->division;
    }

    /**
     * Sets Division.
     * The identifier of the Division that this Alert applies to.
     *
     * @maps division
     * @mapsBy anyOf(anyOf(string,DivisionsResponse),null)
     *
     * @param string|DivisionsResponse|null $division
     */
    public function setDivision($division): void
    {
        $this->division = $division;
    }

    /**
     * Returns Partition.
     * The partition for which this Alerts applies.
     *
     * @return string|PartitionsResponse|null
     */
    public function getPartition()
    {
        return $this->partition;
    }

    /**
     * Sets Partition.
     * The partition for which this Alerts applies.
     *
     * @maps partition
     * @mapsBy anyOf(anyOf(string,PartitionsResponse),null)
     *
     * @param string|PartitionsResponse|null $partition
     */
    public function setPartition($partition): void
    {
        $this->partition = $partition;
    }

    /**
     * Returns Name.
     * The name of this Alert.
     * This field is stored as a text string and must be between 1 and 100 characters long.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of this Alert.
     * This field is stored as a text string and must be between 1 and 100 characters long.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Description.
     * Description of Alerts.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description of Alerts.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Alert Actions.
     *
     * @return AlertActionsResponse[]|null
     */
    public function getAlertActions(): ?array
    {
        return $this->alertActions;
    }

    /**
     * Sets Alert Actions.
     *
     * @maps alertActions
     *
     * @param AlertActionsResponse[]|null $alertActions
     */
    public function setAlertActions(?array $alertActions): void
    {
        $this->alertActions = $alertActions;
    }

    /**
     * Returns Alert Triggers.
     *
     * @return AlertTriggersResponse[]|null
     */
    public function getAlertTriggers(): ?array
    {
        return $this->alertTriggers;
    }

    /**
     * Sets Alert Triggers.
     *
     * @maps alertTriggers
     *
     * @param AlertTriggersResponse[]|null $alertTriggers
     */
    public function setAlertTriggers(?array $alertTriggers): void
    {
        $this->alertTriggers = $alertTriggers;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Converts the AlertsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the AlertsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AlertsResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'login' => $this->login,
                'forlogin' => $this->forlogin,
                'team' => $this->team,
                'division' => $this->division,
                'partition' => $this->partition,
                'name' => $this->name,
                'description' => $this->description,
                'alertActions' => $this->alertActions,
                'alertTriggers' => $this->alertTriggers,
                'inactive' => $this->inactive,
                'frozen' => $this->frozen
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']            = $this->id;
        }
        if (isset($this->created)) {
            $json['created']       = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']      = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']       =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']      = $this->modifier;
        }
        if (isset($this->login)) {
            $json['login']         =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->login,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->forlogin)) {
            $json['forlogin']      =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->forlogin,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->team)) {
            $json['team']          =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->team,
                    'anyOf(anyOf(string,TeamsResponse),null)'
                );
        }
        if (isset($this->division)) {
            $json['division']      =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->division,
                    'anyOf(anyOf(string,DivisionsResponse),null)'
                );
        }
        if (isset($this->partition)) {
            $json['partition']     =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->partition,
                    'anyOf(anyOf(string,PartitionsResponse),null)'
                );
        }
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        if (isset($this->description)) {
            $json['description']   = $this->description;
        }
        if (isset($this->alertActions)) {
            $json['alertActions']  = $this->alertActions;
        }
        if (isset($this->alertTriggers)) {
            $json['alertTriggers'] = $this->alertTriggers;
        }
        if (isset($this->inactive)) {
            $json['inactive']      = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']        = FrozenEnum::checkValue($this->frozen);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
