<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class ChangeRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|null
     */
    private $deleted;

    /**
     * @var string|LoginsResponse|null
     */
    private $login;

    /**
     * @var int|null
     */
    private $authType;

    /**
     * @var string|null
     */
    private $operation;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $reasonType;

    /**
     * @var string|null
     */
    private $reason;

    /**
     * @var string|null
     */
    private $changes;

    /**
     * @var string|null
     */
    private $model;

    /**
     * @var string|AccountsResponse|null
     */
    private $recordId;

    /**
     * @var string|EntitiesResponse|null
     */
    private $entity;

    /**
     * @var string|LoginsResponse|null
     */
    private $analyst;

    /**
     * @var string|null
     */
    private $reviewed;

    /**
     * @var VerificationRefsResponse|null
     */
    private $verificationRef;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Deleted.
     * In case resource is deleted, this field will then show the date it occurred. The format should be
     * YYYY-MM-DD HH:MM:SS
     */
    public function getDeleted(): ?string
    {
        return $this->deleted;
    }

    /**
     * Sets Deleted.
     * In case resource is deleted, this field will then show the date it occurred. The format should be
     * YYYY-MM-DD HH:MM:SS
     *
     * @maps deleted
     */
    public function setDeleted(?string $deleted): void
    {
        $this->deleted = $deleted;
    }

    /**
     * Returns Login.
     * The identifier of the Login associated with this ChangeRequest.
     *
     * @return string|LoginsResponse|null
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The identifier of the Login associated with this ChangeRequest.
     *
     * @maps login
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Auth Type.
     * Auth Type that originate the request.
     */
    public function getAuthType(): ?int
    {
        return $this->authType;
    }

    /**
     * Sets Auth Type.
     * Auth Type that originate the request.
     *
     * @maps authType
     */
    public function setAuthType(?int $authType): void
    {
        $this->authType = $authType;
    }

    /**
     * Returns Operation.
     * The operation being performed on the resource.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `create` - **When creating a model.**
     * - `update` - **When updating a model.**
     *
     * </details>
     */
    public function getOperation(): ?string
    {
        return $this->operation;
    }

    /**
     * Sets Operation.
     * The operation being performed on the resource.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `create` - **When creating a model.**
     * - `update` - **When updating a model.**
     *
     * </details>
     *
     * @maps operation
     * @factory \PayrixLib\Models\ChangeRequestOperationEnum::checkValue
     */
    public function setOperation(?string $operation): void
    {
        $this->operation = $operation;
    }

    /**
     * Returns Status.
     * The status of the requested change.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `pending` - **The Change Request has a pending status.**
     * - `manualReview` - **The Change Request was escalated to be manually reviewed.**
     * - `approved` - **The Change Request has been approved.**
     * - `declined` - **The Change Request was declined.**
     *
     * </details>
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the requested change.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `pending` - **The Change Request has a pending status.**
     * - `manualReview` - **The Change Request was escalated to be manually reviewed.**
     * - `approved` - **The Change Request has been approved.**
     * - `declined` - **The Change Request was declined.**
     *
     * </details>
     *
     * @maps status
     * @factory \PayrixLib\Models\ChangeRequestStatusEnum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Reason Type.
     * A type which categorizes the reason, in case the change was declined.
     */
    public function getReasonType(): ?string
    {
        return $this->reasonType;
    }

    /**
     * Sets Reason Type.
     * A type which categorizes the reason, in case the change was declined.
     *
     * @maps reasonType
     */
    public function setReasonType(?string $reasonType): void
    {
        $this->reasonType = $reasonType;
    }

    /**
     * Returns Reason.
     * The reason in case the change was declined.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * The reason in case the change was declined.
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Returns Changes.
     * A JSON encoded string with the request payload
     */
    public function getChanges(): ?string
    {
        return $this->changes;
    }

    /**
     * Sets Changes.
     * A JSON encoded string with the request payload
     *
     * @maps changes
     */
    public function setChanges(?string $changes): void
    {
        $this->changes = $changes;
    }

    /**
     * Returns Model.
     * The model being changed.
     */
    public function getModel(): ?string
    {
        return $this->model;
    }

    /**
     * Sets Model.
     * The model being changed.
     *
     * @maps model
     */
    public function setModel(?string $model): void
    {
        $this->model = $model;
    }

    /**
     * Returns Record Id.
     * The id of the model, only set when operation is update.
     *
     * @return string|AccountsResponse|null
     */
    public function getRecordId()
    {
        return $this->recordId;
    }

    /**
     * Sets Record Id.
     * The id of the model, only set when operation is update.
     *
     * @maps recordId
     * @mapsBy anyOf(anyOf(string,AccountsResponse),null)
     *
     * @param string|AccountsResponse|null $recordId
     */
    public function setRecordId($recordId): void
    {
        $this->recordId = $recordId;
    }

    /**
     * Returns Entity.
     * The identifier of the Entity associated with this Account.
     *
     * @return string|EntitiesResponse|null
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Sets Entity.
     * The identifier of the Entity associated with this Account.
     *
     * @maps entity
     * @mapsBy anyOf(anyOf(string,EntitiesResponse),null)
     *
     * @param string|EntitiesResponse|null $entity
     */
    public function setEntity($entity): void
    {
        $this->entity = $entity;
    }

    /**
     * Returns Analyst.
     * The person who review the request.
     *
     * @return string|LoginsResponse|null
     */
    public function getAnalyst()
    {
        return $this->analyst;
    }

    /**
     * Sets Analyst.
     * The person who review the request.
     *
     * @maps analyst
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $analyst
     */
    public function setAnalyst($analyst): void
    {
        $this->analyst = $analyst;
    }

    /**
     * Returns Reviewed.
     * If this change request was reviewed. The format should be YYYY-MM-DD HH:MM:SS
     */
    public function getReviewed(): ?string
    {
        return $this->reviewed;
    }

    /**
     * Sets Reviewed.
     * If this change request was reviewed. The format should be YYYY-MM-DD HH:MM:SS
     *
     * @maps reviewed
     */
    public function setReviewed(?string $reviewed): void
    {
        $this->reviewed = $reviewed;
    }

    /**
     * Returns Verification Ref.
     */
    public function getVerificationRef(): ?VerificationRefsResponse
    {
        return $this->verificationRef;
    }

    /**
     * Sets Verification Ref.
     *
     * @maps verificationRef
     */
    public function setVerificationRef(?VerificationRefsResponse $verificationRef): void
    {
        $this->verificationRef = $verificationRef;
    }

    /**
     * Converts the ChangeRequest object to a human-readable string representation.
     *
     * @return string The string representation of the ChangeRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ChangeRequest',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'deleted' => $this->deleted,
                'login' => $this->login,
                'authType' => $this->authType,
                'operation' => $this->operation,
                'status' => $this->status,
                'reasonType' => $this->reasonType,
                'reason' => $this->reason,
                'changes' => $this->changes,
                'model' => $this->model,
                'recordId' => $this->recordId,
                'entity' => $this->entity,
                'analyst' => $this->analyst,
                'reviewed' => $this->reviewed,
                'verificationRef' => $this->verificationRef
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']              = $this->id;
        }
        if (isset($this->created)) {
            $json['created']         = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']        = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']         =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']        = $this->modifier;
        }
        if (isset($this->deleted)) {
            $json['deleted']         = $this->deleted;
        }
        if (isset($this->login)) {
            $json['login']           =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->login,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->authType)) {
            $json['authType']        = $this->authType;
        }
        if (isset($this->operation)) {
            $json['operation']       = ChangeRequestOperationEnum::checkValue($this->operation);
        }
        if (isset($this->status)) {
            $json['status']          = ChangeRequestStatusEnum::checkValue($this->status);
        }
        if (isset($this->reasonType)) {
            $json['reasonType']      = $this->reasonType;
        }
        if (isset($this->reason)) {
            $json['reason']          = $this->reason;
        }
        if (isset($this->changes)) {
            $json['changes']         = $this->changes;
        }
        if (isset($this->model)) {
            $json['model']           = $this->model;
        }
        if (isset($this->recordId)) {
            $json['recordId']        =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->recordId,
                    'anyOf(anyOf(string,AccountsResponse),null)'
                );
        }
        if (isset($this->entity)) {
            $json['entity']          =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->entity,
                    'anyOf(anyOf(string,EntitiesResponse),null)'
                );
        }
        if (isset($this->analyst)) {
            $json['analyst']         =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->analyst,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->reviewed)) {
            $json['reviewed']        = $this->reviewed;
        }
        if (isset($this->verificationRef)) {
            $json['verificationRef'] = $this->verificationRef;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
