<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class ChargebackPlatformEnum
{
    /**
     * Apple platform.
     */
    public const APPLE = 'APPLE';

    /**
     * Elavon platform.
     */
    public const ELAVON = 'ELAVON';

    /**
     * First Data platform.
     */
    public const FIRSTDATA = 'FIRSTDATA';

    /**
     * Google platform.
     */
    public const GOOGLE = 'GOOGLE';

    /**
     * Vantiv platform.
     */
    public const VANTIV = 'VANTIV';

    /**
     * VCore platform.
     */
    public const VCORE = 'VCORE';

    /**
     * Wells ACH platform.
     */
    public const WELLSACH = 'WELLSACH';

    /**
     * Wells Fargo platform.
     */
    public const WELLSFARGO = 'WELLSFARGO';

    /**
     * WF Single platform.
     */
    public const WFSINGLE = 'WFSINGLE';

    private const _ALL_VALUES = [
        self::APPLE,
        self::ELAVON,
        self::FIRSTDATA,
        self::GOOGLE,
        self::VANTIV,
        self::VCORE,
        self::WELLSACH,
        self::WELLSFARGO,
        self::WFSINGLE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ChargebackPlatformEnum.");
    }
}
