<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class ChargebackMessageTypeEnum
{
    /**
     * Assign the chargeback.
     */
    public const ASSIGN = 'assign';

    /**
     * Add a note to the chargeback.
     */
    public const NOTATE = 'notate';

    /**
     * Accept Liability for the Chargeback amount.
     */
    public const ACCEPTLIABILITY = 'acceptLiability';

    /**
     * Create a pre-arbitration case.
     */
    public const CREATEPREARBITRATION = 'createPreArbitration';

    /**
     * Represent the chargeback.
     */
    public const REPRESENT = 'represent';

    /**
     * Respond to the chargeback.
     */
    public const RESPOND = 'respond';

    /**
     * Request Arbitration. The Merchant wishes to enter arbitration to determine the outcome of the
     * Chargeback.
     */
    public const REQUESTARBITRATION = 'requestArbitration';

    /**
     * Create an arbitration case.
     */
    public const CREATEARBITRATION = 'createArbitration';

    /**
     * Request a pre-arbitration case.
     */
    public const REQUESTPREARBITRATION = 'requestPreArbitration';

    /**
     * Request resolution to a pre-arbitration case.
     */
    public const REQUESTRESOLUTIONTOPREARBITRATION = 'requestResolutionToPreArbitration';

    /**
     * Respond to a dispute.
     */
    public const RESPONDTODISPUTE = 'respondToDispute';

    /**
     * Respond to a pre-arbitration case.
     */
    public const RESPONDTOPREARBITRATION = 'respondToPreArbitration';

    /**
     * Unaccept the chargeback.
     */
    public const UNACCEPT = 'unaccept';

    private const _ALL_VALUES = [
        self::ASSIGN,
        self::NOTATE,
        self::ACCEPTLIABILITY,
        self::CREATEPREARBITRATION,
        self::REPRESENT,
        self::RESPOND,
        self::REQUESTARBITRATION,
        self::CREATEARBITRATION,
        self::REQUESTPREARBITRATION,
        self::REQUESTRESOLUTIONTOPREARBITRATION,
        self::RESPONDTODISPUTE,
        self::RESPONDTOPREARBITRATION,
        self::UNACCEPT
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ChargebackMessageTypeEnum.");
    }
}
