<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class CredentialTypeEnum
{
    /**
     * Processes a sale and charges the customer.
     */
    public const TRANSACTION = 'transaction';

    /**
     * Batch processing.
     */
    public const BATCH = 'batch';

    /**
     * Boarding process.
     */
    public const BOARDING = 'boarding';

    /**
     * Updates to payment information.
     */
    public const PAYMENTUPDATES = 'paymentUpdates';

    /**
     * Payout processing.
     */
    public const PAYOUT = 'payout';

    /**
     * Credit payouts.
     */
    public const PAYOUTCREDIT = 'payoutCredit';

    /**
     * Debit payouts.
     */
    public const PAYOUTDEBIT = 'payoutDebit';

    /**
     * Chargeback processing.
     */
    public const CHARGEBACK = 'chargeback';

    /**
     * Transaction reporting.
     */
    public const TXNREPORT = 'txnReport';

    /**
     * Account-related operations.
     */
    public const ACCOUNT = 'account';

    /**
     * Decision-making for entities.
     */
    public const ENTITYDECISION = 'entityDecision';

    /**
     * Transaction checks.
     */
    public const TXNCHECK = 'txnCheck';

    /**
     * Reporting for payouts.
     */
    public const PAYOUTREPORT = 'payoutReport';

    /**
     * Reporting for fees.
     */
    public const FEEREPORT = 'feeReport';

    /**
     * Reporting for chargebacks.
     */
    public const CHARGEBACKREPORT = 'chargebackReport';

    /**
     * Reporting for BINs.
     */
    public const BINREPORT = 'binReport';

    /**
     * Watchlist management.
     */
    public const WATCHLIST = 'watchlist';

    /**
     * Encryption-related operations.
     */
    public const ENCRYPTION = 'encryption';

    /**
     * Requests for changes.
     */
    public const CHANGEREQUEST = 'changeRequest';

    private const _ALL_VALUES = [
        self::TRANSACTION,
        self::BATCH,
        self::BOARDING,
        self::PAYMENTUPDATES,
        self::PAYOUT,
        self::PAYOUTCREDIT,
        self::PAYOUTDEBIT,
        self::CHARGEBACK,
        self::TXNREPORT,
        self::ACCOUNT,
        self::ENTITYDECISION,
        self::TXNCHECK,
        self::PAYOUTREPORT,
        self::FEEREPORT,
        self::CHARGEBACKREPORT,
        self::BINREPORT,
        self::WATCHLIST,
        self::ENCRYPTION,
        self::CHANGEREQUEST
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for CredentialTypeEnum.");
    }
}
