<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class CustomersPostRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $login;

    /**
     * @var array
     */
    private $merchant = [];

    /**
     * @var array
     */
    private $entity = [];

    /**
     * @var string|null
     */
    private $first;

    /**
     * @var string|null
     */
    private $middle;

    /**
     * @var string|null
     */
    private $last;

    /**
     * @var string|null
     */
    private $company;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $shippingFirst;

    /**
     * @var string|null
     */
    private $shippingMiddle;

    /**
     * @var string|null
     */
    private $shippingLast;

    /**
     * @var string|null
     */
    private $shippingCompany;

    /**
     * @var string|null
     */
    private $shippingAddress1;

    /**
     * @var string|null
     */
    private $shippingAddress2;

    /**
     * @var string|null
     */
    private $shippingCity;

    /**
     * @var string|null
     */
    private $shippingState;

    /**
     * @var string|null
     */
    private $shippingZip;

    /**
     * @var string|null
     */
    private $shippingCountry;

    /**
     * @var string|null
     */
    private $shippingPhone;

    /**
     * @var string|null
     */
    private $shippingFax;

    /**
     * @var string|null
     */
    private $custom;

    /**
     * @var string|null
     */
    private $address1;

    /**
     * @var string|null
     */
    private $address2;

    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string|null
     */
    private $zip;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $phone;

    /**
     * @var string|null
     */
    private $fax;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var InvoicesPostRequest[]|null
     */
    private $invoices;

    /**
     * @var TokenPostRequest[]|null
     */
    private $tokens;

    /**
     * @param string $login
     */
    public function __construct(string $login)
    {
        $this->login = $login;
    }

    /**
     * Returns Login.
     * The ID of the Login that owns this resource.
     */
    public function getLogin(): string
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The ID of the Login that owns this resource.
     *
     * @required
     * @maps login
     */
    public function setLogin(string $login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Merchant.
     * The ID of the Merchant associated with this Customer.
     */
    public function getMerchant(): ?string
    {
        if (count($this->merchant) == 0) {
            return null;
        }
        return $this->merchant['value'];
    }

    /**
     * Sets Merchant.
     * The ID of the Merchant associated with this Customer.
     *
     * @maps merchant
     */
    public function setMerchant(?string $merchant): void
    {
        $this->merchant['value'] = $merchant;
    }

    /**
     * Unsets Merchant.
     * The ID of the Merchant associated with this Customer.
     */
    public function unsetMerchant(): void
    {
        $this->merchant = [];
    }

    /**
     * Returns Entity.
     * The ID of the Entity that owns this resource.
     */
    public function getEntity(): ?string
    {
        if (count($this->entity) == 0) {
            return null;
        }
        return $this->entity['value'];
    }

    /**
     * Sets Entity.
     * The ID of the Entity that owns this resource.
     *
     * @maps entity
     */
    public function setEntity(?string $entity): void
    {
        $this->entity['value'] = $entity;
    }

    /**
     * Unsets Entity.
     * The ID of the Entity that owns this resource.
     */
    public function unsetEntity(): void
    {
        $this->entity = [];
    }

    /**
     * Returns First.
     * The first name associated with this Customer.
     */
    public function getFirst(): ?string
    {
        return $this->first;
    }

    /**
     * Sets First.
     * The first name associated with this Customer.
     *
     * @maps first
     */
    public function setFirst(?string $first): void
    {
        $this->first = $first;
    }

    /**
     * Returns Middle.
     * The middle name associated with this Customer.
     */
    public function getMiddle(): ?string
    {
        return $this->middle;
    }

    /**
     * Sets Middle.
     * The middle name associated with this Customer.
     *
     * @maps middle
     */
    public function setMiddle(?string $middle): void
    {
        $this->middle = $middle;
    }

    /**
     * Returns Last.
     * The last name associated with this Customer.
     */
    public function getLast(): ?string
    {
        return $this->last;
    }

    /**
     * Sets Last.
     * The last name associated with this Customer.
     *
     * @maps last
     */
    public function setLast(?string $last): void
    {
        $this->last = $last;
    }

    /**
     * Returns Company.
     * The name of the company associated with this Customer.
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * Sets Company.
     * The name of the company associated with this Customer.
     *
     * @maps company
     */
    public function setCompany(?string $company): void
    {
        $this->company = $company;
    }

    /**
     * Returns Email.
     * The email address of this Customer.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * The email address of this Customer.
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Shipping First.
     * The first name associated with this Customer's shipping information.
     */
    public function getShippingFirst(): ?string
    {
        return $this->shippingFirst;
    }

    /**
     * Sets Shipping First.
     * The first name associated with this Customer's shipping information.
     *
     * @maps shippingFirst
     */
    public function setShippingFirst(?string $shippingFirst): void
    {
        $this->shippingFirst = $shippingFirst;
    }

    /**
     * Returns Shipping Middle.
     * The middle name associated with this Customer's shipping information.
     */
    public function getShippingMiddle(): ?string
    {
        return $this->shippingMiddle;
    }

    /**
     * Sets Shipping Middle.
     * The middle name associated with this Customer's shipping information.
     *
     * @maps shippingMiddle
     */
    public function setShippingMiddle(?string $shippingMiddle): void
    {
        $this->shippingMiddle = $shippingMiddle;
    }

    /**
     * Returns Shipping Last.
     * The last name associated with this Customer's shipping information.
     */
    public function getShippingLast(): ?string
    {
        return $this->shippingLast;
    }

    /**
     * Sets Shipping Last.
     * The last name associated with this Customer's shipping information.
     *
     * @maps shippingLast
     */
    public function setShippingLast(?string $shippingLast): void
    {
        $this->shippingLast = $shippingLast;
    }

    /**
     * Returns Shipping Company.
     * The name of the company associated with this Customer's shipping information.
     */
    public function getShippingCompany(): ?string
    {
        return $this->shippingCompany;
    }

    /**
     * Sets Shipping Company.
     * The name of the company associated with this Customer's shipping information.
     *
     * @maps shippingCompany
     */
    public function setShippingCompany(?string $shippingCompany): void
    {
        $this->shippingCompany = $shippingCompany;
    }

    /**
     * Returns Shipping Address 1.
     * The first line of the address associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getShippingAddress1(): ?string
    {
        return $this->shippingAddress1;
    }

    /**
     * Sets Shipping Address 1.
     * The first line of the address associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps shippingAddress1
     */
    public function setShippingAddress1(?string $shippingAddress1): void
    {
        $this->shippingAddress1 = $shippingAddress1;
    }

    /**
     * Returns Shipping Address 2.
     * The second line of the address associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getShippingAddress2(): ?string
    {
        return $this->shippingAddress2;
    }

    /**
     * Sets Shipping Address 2.
     * The second line of the address associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps shippingAddress2
     */
    public function setShippingAddress2(?string $shippingAddress2): void
    {
        $this->shippingAddress2 = $shippingAddress2;
    }

    /**
     * Returns Shipping City.
     * The name of the city associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getShippingCity(): ?string
    {
        return $this->shippingCity;
    }

    /**
     * Sets Shipping City.
     * The name of the city associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps shippingCity
     */
    public function setShippingCity(?string $shippingCity): void
    {
        $this->shippingCity = $shippingCity;
    }

    /**
     * Returns Shipping State.
     * The U.S. state or Canadian province relevant to the address provided here. If the location is within
     * the U.S. and Canada, specify the 2-character postal abbreviation for the state. If the location is
     * outside of the U.S. and Canada, provide the full state name. This field is stored as a text string
     * and must be between 2 and 100 characters long.
     *
     *
     * <details>
     * <summary>U.S. States</summary>
     *
     * - `AK` - **Alaska (US)**
     *
     * - `AR` - **Arkansas (US)**
     *
     * - `AL` - **Alabama (US)**
     *
     * - `AZ` - **Arizona (US)**
     *
     * - `CA` - **California (US)**
     *
     * - `CO` - **Colorado (US)**
     *
     * - `CT` - **Connecticut (US)**
     *
     * - `DE` - **Delaware (US)**
     *
     * - `FL` - **Florida (US)**
     *
     * - `GA` - **Georgia (US)**
     *
     * - `HI` - **Hawaii (US)**
     *
     * - `IA` - **Iowa (US)**
     *
     * - `ID` - **Idaho (US)**
     *
     * - `IL` - **Illinois (US)**
     *
     * - `IN` - **Indiana (US)**
     *
     * - `KY` - **Kentucky (US)**
     *
     * - `KS` - **Kansas (US)**
     *
     * - `LA` - **Louisiana (US)**
     *
     * - `MA` - **Massachusetts (US)**
     *
     * - `MD` - **Maryland (US)**
     *
     * - `ME` - **Maine (US)**
     *
     * - `MI` - **Michigan (US)**
     *
     * - `MN` - **Minnesota (US)**
     *
     * - `MO` - **Missouri (US)**
     *
     * - `MS` - **Mississippi (US)**
     *
     * - `MT` - **Montana (US)**
     *
     * - `NC` - **North Carolina (US)**
     *
     * - `ND` - **North Dakota (US)**
     *
     * - `NE` - **Nebraska (US)**
     *
     * - `NH` - **New Hampshire (US)**
     *
     * - `NJ` - **New Jersey (US)**
     *
     * - `NM` - **New Mexico (US)**
     *
     * - `NV` - **Nevada (US)**
     *
     * - `NY` - **New York (US)**
     *
     * - `OH` - **Ohio (US)**
     *
     * - `OK`- **Oklahoma (US)**
     *
     * - `OR` - **Oregon (US)**
     *
     * - `PA` - **Pennsylvania (US)**
     *
     * - `RI` - **Rhode Island (US)**
     *
     * - `SC`- **South Carolina (US)**
     *
     * - `SD` - **South Dakota (US)**
     *
     * - `TN` - **Tennessee (US)**
     *
     * - `TX` - **Texas (US)**
     *
     * - `UT` - **Utah (US)**
     *
     * - `VA` - **Virginia (US)**
     *
     * - `VT` - **Vermont (US)**
     *
     * - `WA` - **Washington (US)**
     *
     * - `WI` - **Wisconsin (US)**
     *
     * - `WV` - **West Virginia (US)**
     *
     * - `WY` - **Wyoming (US)**
     * </details>
     *
     *
     *
     * <details>
     * <summary>Canada Provinces and Territories</summary>
     *
     * - `AB` - **Alberta (CAN)**
     *
     * - `BC` - **British Columbia (CAN)**
     *
     * - `MB` - **Manitoba (CAN)**
     *
     * - `ON` - **Ontario (CAN)**
     *
     * - `NS` - **Nova Scotia (CAN)**
     *
     * - `NB` - **New Brunswick (CAN)**
     *
     * - `NL` - **Newfoundland and Labrador (CAN)**
     *
     * - `NT` - **Northwest Territories (CAN)**
     *
     * - `NU` - **Nunavut (CAN)**
     *
     * - `PE` - **Prince Edward Island (CAN)**
     *
     * - `QC` - **Quebec (CAN)**
     *
     * - `SK` - **Saskatchewan (CAN)**
     *
     * - `YT` - **Yukon (CAN)**
     * </details>
     */
    public function getShippingState(): ?string
    {
        return $this->shippingState;
    }

    /**
     * Sets Shipping State.
     * The U.S. state or Canadian province relevant to the address provided here. If the location is within
     * the U.S. and Canada, specify the 2-character postal abbreviation for the state. If the location is
     * outside of the U.S. and Canada, provide the full state name. This field is stored as a text string
     * and must be between 2 and 100 characters long.
     *
     *
     * <details>
     * <summary>U.S. States</summary>
     *
     * - `AK` - **Alaska (US)**
     *
     * - `AR` - **Arkansas (US)**
     *
     * - `AL` - **Alabama (US)**
     *
     * - `AZ` - **Arizona (US)**
     *
     * - `CA` - **California (US)**
     *
     * - `CO` - **Colorado (US)**
     *
     * - `CT` - **Connecticut (US)**
     *
     * - `DE` - **Delaware (US)**
     *
     * - `FL` - **Florida (US)**
     *
     * - `GA` - **Georgia (US)**
     *
     * - `HI` - **Hawaii (US)**
     *
     * - `IA` - **Iowa (US)**
     *
     * - `ID` - **Idaho (US)**
     *
     * - `IL` - **Illinois (US)**
     *
     * - `IN` - **Indiana (US)**
     *
     * - `KY` - **Kentucky (US)**
     *
     * - `KS` - **Kansas (US)**
     *
     * - `LA` - **Louisiana (US)**
     *
     * - `MA` - **Massachusetts (US)**
     *
     * - `MD` - **Maryland (US)**
     *
     * - `ME` - **Maine (US)**
     *
     * - `MI` - **Michigan (US)**
     *
     * - `MN` - **Minnesota (US)**
     *
     * - `MO` - **Missouri (US)**
     *
     * - `MS` - **Mississippi (US)**
     *
     * - `MT` - **Montana (US)**
     *
     * - `NC` - **North Carolina (US)**
     *
     * - `ND` - **North Dakota (US)**
     *
     * - `NE` - **Nebraska (US)**
     *
     * - `NH` - **New Hampshire (US)**
     *
     * - `NJ` - **New Jersey (US)**
     *
     * - `NM` - **New Mexico (US)**
     *
     * - `NV` - **Nevada (US)**
     *
     * - `NY` - **New York (US)**
     *
     * - `OH` - **Ohio (US)**
     *
     * - `OK`- **Oklahoma (US)**
     *
     * - `OR` - **Oregon (US)**
     *
     * - `PA` - **Pennsylvania (US)**
     *
     * - `RI` - **Rhode Island (US)**
     *
     * - `SC`- **South Carolina (US)**
     *
     * - `SD` - **South Dakota (US)**
     *
     * - `TN` - **Tennessee (US)**
     *
     * - `TX` - **Texas (US)**
     *
     * - `UT` - **Utah (US)**
     *
     * - `VA` - **Virginia (US)**
     *
     * - `VT` - **Vermont (US)**
     *
     * - `WA` - **Washington (US)**
     *
     * - `WI` - **Wisconsin (US)**
     *
     * - `WV` - **West Virginia (US)**
     *
     * - `WY` - **Wyoming (US)**
     * </details>
     *
     *
     *
     * <details>
     * <summary>Canada Provinces and Territories</summary>
     *
     * - `AB` - **Alberta (CAN)**
     *
     * - `BC` - **British Columbia (CAN)**
     *
     * - `MB` - **Manitoba (CAN)**
     *
     * - `ON` - **Ontario (CAN)**
     *
     * - `NS` - **Nova Scotia (CAN)**
     *
     * - `NB` - **New Brunswick (CAN)**
     *
     * - `NL` - **Newfoundland and Labrador (CAN)**
     *
     * - `NT` - **Northwest Territories (CAN)**
     *
     * - `NU` - **Nunavut (CAN)**
     *
     * - `PE` - **Prince Edward Island (CAN)**
     *
     * - `QC` - **Quebec (CAN)**
     *
     * - `SK` - **Saskatchewan (CAN)**
     *
     * - `YT` - **Yukon (CAN)**
     * </details>
     *
     * @maps shippingState
     */
    public function setShippingState(?string $shippingState): void
    {
        $this->shippingState = $shippingState;
    }

    /**
     * Returns Shipping Zip.
     * The ZIP code associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 20 characters long.
     */
    public function getShippingZip(): ?string
    {
        return $this->shippingZip;
    }

    /**
     * Sets Shipping Zip.
     * The ZIP code associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 1 and 20 characters long.
     *
     * @maps shippingZip
     */
    public function setShippingZip(?string $shippingZip): void
    {
        $this->shippingZip = $shippingZip;
    }

    /**
     * Returns Shipping Country.
     * The country associated with this Customer's shipping information.
     * Valid values for this field is the 3-letter ISO code for the country.
     */
    public function getShippingCountry(): ?string
    {
        return $this->shippingCountry;
    }

    /**
     * Sets Shipping Country.
     * The country associated with this Customer's shipping information.
     * Valid values for this field is the 3-letter ISO code for the country.
     *
     * @maps shippingCountry
     * @factory \PayrixLib\Models\CountryEnum::checkValue
     */
    public function setShippingCountry(?string $shippingCountry): void
    {
        $this->shippingCountry = $shippingCountry;
    }

    /**
     * Returns Shipping Phone.
     * The phone number associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     */
    public function getShippingPhone(): ?string
    {
        return $this->shippingPhone;
    }

    /**
     * Sets Shipping Phone.
     * The phone number associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     *
     * @maps shippingPhone
     */
    public function setShippingPhone(?string $shippingPhone): void
    {
        $this->shippingPhone = $shippingPhone;
    }

    /**
     * Returns Shipping Fax.
     * The fax number associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     */
    public function getShippingFax(): ?string
    {
        return $this->shippingFax;
    }

    /**
     * Sets Shipping Fax.
     * The fax number associated with this Customer's shipping information.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     *
     * @maps shippingFax
     */
    public function setShippingFax(?string $shippingFax): void
    {
        $this->shippingFax = $shippingFax;
    }

    /**
     * Returns Custom.
     * Custom, free-form field for client-supplied text, must be between 0 and 1,000 characters long.
     */
    public function getCustom(): ?string
    {
        return $this->custom;
    }

    /**
     * Sets Custom.
     * Custom, free-form field for client-supplied text, must be between 0 and 1,000 characters long.
     *
     * @maps custom
     */
    public function setCustom(?string $custom): void
    {
        $this->custom = $custom;
    }

    /**
     * Returns Address 1.
     * The first line of the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    /**
     * Sets Address 1.
     * The first line of the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps address1
     */
    public function setAddress1(?string $address1): void
    {
        $this->address1 = $address1;
    }

    /**
     * Returns Address 2.
     * The second line of the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    /**
     * Sets Address 2.
     * The second line of the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps address2
     */
    public function setAddress2(?string $address2): void
    {
        $this->address2 = $address2;
    }

    /**
     * Returns City.
     * The name of the city in the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * The name of the city in the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns State.
     * The U.S. state or Canadian province relevant to the address provided here. If the location is within
     * the U.S. and Canada, specify the 2-character postal abbreviation for the state. If the location is
     * outside of the U.S. and Canada, provide the full state name. This field is stored as a text string
     * and must be between 2 and 100 characters long.
     *
     *
     * <details>
     * <summary>U.S. States</summary>
     *
     * - `AK` - **Alaska (US)**
     *
     * - `AR` - **Arkansas (US)**
     *
     * - `AL` - **Alabama (US)**
     *
     * - `AZ` - **Arizona (US)**
     *
     * - `CA` - **California (US)**
     *
     * - `CO` - **Colorado (US)**
     *
     * - `CT` - **Connecticut (US)**
     *
     * - `DE` - **Delaware (US)**
     *
     * - `FL` - **Florida (US)**
     *
     * - `GA` - **Georgia (US)**
     *
     * - `HI` - **Hawaii (US)**
     *
     * - `IA` - **Iowa (US)**
     *
     * - `ID` - **Idaho (US)**
     *
     * - `IL` - **Illinois (US)**
     *
     * - `IN` - **Indiana (US)**
     *
     * - `KY` - **Kentucky (US)**
     *
     * - `KS` - **Kansas (US)**
     *
     * - `LA` - **Louisiana (US)**
     *
     * - `MA` - **Massachusetts (US)**
     *
     * - `MD` - **Maryland (US)**
     *
     * - `ME` - **Maine (US)**
     *
     * - `MI` - **Michigan (US)**
     *
     * - `MN` - **Minnesota (US)**
     *
     * - `MO` - **Missouri (US)**
     *
     * - `MS` - **Mississippi (US)**
     *
     * - `MT` - **Montana (US)**
     *
     * - `NC` - **North Carolina (US)**
     *
     * - `ND` - **North Dakota (US)**
     *
     * - `NE` - **Nebraska (US)**
     *
     * - `NH` - **New Hampshire (US)**
     *
     * - `NJ` - **New Jersey (US)**
     *
     * - `NM` - **New Mexico (US)**
     *
     * - `NV` - **Nevada (US)**
     *
     * - `NY` - **New York (US)**
     *
     * - `OH` - **Ohio (US)**
     *
     * - `OK`- **Oklahoma (US)**
     *
     * - `OR` - **Oregon (US)**
     *
     * - `PA` - **Pennsylvania (US)**
     *
     * - `RI` - **Rhode Island (US)**
     *
     * - `SC`- **South Carolina (US)**
     *
     * - `SD` - **South Dakota (US)**
     *
     * - `TN` - **Tennessee (US)**
     *
     * - `TX` - **Texas (US)**
     *
     * - `UT` - **Utah (US)**
     *
     * - `VA` - **Virginia (US)**
     *
     * - `VT` - **Vermont (US)**
     *
     * - `WA` - **Washington (US)**
     *
     * - `WI` - **Wisconsin (US)**
     *
     * - `WV` - **West Virginia (US)**
     *
     * - `WY` - **Wyoming (US)**
     * </details>
     *
     *
     *
     * <details>
     * <summary>Canada Provinces and Territories</summary>
     *
     * - `AB` - **Alberta (CAN)**
     *
     * - `BC` - **British Columbia (CAN)**
     *
     * - `MB` - **Manitoba (CAN)**
     *
     * - `ON` - **Ontario (CAN)**
     *
     * - `NS` - **Nova Scotia (CAN)**
     *
     * - `NB` - **New Brunswick (CAN)**
     *
     * - `NL` - **Newfoundland and Labrador (CAN)**
     *
     * - `NT` - **Northwest Territories (CAN)**
     *
     * - `NU` - **Nunavut (CAN)**
     *
     * - `PE` - **Prince Edward Island (CAN)**
     *
     * - `QC` - **Quebec (CAN)**
     *
     * - `SK` - **Saskatchewan (CAN)**
     *
     * - `YT` - **Yukon (CAN)**
     * </details>
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * The U.S. state or Canadian province relevant to the address provided here. If the location is within
     * the U.S. and Canada, specify the 2-character postal abbreviation for the state. If the location is
     * outside of the U.S. and Canada, provide the full state name. This field is stored as a text string
     * and must be between 2 and 100 characters long.
     *
     *
     * <details>
     * <summary>U.S. States</summary>
     *
     * - `AK` - **Alaska (US)**
     *
     * - `AR` - **Arkansas (US)**
     *
     * - `AL` - **Alabama (US)**
     *
     * - `AZ` - **Arizona (US)**
     *
     * - `CA` - **California (US)**
     *
     * - `CO` - **Colorado (US)**
     *
     * - `CT` - **Connecticut (US)**
     *
     * - `DE` - **Delaware (US)**
     *
     * - `FL` - **Florida (US)**
     *
     * - `GA` - **Georgia (US)**
     *
     * - `HI` - **Hawaii (US)**
     *
     * - `IA` - **Iowa (US)**
     *
     * - `ID` - **Idaho (US)**
     *
     * - `IL` - **Illinois (US)**
     *
     * - `IN` - **Indiana (US)**
     *
     * - `KY` - **Kentucky (US)**
     *
     * - `KS` - **Kansas (US)**
     *
     * - `LA` - **Louisiana (US)**
     *
     * - `MA` - **Massachusetts (US)**
     *
     * - `MD` - **Maryland (US)**
     *
     * - `ME` - **Maine (US)**
     *
     * - `MI` - **Michigan (US)**
     *
     * - `MN` - **Minnesota (US)**
     *
     * - `MO` - **Missouri (US)**
     *
     * - `MS` - **Mississippi (US)**
     *
     * - `MT` - **Montana (US)**
     *
     * - `NC` - **North Carolina (US)**
     *
     * - `ND` - **North Dakota (US)**
     *
     * - `NE` - **Nebraska (US)**
     *
     * - `NH` - **New Hampshire (US)**
     *
     * - `NJ` - **New Jersey (US)**
     *
     * - `NM` - **New Mexico (US)**
     *
     * - `NV` - **Nevada (US)**
     *
     * - `NY` - **New York (US)**
     *
     * - `OH` - **Ohio (US)**
     *
     * - `OK`- **Oklahoma (US)**
     *
     * - `OR` - **Oregon (US)**
     *
     * - `PA` - **Pennsylvania (US)**
     *
     * - `RI` - **Rhode Island (US)**
     *
     * - `SC`- **South Carolina (US)**
     *
     * - `SD` - **South Dakota (US)**
     *
     * - `TN` - **Tennessee (US)**
     *
     * - `TX` - **Texas (US)**
     *
     * - `UT` - **Utah (US)**
     *
     * - `VA` - **Virginia (US)**
     *
     * - `VT` - **Vermont (US)**
     *
     * - `WA` - **Washington (US)**
     *
     * - `WI` - **Wisconsin (US)**
     *
     * - `WV` - **West Virginia (US)**
     *
     * - `WY` - **Wyoming (US)**
     * </details>
     *
     *
     *
     * <details>
     * <summary>Canada Provinces and Territories</summary>
     *
     * - `AB` - **Alberta (CAN)**
     *
     * - `BC` - **British Columbia (CAN)**
     *
     * - `MB` - **Manitoba (CAN)**
     *
     * - `ON` - **Ontario (CAN)**
     *
     * - `NS` - **Nova Scotia (CAN)**
     *
     * - `NB` - **New Brunswick (CAN)**
     *
     * - `NL` - **Newfoundland and Labrador (CAN)**
     *
     * - `NT` - **Northwest Territories (CAN)**
     *
     * - `NU` - **Nunavut (CAN)**
     *
     * - `PE` - **Prince Edward Island (CAN)**
     *
     * - `QC` - **Quebec (CAN)**
     *
     * - `SK` - **Saskatchewan (CAN)**
     *
     * - `YT` - **Yukon (CAN)**
     * </details>
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Zip.
     * The ZIP code in the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 20 characters long.
     */
    public function getZip(): ?string
    {
        return $this->zip;
    }

    /**
     * Sets Zip.
     * The ZIP code in the address associated with this Customer.
     * This field is stored as a text string and must be between 1 and 20 characters long.
     *
     * @maps zip
     */
    public function setZip(?string $zip): void
    {
        $this->zip = $zip;
    }

    /**
     * Returns Country.
     * The country associated with this Customer.
     * Valid values for this field is the 3-letter ISO code for the country.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * The country associated with this Customer.
     * Valid values for this field is the 3-letter ISO code for the country.
     *
     * @maps country
     * @factory \PayrixLib\Models\CountryEnum::checkValue
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Phone.
     * The phone number associated with this Transaction.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * Sets Phone.
     * The phone number associated with this Transaction.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     *
     * @maps phone
     */
    public function setPhone(?string $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * Returns Fax.
     * The fax number associated with this Customer.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     */
    public function getFax(): ?string
    {
        return $this->fax;
    }

    /**
     * Sets Fax.
     * The fax number associated with this Customer.
     * This field is stored as a text string and must be between 10 and 15 characters long.
     *
     * @maps fax
     */
    public function setFax(?string $fax): void
    {
        $this->fax = $fax;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Invoices.
     *
     * @return InvoicesPostRequest[]|null
     */
    public function getInvoices(): ?array
    {
        return $this->invoices;
    }

    /**
     * Sets Invoices.
     *
     * @maps invoices
     *
     * @param InvoicesPostRequest[]|null $invoices
     */
    public function setInvoices(?array $invoices): void
    {
        $this->invoices = $invoices;
    }

    /**
     * Returns Tokens.
     *
     * @return TokenPostRequest[]|null
     */
    public function getTokens(): ?array
    {
        return $this->tokens;
    }

    /**
     * Sets Tokens.
     *
     * @maps tokens
     *
     * @param TokenPostRequest[]|null $tokens
     */
    public function setTokens(?array $tokens): void
    {
        $this->tokens = $tokens;
    }

    /**
     * Converts the CustomersPostRequest object to a human-readable string representation.
     *
     * @return string The string representation of the CustomersPostRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CustomersPostRequest',
            [
                'login' => $this->login,
                'merchant' => $this->getMerchant(),
                'entity' => $this->getEntity(),
                'first' => $this->first,
                'middle' => $this->middle,
                'last' => $this->last,
                'company' => $this->company,
                'email' => $this->email,
                'shippingFirst' => $this->shippingFirst,
                'shippingMiddle' => $this->shippingMiddle,
                'shippingLast' => $this->shippingLast,
                'shippingCompany' => $this->shippingCompany,
                'shippingAddress1' => $this->shippingAddress1,
                'shippingAddress2' => $this->shippingAddress2,
                'shippingCity' => $this->shippingCity,
                'shippingState' => $this->shippingState,
                'shippingZip' => $this->shippingZip,
                'shippingCountry' => $this->shippingCountry,
                'shippingPhone' => $this->shippingPhone,
                'shippingFax' => $this->shippingFax,
                'custom' => $this->custom,
                'address1' => $this->address1,
                'address2' => $this->address2,
                'city' => $this->city,
                'state' => $this->state,
                'zip' => $this->zip,
                'country' => $this->country,
                'phone' => $this->phone,
                'fax' => $this->fax,
                'frozen' => $this->frozen,
                'inactive' => $this->inactive,
                'invoices' => $this->invoices,
                'tokens' => $this->tokens
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['login']                = $this->login;
        if (!empty($this->merchant)) {
            $json['merchant']         = $this->merchant['value'];
        }
        if (!empty($this->entity)) {
            $json['entity']           = $this->entity['value'];
        }
        if (isset($this->first)) {
            $json['first']            = $this->first;
        }
        if (isset($this->middle)) {
            $json['middle']           = $this->middle;
        }
        if (isset($this->last)) {
            $json['last']             = $this->last;
        }
        if (isset($this->company)) {
            $json['company']          = $this->company;
        }
        if (isset($this->email)) {
            $json['email']            = $this->email;
        }
        if (isset($this->shippingFirst)) {
            $json['shippingFirst']    = $this->shippingFirst;
        }
        if (isset($this->shippingMiddle)) {
            $json['shippingMiddle']   = $this->shippingMiddle;
        }
        if (isset($this->shippingLast)) {
            $json['shippingLast']     = $this->shippingLast;
        }
        if (isset($this->shippingCompany)) {
            $json['shippingCompany']  = $this->shippingCompany;
        }
        if (isset($this->shippingAddress1)) {
            $json['shippingAddress1'] = $this->shippingAddress1;
        }
        if (isset($this->shippingAddress2)) {
            $json['shippingAddress2'] = $this->shippingAddress2;
        }
        if (isset($this->shippingCity)) {
            $json['shippingCity']     = $this->shippingCity;
        }
        if (isset($this->shippingState)) {
            $json['shippingState']    = $this->shippingState;
        }
        if (isset($this->shippingZip)) {
            $json['shippingZip']      = $this->shippingZip;
        }
        if (isset($this->shippingCountry)) {
            $json['shippingCountry']  = CountryEnum::checkValue($this->shippingCountry);
        }
        if (isset($this->shippingPhone)) {
            $json['shippingPhone']    = $this->shippingPhone;
        }
        if (isset($this->shippingFax)) {
            $json['shippingFax']      = $this->shippingFax;
        }
        if (isset($this->custom)) {
            $json['custom']           = $this->custom;
        }
        if (isset($this->address1)) {
            $json['address1']         = $this->address1;
        }
        if (isset($this->address2)) {
            $json['address2']         = $this->address2;
        }
        if (isset($this->city)) {
            $json['city']             = $this->city;
        }
        if (isset($this->state)) {
            $json['state']            = $this->state;
        }
        if (isset($this->zip)) {
            $json['zip']              = $this->zip;
        }
        if (isset($this->country)) {
            $json['country']          = CountryEnum::checkValue($this->country);
        }
        if (isset($this->phone)) {
            $json['phone']            = $this->phone;
        }
        if (isset($this->fax)) {
            $json['fax']              = $this->fax;
        }
        if (isset($this->frozen)) {
            $json['frozen']           = FrozenEnum::checkValue($this->frozen);
        }
        if (isset($this->inactive)) {
            $json['inactive']         = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->invoices)) {
            $json['invoices']         = $this->invoices;
        }
        if (isset($this->tokens)) {
            $json['tokens']           = $this->tokens;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
