<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class EntityCustomFieldsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|EntitiesResponse|null
     */
    private $entity;

    /**
     * @var string|null
     */
    private $key;

    /**
     * @var string|null
     */
    private $value;

    /**
     * @var string|null
     */
    private $deleted;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Entity.
     * Entity for which we are creating custom field.
     *
     * @return string|EntitiesResponse|null
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Sets Entity.
     * Entity for which we are creating custom field.
     *
     * @maps entity
     * @mapsBy anyOf(anyOf(string,EntitiesResponse),null)
     *
     * @param string|EntitiesResponse|null $entity
     */
    public function setEntity($entity): void
    {
        $this->entity = $entity;
    }

    /**
     * Returns Key.
     * Name of custom field.
     */
    public function getKey(): ?string
    {
        return $this->key;
    }

    /**
     * Sets Key.
     * Name of custom field.
     *
     * @maps key
     */
    public function setKey(?string $key): void
    {
        $this->key = $key;
    }

    /**
     * Returns Value.
     * Value of custom field.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * Value of custom field.
     *
     * @maps value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Returns Deleted.
     * Time when custom field is deleted. The format should be YYYY-MM-DD HH:MM:SS.
     */
    public function getDeleted(): ?string
    {
        return $this->deleted;
    }

    /**
     * Sets Deleted.
     * Time when custom field is deleted. The format should be YYYY-MM-DD HH:MM:SS.
     *
     * @maps deleted
     */
    public function setDeleted(?string $deleted): void
    {
        $this->deleted = $deleted;
    }

    /**
     * Converts the EntityCustomFieldsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EntityCustomFieldsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EntityCustomFieldsResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'entity' => $this->entity,
                'key' => $this->key,
                'value' => $this->value,
                'deleted' => $this->deleted
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']       = $this->id;
        }
        if (isset($this->created)) {
            $json['created']  = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified'] = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']  =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier'] = $this->modifier;
        }
        if (isset($this->entity)) {
            $json['entity']   =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->entity,
                    'anyOf(anyOf(string,EntitiesResponse),null)'
                );
        }
        if (isset($this->key)) {
            $json['key']      = $this->key;
        }
        if (isset($this->value)) {
            $json['value']    = $this->value;
        }
        if (isset($this->deleted)) {
            $json['deleted']  = $this->deleted;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
