<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class EntitiesResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|null
     */
    private $ipCreated;

    /**
     * @var string|null
     */
    private $ipModified;

    /**
     * @var string|null
     */
    private $clientIp;

    /**
     * @var string|LoginsResponse|null
     */
    private $login;

    /**
     * @var string|null
     */
    private $parameter;

    /**
     * @var int|null
     */
    private $totalCreditDisbursements;

    /**
     * @var int|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var string|null
     */
    private $address1;

    /**
     * @var string|null
     */
    private $address2;

    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string|null
     */
    private $website;

    /**
     * @var string|null
     */
    private $zip;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $timezone;

    /**
     * @var string|null
     */
    private $phone;

    /**
     * @var string|null
     */
    private $customerPhone;

    /**
     * @var string|null
     */
    private $fax;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $ein;

    /**
     * @var string|null
     */
    private $einType;

    /**
     * @var string|null
     */
    private $globalBusinessId;

    /**
     * @var string|null
     */
    private $globalBusinessType;

    /**
     * @var string|null
     */
    private $irsFilingName;

    /**
     * @var int|null
     */
    private $locations;

    /**
     * @var string|null
     */
    private $tcVersion;

    /**
     * @var string|null
     */
    private $tcDate;

    /**
     * @var string|null
     */
    private $tcIp;

    /**
     * @var string|null
     */
    private $tcAcceptDate;

    /**
     * @var string|null
     */
    private $tcAcceptIp;

    /**
     * @var string|null
     */
    private $custom;

    /**
     * @var int|null
     */
    private $tinStatus;

    /**
     * @var int|null
     */
    private $public = EntitiesPublicEnum::PRIVATEENTITY;

    /**
     * @var int|null
     */
    private $reserved;

    /**
     * @var string|null
     */
    private $pendingRiskCheck;

    /**
     * @var string|null
     */
    private $checkStage;

    /**
     * @var string|null
     */
    private $industry;

    /**
     * @var string|null
     */
    private $payoutSecondaryDescriptor;

    /**
     * @var array
     */
    private $currency = ['value' => CurrencyEnum::USD];

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * @var AccountsResponse[]|null
     */
    private $accounts;

    /**
     * @var AdjustmentsResponse[]|null
     */
    private $adjustments;

    /**
     * @var AdjustmentsResponse[]|null
     */
    private $adjustmentsFromentity;

    /**
     * @var AdjustmentsResponse[]|null
     */
    private $adjustmentsOnentity;

    /**
     * @var AggregationsResponse[]|null
     */
    private $aggregations;

    /**
     * @var AppleDomainsResponse[]|null
     */
    private $ownedAppleDomains;

    /**
     * @var AssessmentsResponse[]|null
     */
    private $assessmentsOnentity;

    /**
     * @var BillingModifiersResponse[]|null
     */
    private $billingModifiers;

    /**
     * @var BillingsResponse[]|null
     */
    private $billings;

    /**
     * @var BillingsResponse[]|null
     */
    private $billingsForentity;

    /**
     * @var ChangeRequest[]|null
     */
    private $changeRequests;

    /**
     * @var ContactsResponse[]|null
     */
    private $contacts;

    /**
     * @var CredentialsResponse[]|null
     */
    private $credentials;

    /**
     * @var DisbursementsResponse[]|null
     */
    private $disbursements;

    /**
     * @var DecisionsResponse[]|null
     */
    private $decisions;

    /**
     * @var EmbeddedFinanceResponse[]|null
     */
    private $embeddedFinance;

    /**
     * @var EntityCustomFieldsResponse[]|null
     */
    private $entityCustomFields;

    /**
     * @var EntityDataResponse[]|null
     */
    private $entityData;

    /**
     * @var EntityDebtsResponse[]|null
     */
    private $entityDebts;

    /**
     * @var EntityDebtsResponse[]|null
     */
    private $entityDebtsToentity;

    /**
     * @var EntityRefsResponse[]|null
     */
    private $entityRefs;

    /**
     * @var EntityReturnsResponse[]|null
     */
    private $entityReturns;

    /**
     * @var EntityTermsResponse[]|null
     */
    private $entityTerms;

    /**
     * @var EntriesResponse[]|null
     */
    private $entriesOnentity;

    /**
     * @var FeesResponse[]|null
     */
    private $fees;

    /**
     * @var FeesResponse[]|null
     */
    private $forentityFees;

    /**
     * @var ProfitSharesResponse[]|null
     */
    private $forentityProfitShares;

    /**
     * @var FundsResponse[]|null
     */
    private $funds;

    /**
     * @var HoldsResponse[]|null
     */
    private $holds;

    /**
     * @var InvoiceParametersResponse[]|null
     */
    private $invoiceParameters;

    /**
     * @var NotesResponse[]|null
     */
    private $notes;

    /**
     * @var OrgEntitiesResponse[]|null
     */
    private $orgEntities;

    /**
     * @var OmniTokensResponse[]|null
     */
    private $omniTokens;

    /**
     * @var PaymentUpdateGroupsResponse[]|null
     */
    private $paymentUpdateGroups;

    /**
     * @var PayoutFlowsResponse[]|null
     */
    private $payoutFlows;

    /**
     * @var PayoutsResponse[]|null
     */
    private $payouts;

    /**
     * @var PendingEntriesResponse[]|null
     */
    private $pendingEntriesOnentity;

    /**
     * @var PinlessDebitConversionsResponse[]|null
     */
    private $pinlessDebitConversions;

    /**
     * @var ProfitSharesResponse[]|null
     */
    private $profitShares;

    /**
     * @var ReserveEntriesResponse[]|null
     */
    private $reserveEntriesOnentity;

    /**
     * @var ReservesResponse[]|null
     */
    private $reserves;

    /**
     * @var RevenueBoostsResponse[]|null
     */
    private $revenueBoosts;

    /**
     * @var RevShareSchedulesResponse[]|null
     */
    private $revShareSchedulesEntity;

    /**
     * @var RevShareSchedulesResponse[]|null
     */
    private $revShareSchedulesForentity;

    /**
     * @var RevShareStatmentsResponse[]|null
     */
    private $revShareStatementsEntity;

    /**
     * @var RevShareStatmentsResponse[]|null
     */
    private $revShareStatementsForentity;

    /**
     * @var SecretsResponse[]|null
     */
    private $secrets;

    /**
     * @var StatementEntriesResponse[]|null
     */
    private $statementEntries;

    /**
     * @var StatementEntriesResponse[]|null
     */
    private $statementEntriesOnentity;

    /**
     * @var StatementEntriesResponse[]|null
     */
    private $statementEntriesForentity;

    /**
     * @var SubscriptionsResponse[]|null
     */
    private $subscriptions;

    /**
     * @var StatementsResponse[]|null
     */
    private $statementsEntity;

    /**
     * @var StatementsResponse[]|null
     */
    private $statementsForentity;

    /**
     * @var SaferPaymentsResponse[]|null
     */
    private $saferPayments;

    /**
     * @var VendorsResponse[]|null
     */
    private $vendor;

    /**
     * @var MerchantsResponse|null
     */
    private $merchant;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Ip Created.
     * The incoming IP address from which this Entity was created.
     */
    public function getIpCreated(): ?string
    {
        return $this->ipCreated;
    }

    /**
     * Sets Ip Created.
     * The incoming IP address from which this Entity was created.
     *
     * @maps ipCreated
     */
    public function setIpCreated(?string $ipCreated): void
    {
        $this->ipCreated = $ipCreated;
    }

    /**
     * Returns Ip Modified.
     * The incoming IP address from which this Entity was last modified.
     */
    public function getIpModified(): ?string
    {
        return $this->ipModified;
    }

    /**
     * Sets Ip Modified.
     * The incoming IP address from which this Entity was last modified.
     *
     * @maps ipModified
     */
    public function setIpModified(?string $ipModified): void
    {
        $this->ipModified = $ipModified;
    }

    /**
     * Returns Client Ip.
     * The client IP address from which the Entity was created.
     * Valid values are any IPv4 or IPv6 address.
     */
    public function getClientIp(): ?string
    {
        return $this->clientIp;
    }

    /**
     * Sets Client Ip.
     * The client IP address from which the Entity was created.
     * Valid values are any IPv4 or IPv6 address.
     *
     * @maps clientIp
     */
    public function setClientIp(?string $clientIp): void
    {
        $this->clientIp = $clientIp;
    }

    /**
     * Returns Login.
     * The ID of the Login that owns this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The ID of the Login that owns this resource.
     *
     * @maps login
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Parameter.
     * The parameter associated with this Entity.
     */
    public function getParameter(): ?string
    {
        return $this->parameter;
    }

    /**
     * Sets Parameter.
     * The parameter associated with this Entity.
     *
     * @maps parameter
     */
    public function setParameter(?string $parameter): void
    {
        $this->parameter = $parameter;
    }

    /**
     * Returns Total Credit Disbursements.
     * The sum of all negative disbursements, in cents, associated to this Entity.
     */
    public function getTotalCreditDisbursements(): ?int
    {
        return $this->totalCreditDisbursements;
    }

    /**
     * Sets Total Credit Disbursements.
     * The sum of all negative disbursements, in cents, associated to this Entity.
     *
     * @maps totalCreditDisbursements
     */
    public function setTotalCreditDisbursements(?int $totalCreditDisbursements): void
    {
        $this->totalCreditDisbursements = $totalCreditDisbursements;
    }

    /**
     * Returns Type.
     * The type of Entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Sole Proprietorship**
     * - `1` - **Corporation**
     * - `2` - **Limited Liability Company**
     * - `3` - **Partnership**
     * - `4` - **Association**
     * - `5` - **Non-Profit Organization**
     * - `6` - **Government Organization**
     * - `7` - **C Corporation**
     * - `8` - **S Corporation**
     *
     * </details>
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of Entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Sole Proprietorship**
     * - `1` - **Corporation**
     * - `2` - **Limited Liability Company**
     * - `3` - **Partnership**
     * - `4` - **Association**
     * - `5` - **Non-Profit Organization**
     * - `6` - **Government Organization**
     * - `7` - **C Corporation**
     * - `8` - **S Corporation**
     *
     * </details>
     *
     * @maps type
     * @factory \PayrixLib\Models\EntityTypeEnum::checkValue
     */
    public function setType(?int $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Name.
     * The name of this Entity.
     * This field is stored as a text string and must be between 1 and 100 characters long.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of this Entity.
     * This field is stored as a text string and must be between 1 and 100 characters long.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Display Name.
     * The display name of this Entity.
     * This field is stored as a text string and must be between 1 and 1,000 characters long.
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     * The display name of this Entity.
     * This field is stored as a text string and must be between 1 and 1,000 characters long.
     *
     * @maps displayName
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Address 1.
     * The first line of the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    /**
     * Sets Address 1.
     * The first line of the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps address1
     */
    public function setAddress1(?string $address1): void
    {
        $this->address1 = $address1;
    }

    /**
     * Returns Address 2.
     * The second line of the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    /**
     * Sets Address 2.
     * The second line of the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps address2
     */
    public function setAddress2(?string $address2): void
    {
        $this->address2 = $address2;
    }

    /**
     * Returns City.
     * The name of the city in the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * The name of the city in the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 500 characters long.
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns State.
     * The U.S. state or Canadian province relevant to the address provided here. If the location is within
     * the U.S. and Canada, specify the 2-character postal abbreviation for the state. If the location is
     * outside of the U.S. and Canada, provide the full state name. This field is stored as a text string
     * and must be between 2 and 100 characters long.
     *
     *
     * <details>
     * <summary>U.S. States</summary>
     *
     * - `AK` - **Alaska (US)**
     *
     * - `AR` - **Arkansas (US)**
     *
     * - `AL` - **Alabama (US)**
     *
     * - `AZ` - **Arizona (US)**
     *
     * - `CA` - **California (US)**
     *
     * - `CO` - **Colorado (US)**
     *
     * - `CT` - **Connecticut (US)**
     *
     * - `DE` - **Delaware (US)**
     *
     * - `FL` - **Florida (US)**
     *
     * - `GA` - **Georgia (US)**
     *
     * - `HI` - **Hawaii (US)**
     *
     * - `IA` - **Iowa (US)**
     *
     * - `ID` - **Idaho (US)**
     *
     * - `IL` - **Illinois (US)**
     *
     * - `IN` - **Indiana (US)**
     *
     * - `KY` - **Kentucky (US)**
     *
     * - `KS` - **Kansas (US)**
     *
     * - `LA` - **Louisiana (US)**
     *
     * - `MA` - **Massachusetts (US)**
     *
     * - `MD` - **Maryland (US)**
     *
     * - `ME` - **Maine (US)**
     *
     * - `MI` - **Michigan (US)**
     *
     * - `MN` - **Minnesota (US)**
     *
     * - `MO` - **Missouri (US)**
     *
     * - `MS` - **Mississippi (US)**
     *
     * - `MT` - **Montana (US)**
     *
     * - `NC` - **North Carolina (US)**
     *
     * - `ND` - **North Dakota (US)**
     *
     * - `NE` - **Nebraska (US)**
     *
     * - `NH` - **New Hampshire (US)**
     *
     * - `NJ` - **New Jersey (US)**
     *
     * - `NM` - **New Mexico (US)**
     *
     * - `NV` - **Nevada (US)**
     *
     * - `NY` - **New York (US)**
     *
     * - `OH` - **Ohio (US)**
     *
     * - `OK`- **Oklahoma (US)**
     *
     * - `OR` - **Oregon (US)**
     *
     * - `PA` - **Pennsylvania (US)**
     *
     * - `RI` - **Rhode Island (US)**
     *
     * - `SC`- **South Carolina (US)**
     *
     * - `SD` - **South Dakota (US)**
     *
     * - `TN` - **Tennessee (US)**
     *
     * - `TX` - **Texas (US)**
     *
     * - `UT` - **Utah (US)**
     *
     * - `VA` - **Virginia (US)**
     *
     * - `VT` - **Vermont (US)**
     *
     * - `WA` - **Washington (US)**
     *
     * - `WI` - **Wisconsin (US)**
     *
     * - `WV` - **West Virginia (US)**
     *
     * - `WY` - **Wyoming (US)**
     * </details>
     *
     *
     *
     * <details>
     * <summary>Canada Provinces and Territories</summary>
     *
     * - `AB` - **Alberta (CAN)**
     *
     * - `BC` - **British Columbia (CAN)**
     *
     * - `MB` - **Manitoba (CAN)**
     *
     * - `ON` - **Ontario (CAN)**
     *
     * - `NS` - **Nova Scotia (CAN)**
     *
     * - `NB` - **New Brunswick (CAN)**
     *
     * - `NL` - **Newfoundland and Labrador (CAN)**
     *
     * - `NT` - **Northwest Territories (CAN)**
     *
     * - `NU` - **Nunavut (CAN)**
     *
     * - `PE` - **Prince Edward Island (CAN)**
     *
     * - `QC` - **Quebec (CAN)**
     *
     * - `SK` - **Saskatchewan (CAN)**
     *
     * - `YT` - **Yukon (CAN)**
     * </details>
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * The U.S. state or Canadian province relevant to the address provided here. If the location is within
     * the U.S. and Canada, specify the 2-character postal abbreviation for the state. If the location is
     * outside of the U.S. and Canada, provide the full state name. This field is stored as a text string
     * and must be between 2 and 100 characters long.
     *
     *
     * <details>
     * <summary>U.S. States</summary>
     *
     * - `AK` - **Alaska (US)**
     *
     * - `AR` - **Arkansas (US)**
     *
     * - `AL` - **Alabama (US)**
     *
     * - `AZ` - **Arizona (US)**
     *
     * - `CA` - **California (US)**
     *
     * - `CO` - **Colorado (US)**
     *
     * - `CT` - **Connecticut (US)**
     *
     * - `DE` - **Delaware (US)**
     *
     * - `FL` - **Florida (US)**
     *
     * - `GA` - **Georgia (US)**
     *
     * - `HI` - **Hawaii (US)**
     *
     * - `IA` - **Iowa (US)**
     *
     * - `ID` - **Idaho (US)**
     *
     * - `IL` - **Illinois (US)**
     *
     * - `IN` - **Indiana (US)**
     *
     * - `KY` - **Kentucky (US)**
     *
     * - `KS` - **Kansas (US)**
     *
     * - `LA` - **Louisiana (US)**
     *
     * - `MA` - **Massachusetts (US)**
     *
     * - `MD` - **Maryland (US)**
     *
     * - `ME` - **Maine (US)**
     *
     * - `MI` - **Michigan (US)**
     *
     * - `MN` - **Minnesota (US)**
     *
     * - `MO` - **Missouri (US)**
     *
     * - `MS` - **Mississippi (US)**
     *
     * - `MT` - **Montana (US)**
     *
     * - `NC` - **North Carolina (US)**
     *
     * - `ND` - **North Dakota (US)**
     *
     * - `NE` - **Nebraska (US)**
     *
     * - `NH` - **New Hampshire (US)**
     *
     * - `NJ` - **New Jersey (US)**
     *
     * - `NM` - **New Mexico (US)**
     *
     * - `NV` - **Nevada (US)**
     *
     * - `NY` - **New York (US)**
     *
     * - `OH` - **Ohio (US)**
     *
     * - `OK`- **Oklahoma (US)**
     *
     * - `OR` - **Oregon (US)**
     *
     * - `PA` - **Pennsylvania (US)**
     *
     * - `RI` - **Rhode Island (US)**
     *
     * - `SC`- **South Carolina (US)**
     *
     * - `SD` - **South Dakota (US)**
     *
     * - `TN` - **Tennessee (US)**
     *
     * - `TX` - **Texas (US)**
     *
     * - `UT` - **Utah (US)**
     *
     * - `VA` - **Virginia (US)**
     *
     * - `VT` - **Vermont (US)**
     *
     * - `WA` - **Washington (US)**
     *
     * - `WI` - **Wisconsin (US)**
     *
     * - `WV` - **West Virginia (US)**
     *
     * - `WY` - **Wyoming (US)**
     * </details>
     *
     *
     *
     * <details>
     * <summary>Canada Provinces and Territories</summary>
     *
     * - `AB` - **Alberta (CAN)**
     *
     * - `BC` - **British Columbia (CAN)**
     *
     * - `MB` - **Manitoba (CAN)**
     *
     * - `ON` - **Ontario (CAN)**
     *
     * - `NS` - **Nova Scotia (CAN)**
     *
     * - `NB` - **New Brunswick (CAN)**
     *
     * - `NL` - **Newfoundland and Labrador (CAN)**
     *
     * - `NT` - **Northwest Territories (CAN)**
     *
     * - `NU` - **Nunavut (CAN)**
     *
     * - `PE` - **Prince Edward Island (CAN)**
     *
     * - `QC` - **Quebec (CAN)**
     *
     * - `SK` - **Saskatchewan (CAN)**
     *
     * - `YT` - **Yukon (CAN)**
     * </details>
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Website.
     * The website URL associated with this Entity.
     * This field is stored as a text string and must be between 0 and 500 characters long.
     */
    public function getWebsite(): ?string
    {
        return $this->website;
    }

    /**
     * Sets Website.
     * The website URL associated with this Entity.
     * This field is stored as a text string and must be between 0 and 500 characters long.
     *
     * @maps website
     */
    public function setWebsite(?string $website): void
    {
        $this->website = $website;
    }

    /**
     * Returns Zip.
     * The ZIP code in the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 20 characters long.
     */
    public function getZip(): ?string
    {
        return $this->zip;
    }

    /**
     * Sets Zip.
     * The ZIP code in the address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 20 characters long.
     *
     * @maps zip
     */
    public function setZip(?string $zip): void
    {
        $this->zip = $zip;
    }

    /**
     * Returns Country.
     * The country in the address associated with the Entity, currently accepting values including `USA`
     * and `CAN`.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * The country in the address associated with the Entity, currently accepting values including `USA`
     * and `CAN`.
     *
     * @maps country
     * @factory \PayrixLib\Models\EntityCountryEnum::checkValue
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Timezone.
     * The time zone for the address associated with the terminal's location.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `est` - **Eastern Standard Time**
     *
     * - `pst` - **Pacific Standard Time**
     *
     * - `cst` - **Central Standard Time**
     *
     * - `mst` - **Mountain Daylight Time**
     *
     * - `akst` - **Alaska Standard Time**
     *
     * - `hst` - **Hawaii Standard Time**
     *
     * - `sst` - **Samoa Standard Time**
     *
     * - `chst` - **Chamorro Standard Time**
     *
     * - `ast`  - **Atlantic Standard Time**
     *
     * - `pwt` - **Palau Time**
     *
     * - `mht` - **Marshall Islands Time**
     *
     * - `chut` - **Chuuk Time**
     *
     * - `nst` - **Newfoundland Standard Time**
     *
     * </details>
     */
    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    /**
     * Sets Timezone.
     * The time zone for the address associated with the terminal's location.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `est` - **Eastern Standard Time**
     *
     * - `pst` - **Pacific Standard Time**
     *
     * - `cst` - **Central Standard Time**
     *
     * - `mst` - **Mountain Daylight Time**
     *
     * - `akst` - **Alaska Standard Time**
     *
     * - `hst` - **Hawaii Standard Time**
     *
     * - `sst` - **Samoa Standard Time**
     *
     * - `chst` - **Chamorro Standard Time**
     *
     * - `ast`  - **Atlantic Standard Time**
     *
     * - `pwt` - **Palau Time**
     *
     * - `mht` - **Marshall Islands Time**
     *
     * - `chut` - **Chuuk Time**
     *
     * - `nst` - **Newfoundland Standard Time**
     *
     * </details>
     *
     * @maps timezone
     * @factory \PayrixLib\Models\EntitiesTimezoneEnum::checkValue
     */
    public function setTimezone(?string $timezone): void
    {
        $this->timezone = $timezone;
    }

    /**
     * Returns Phone.
     * The phone number associated with this Entity.
     * This field is stored as a text string and must be between 5 and 15 characters long.
     */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * Sets Phone.
     * The phone number associated with this Entity.
     * This field is stored as a text string and must be between 5 and 15 characters long.
     *
     * @maps phone
     */
    public function setPhone(?string $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * Returns Customer Phone.
     * The customer service phone number associated with this Entity. For Merchants, this number will be
     * displayed on the customer's credit card statement.
     * This field is stored as a text string and must be between 5 and 15 characters long.
     */
    public function getCustomerPhone(): ?string
    {
        return $this->customerPhone;
    }

    /**
     * Sets Customer Phone.
     * The customer service phone number associated with this Entity. For Merchants, this number will be
     * displayed on the customer's credit card statement.
     * This field is stored as a text string and must be between 5 and 15 characters long.
     *
     * @maps customerPhone
     */
    public function setCustomerPhone(?string $customerPhone): void
    {
        $this->customerPhone = $customerPhone;
    }

    /**
     * Returns Fax.
     * The fax number associated with this Entity.
     * This field is stored as a text string and must be between 5 and 15 characters long.
     */
    public function getFax(): ?string
    {
        return $this->fax;
    }

    /**
     * Sets Fax.
     * The fax number associated with this Entity.
     * This field is stored as a text string and must be between 5 and 15 characters long.
     *
     * @maps fax
     */
    public function setFax(?string $fax): void
    {
        $this->fax = $fax;
    }

    /**
     * Returns Email.
     * The email address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 100 characters long.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * The email address associated with this Entity.
     * This field is stored as a text string and must be between 1 and 100 characters long.
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Ein.
     * The IRS Employer Identification Number (EIN) for the Entity.
     * This field is stored as an integer and must be 9 characters long.
     */
    public function getEin(): ?string
    {
        return $this->ein;
    }

    /**
     * Sets Ein.
     * The IRS Employer Identification Number (EIN) for the Entity.
     * This field is stored as an integer and must be 9 characters long.
     *
     * @maps ein
     */
    public function setEin(?string $ein): void
    {
        $this->ein = $ein;
    }

    /**
     * Returns Ein Type.
     * Indicates if the TIN being used is an EIN, SSN, or other/unknown number.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `ssn` - **Social Security Number.**
     * - `tin` - **Employer Identification Number.**
     * - `other` - **Other/Unknown TIN.**
     *
     * </details>
     */
    public function getEinType(): ?string
    {
        return $this->einType;
    }

    /**
     * Sets Ein Type.
     * Indicates if the TIN being used is an EIN, SSN, or other/unknown number.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `ssn` - **Social Security Number.**
     * - `tin` - **Employer Identification Number.**
     * - `other` - **Other/Unknown TIN.**
     *
     * </details>
     *
     * @maps einType
     * @factory \PayrixLib\Models\EntitiesEinTypeEnum::checkValue
     */
    public function setEinType(?string $einType): void
    {
        $this->einType = $einType;
    }

    /**
     * Returns Global Business Id.
     * The business registration number for the entity.
     * This field is stored as an alphanumeric and must be between 9 to 10 characters long.
     */
    public function getGlobalBusinessId(): ?string
    {
        return $this->globalBusinessId;
    }

    /**
     * Sets Global Business Id.
     * The business registration number for the entity.
     * This field is stored as an alphanumeric and must be between 9 to 10 characters long.
     *
     * @maps globalBusinessId
     */
    public function setGlobalBusinessId(?string $globalBusinessId): void
    {
        $this->globalBusinessId = $globalBusinessId;
    }

    /**
     * Returns Global Business Type.
     * The business registration type for the entity
     *
     * <details>
     * <summary>Valid Values for country USA</summary>
     *
     * - `ssn` - **Social Security Number.**
     * - `tin` - **Employer Identification Number.**
     * - `other` - **Other/Unknown TIN.**
     * </details>
     * <details>
     * <summary>Valid Values for country Canada</summary>
     *
     * - `CD` - **Federal**
     * - `AB` - **Alberta**
     * - `BC` - **British Columbia**
     * - `MB` - **Manitoba**
     * - `NB` - **New Brunswick**
     * - `NL` - **Newfoundland and Labrador**
     * - `NT` - **Northwest Territories**
     * - `NS` - **Nova Scotia**
     * - `NU` - **Nunavut**
     * - `ON` - **Ontario**
     * - `PE` - **Prince Edward Island**
     * - `QC` - **Quebec**
     * - `SK` - **Saskatchewan**
     * - `YT` - **Yukon**
     *
     * </details>
     */
    public function getGlobalBusinessType(): ?string
    {
        return $this->globalBusinessType;
    }

    /**
     * Sets Global Business Type.
     * The business registration type for the entity
     *
     * <details>
     * <summary>Valid Values for country USA</summary>
     *
     * - `ssn` - **Social Security Number.**
     * - `tin` - **Employer Identification Number.**
     * - `other` - **Other/Unknown TIN.**
     * </details>
     * <details>
     * <summary>Valid Values for country Canada</summary>
     *
     * - `CD` - **Federal**
     * - `AB` - **Alberta**
     * - `BC` - **British Columbia**
     * - `MB` - **Manitoba**
     * - `NB` - **New Brunswick**
     * - `NL` - **Newfoundland and Labrador**
     * - `NT` - **Northwest Territories**
     * - `NS` - **Nova Scotia**
     * - `NU` - **Nunavut**
     * - `ON` - **Ontario**
     * - `PE` - **Prince Edward Island**
     * - `QC` - **Quebec**
     * - `SK` - **Saskatchewan**
     * - `YT` - **Yukon**
     *
     * </details>
     *
     * @maps globalBusinessType
     * @factory \PayrixLib\Models\GlobalBusinessTypeEnum::checkValue
     */
    public function setGlobalBusinessType(?string $globalBusinessType): void
    {
        $this->globalBusinessType = $globalBusinessType;
    }

    /**
     * Returns Irs Filing Name.
     * The IRS Legal Filing Name. This must match what has been provided to the IRS when filing taxes.
     */
    public function getIrsFilingName(): ?string
    {
        return $this->irsFilingName;
    }

    /**
     * Sets Irs Filing Name.
     * The IRS Legal Filing Name. This must match what has been provided to the IRS when filing taxes.
     *
     * @maps irsFilingName
     */
    public function setIrsFilingName(?string $irsFilingName): void
    {
        $this->irsFilingName = $irsFilingName;
    }

    /**
     * Returns Locations.
     * The number of locations at which this Entity does business.
     * This field is stored as an integer and must be between 1 and 1,000,000 characters long.
     */
    public function getLocations(): ?int
    {
        return $this->locations;
    }

    /**
     * Sets Locations.
     * The number of locations at which this Entity does business.
     * This field is stored as an integer and must be between 1 and 1,000,000 characters long.
     *
     * @maps locations
     */
    public function setLocations(?int $locations): void
    {
        $this->locations = $locations;
    }

    /**
     * Returns Tc Version.
     * An indicator showing the version of the terms and conditions that this Entity has accepted. The API
     * indicates the version as a string.
     * This field is stored as a text string and must be between 0 and 20 characters long.
     */
    public function getTcVersion(): ?string
    {
        return $this->tcVersion;
    }

    /**
     * Sets Tc Version.
     * An indicator showing the version of the terms and conditions that this Entity has accepted. The API
     * indicates the version as a string.
     * This field is stored as a text string and must be between 0 and 20 characters long.
     *
     * @maps tcVersion
     */
    public function setTcVersion(?string $tcVersion): void
    {
        $this->tcVersion = $tcVersion;
    }

    /**
     * Returns Tc Date.
     * Date the `tcVersion` was last updated. The format should be YYYY-MM-DD HH:MM:SS.
     */
    public function getTcDate(): ?string
    {
        return $this->tcDate;
    }

    /**
     * Sets Tc Date.
     * Date the `tcVersion` was last updated. The format should be YYYY-MM-DD HH:MM:SS.
     *
     * @maps tcDate
     */
    public function setTcDate(?string $tcDate): void
    {
        $this->tcDate = $tcDate;
    }

    /**
     * Returns Tc Ip.
     * IP address of client from last `tcVersion` update.
     */
    public function getTcIp(): ?string
    {
        return $this->tcIp;
    }

    /**
     * Sets Tc Ip.
     * IP address of client from last `tcVersion` update.
     *
     * @maps tcIp
     */
    public function setTcIp(?string $tcIp): void
    {
        $this->tcIp = $tcIp;
    }

    /**
     * Returns Tc Accept Date.
     * Date and time on which this Entity accepted the Terms and Conditions, if different than tcDate.
     * The date is specified as a 12-digit string in YYYYMMDDHHII format, for example, `201601201528` for
     * January 20, 2016, at 15:28 (3:28 PM).
     */
    public function getTcAcceptDate(): ?string
    {
        return $this->tcAcceptDate;
    }

    /**
     * Sets Tc Accept Date.
     * Date and time on which this Entity accepted the Terms and Conditions, if different than tcDate.
     * The date is specified as a 12-digit string in YYYYMMDDHHII format, for example, `201601201528` for
     * January 20, 2016, at 15:28 (3:28 PM).
     *
     * @maps tcAcceptDate
     */
    public function setTcAcceptDate(?string $tcAcceptDate): void
    {
        $this->tcAcceptDate = $tcAcceptDate;
    }

    /**
     * Returns Tc Accept Ip.
     * IP address from which this Entity accepted the Terms and Conditions, if different than `tcIp`.
     */
    public function getTcAcceptIp(): ?string
    {
        return $this->tcAcceptIp;
    }

    /**
     * Sets Tc Accept Ip.
     * IP address from which this Entity accepted the Terms and Conditions, if different than `tcIp`.
     *
     * @maps tcAcceptIp
     */
    public function setTcAcceptIp(?string $tcAcceptIp): void
    {
        $this->tcAcceptIp = $tcAcceptIp;
    }

    /**
     * Returns Custom.
     * Custom, free-form field for client-supplied text; must be between 0 and 1,000 characters long.
     */
    public function getCustom(): ?string
    {
        return $this->custom;
    }

    /**
     * Sets Custom.
     * Custom, free-form field for client-supplied text; must be between 0 and 1,000 characters long.
     *
     * @maps custom
     */
    public function setCustom(?string $custom): void
    {
        $this->custom = $custom;
    }

    /**
     * Returns Tin Status.
     * The Tax Identification Number (TIN) status of the entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Pending**
     * - `1` - **Valid**
     * - `2` - **Invalid**
     * - `3` - **Not required**
     *
     * </details>
     */
    public function getTinStatus(): ?int
    {
        return $this->tinStatus;
    }

    /**
     * Sets Tin Status.
     * The Tax Identification Number (TIN) status of the entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Pending**
     * - `1` - **Valid**
     * - `2` - **Invalid**
     * - `3` - **Not required**
     *
     * </details>
     *
     * @maps tinStatus
     * @factory \PayrixLib\Models\EntitiesTinStatusEnum::checkValue
     */
    public function setTinStatus(?int $tinStatus): void
    {
        $this->tinStatus = $tinStatus;
    }

    /**
     * Returns Public.
     * Indicates whether this is a publicly held entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Private entity**
     * - `1` - **Public entity**
     *
     * </details>
     */
    public function getPublic(): ?int
    {
        return $this->public;
    }

    /**
     * Sets Public.
     * Indicates whether this is a publicly held entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Private entity**
     * - `1` - **Public entity**
     *
     * </details>
     *
     * @maps public
     * @factory \PayrixLib\Models\EntitiesPublicEnum::checkValue
     */
    public function setPublic(?int $public): void
    {
        $this->public = $public;
    }

    /**
     * Returns Reserved.
     * Indicates the reserve status of the entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **No reserve.**
     * - `1` - **Block transaction, will never be processed. The Entity is sent to the manual review queue..
     * **
     * - `3` - **Hold transaction, will not be captured.**
     * - `4` - **Reserve transaction, funds should be reserved.**
     * - `5` - **Block current activity, no change for merchant.**
     * - `6` - **Passed decision(s). Will not be set anywhere, will only be used for integration purposes.
     * **
     * - `7` - **We did not have policies to process.**
     * - `8` - **We onboard the merchant and wait for manual check later.**
     * - `9` - **Schedule the automatic release of the reserve.**
     * - `10` - **Hold transaction, will not be captured. Automatic release when the associated sale is
     * done.**
     *
     * </details>
     */
    public function getReserved(): ?int
    {
        return $this->reserved;
    }

    /**
     * Sets Reserved.
     * Indicates the reserve status of the entity.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **No reserve.**
     * - `1` - **Block transaction, will never be processed. The Entity is sent to the manual review queue..
     * **
     * - `3` - **Hold transaction, will not be captured.**
     * - `4` - **Reserve transaction, funds should be reserved.**
     * - `5` - **Block current activity, no change for merchant.**
     * - `6` - **Passed decision(s). Will not be set anywhere, will only be used for integration purposes.
     * **
     * - `7` - **We did not have policies to process.**
     * - `8` - **We onboard the merchant and wait for manual check later.**
     * - `9` - **Schedule the automatic release of the reserve.**
     * - `10` - **Hold transaction, will not be captured. Automatic release when the associated sale is
     * done.**
     *
     * </details>
     *
     * @maps reserved
     * @factory \PayrixLib\Models\EntitiesReservedEnum::checkValue
     */
    public function setReserved(?int $reserved): void
    {
        $this->reserved = $reserved;
    }

    /**
     * Returns Pending Risk Check.
     * Whether it is pending a risk check.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `pending` - **Pending**
     * - `successful` - **Successful**
     * - `failed` - **Failed**
     * - `manual` - **Manual**
     *
     * </details>
     */
    public function getPendingRiskCheck(): ?string
    {
        return $this->pendingRiskCheck;
    }

    /**
     * Sets Pending Risk Check.
     * Whether it is pending a risk check.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `pending` - **Pending**
     * - `successful` - **Successful**
     * - `failed` - **Failed**
     * - `manual` - **Manual**
     *
     * </details>
     *
     * @maps pendingRiskCheck
     * @factory \PayrixLib\Models\EntityPendingRiskCheckEnum::checkValue
     */
    public function setPendingRiskCheck(?string $pendingRiskCheck): void
    {
        $this->pendingRiskCheck = $pendingRiskCheck;
    }

    /**
     * Returns Check Stage.
     * The last stage completed for risk underwriting review.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `createEntity` - **Merchant created.** No Signup Form submitted.
     * - `underwriting` - **Risk/Underwriting Review.** Merchant Signup Form submitted.
     * - `preboard` - **Preboard.** Check the Merchant before they are boarded.
     * - `postboard` - **Check the Merchant after they are boarded.**
     * - `txn` - **Check the Merchant when they process a Transaction.**
     * - `txnVolume` - **Check the Merchant when their transaction volume hits a certain amount.**
     * - `payout` - **Check the Merchant when a Payout occurs.**
     * - `payoutVolume` - **Check the Merchant when the volume of Payouts to the Merchant hits a certain
     * amount.**
     *
     * </details>
     */
    public function getCheckStage(): ?string
    {
        return $this->checkStage;
    }

    /**
     * Sets Check Stage.
     * The last stage completed for risk underwriting review.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `createEntity` - **Merchant created.** No Signup Form submitted.
     * - `underwriting` - **Risk/Underwriting Review.** Merchant Signup Form submitted.
     * - `preboard` - **Preboard.** Check the Merchant before they are boarded.
     * - `postboard` - **Check the Merchant after they are boarded.**
     * - `txn` - **Check the Merchant when they process a Transaction.**
     * - `txnVolume` - **Check the Merchant when their transaction volume hits a certain amount.**
     * - `payout` - **Check the Merchant when a Payout occurs.**
     * - `payoutVolume` - **Check the Merchant when the volume of Payouts to the Merchant hits a certain
     * amount.**
     *
     * </details>
     *
     * @maps checkStage
     * @factory \PayrixLib\Models\EntityCheckStageEnum::checkValue
     */
    public function setCheckStage(?string $checkStage): void
    {
        $this->checkStage = $checkStage;
    }

    /**
     * Returns Industry.
     * This field is stored as a text string and must be between 0 and 1,000 characters long.
     */
    public function getIndustry(): ?string
    {
        return $this->industry;
    }

    /**
     * Sets Industry.
     * This field is stored as a text string and must be between 0 and 1,000 characters long.
     *
     * @maps industry
     */
    public function setIndustry(?string $industry): void
    {
        $this->industry = $industry;
    }

    /**
     * Returns Payout Secondary Descriptor.
     * The secondary billing descriptor to appear on the bank statements for funds transfer for the entity.
     */
    public function getPayoutSecondaryDescriptor(): ?string
    {
        return $this->payoutSecondaryDescriptor;
    }

    /**
     * Sets Payout Secondary Descriptor.
     * The secondary billing descriptor to appear on the bank statements for funds transfer for the entity.
     *
     * @maps payoutSecondaryDescriptor
     */
    public function setPayoutSecondaryDescriptor(?string $payoutSecondaryDescriptor): void
    {
        $this->payoutSecondaryDescriptor = $payoutSecondaryDescriptor;
    }

    /**
     * Returns Currency.
     * The currency of this Entity. See <a href="https://www.iban.com/currency-codes"
     * target="_blank">Currency codes</a>  for all valid values.
     */
    public function getCurrency(): ?string
    {
        if (count($this->currency) == 0) {
            return null;
        }
        return $this->currency['value'];
    }

    /**
     * Sets Currency.
     * The currency of this Entity. See <a href="https://www.iban.com/currency-codes"
     * target="_blank">Currency codes</a>  for all valid values.
     *
     * @maps currency
     * @factory \PayrixLib\Models\CurrencyEnum::checkValue
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency['value'] = $currency;
    }

    /**
     * Unsets Currency.
     * The currency of this Entity. See <a href="https://www.iban.com/currency-codes"
     * target="_blank">Currency codes</a>  for all valid values.
     */
    public function unsetCurrency(): void
    {
        $this->currency = [];
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Returns Accounts.
     *
     * @return AccountsResponse[]|null
     */
    public function getAccounts(): ?array
    {
        return $this->accounts;
    }

    /**
     * Sets Accounts.
     *
     * @maps accounts
     *
     * @param AccountsResponse[]|null $accounts
     */
    public function setAccounts(?array $accounts): void
    {
        $this->accounts = $accounts;
    }

    /**
     * Returns Adjustments.
     *
     * @return AdjustmentsResponse[]|null
     */
    public function getAdjustments(): ?array
    {
        return $this->adjustments;
    }

    /**
     * Sets Adjustments.
     *
     * @maps adjustments
     *
     * @param AdjustmentsResponse[]|null $adjustments
     */
    public function setAdjustments(?array $adjustments): void
    {
        $this->adjustments = $adjustments;
    }

    /**
     * Returns Adjustments Fromentity.
     *
     * @return AdjustmentsResponse[]|null
     */
    public function getAdjustmentsFromentity(): ?array
    {
        return $this->adjustmentsFromentity;
    }

    /**
     * Sets Adjustments Fromentity.
     *
     * @maps adjustmentsFromentity
     *
     * @param AdjustmentsResponse[]|null $adjustmentsFromentity
     */
    public function setAdjustmentsFromentity(?array $adjustmentsFromentity): void
    {
        $this->adjustmentsFromentity = $adjustmentsFromentity;
    }

    /**
     * Returns Adjustments Onentity.
     *
     * @return AdjustmentsResponse[]|null
     */
    public function getAdjustmentsOnentity(): ?array
    {
        return $this->adjustmentsOnentity;
    }

    /**
     * Sets Adjustments Onentity.
     *
     * @maps adjustmentsOnentity
     *
     * @param AdjustmentsResponse[]|null $adjustmentsOnentity
     */
    public function setAdjustmentsOnentity(?array $adjustmentsOnentity): void
    {
        $this->adjustmentsOnentity = $adjustmentsOnentity;
    }

    /**
     * Returns Aggregations.
     *
     * @return AggregationsResponse[]|null
     */
    public function getAggregations(): ?array
    {
        return $this->aggregations;
    }

    /**
     * Sets Aggregations.
     *
     * @maps aggregations
     *
     * @param AggregationsResponse[]|null $aggregations
     */
    public function setAggregations(?array $aggregations): void
    {
        $this->aggregations = $aggregations;
    }

    /**
     * Returns Owned Apple Domains.
     *
     * @return AppleDomainsResponse[]|null
     */
    public function getOwnedAppleDomains(): ?array
    {
        return $this->ownedAppleDomains;
    }

    /**
     * Sets Owned Apple Domains.
     *
     * @maps ownedAppleDomains
     *
     * @param AppleDomainsResponse[]|null $ownedAppleDomains
     */
    public function setOwnedAppleDomains(?array $ownedAppleDomains): void
    {
        $this->ownedAppleDomains = $ownedAppleDomains;
    }

    /**
     * Returns Assessments Onentity.
     *
     * @return AssessmentsResponse[]|null
     */
    public function getAssessmentsOnentity(): ?array
    {
        return $this->assessmentsOnentity;
    }

    /**
     * Sets Assessments Onentity.
     *
     * @maps assessmentsOnentity
     *
     * @param AssessmentsResponse[]|null $assessmentsOnentity
     */
    public function setAssessmentsOnentity(?array $assessmentsOnentity): void
    {
        $this->assessmentsOnentity = $assessmentsOnentity;
    }

    /**
     * Returns Billing Modifiers.
     *
     * @return BillingModifiersResponse[]|null
     */
    public function getBillingModifiers(): ?array
    {
        return $this->billingModifiers;
    }

    /**
     * Sets Billing Modifiers.
     *
     * @maps billingModifiers
     *
     * @param BillingModifiersResponse[]|null $billingModifiers
     */
    public function setBillingModifiers(?array $billingModifiers): void
    {
        $this->billingModifiers = $billingModifiers;
    }

    /**
     * Returns Billings.
     *
     * @return BillingsResponse[]|null
     */
    public function getBillings(): ?array
    {
        return $this->billings;
    }

    /**
     * Sets Billings.
     *
     * @maps billings
     *
     * @param BillingsResponse[]|null $billings
     */
    public function setBillings(?array $billings): void
    {
        $this->billings = $billings;
    }

    /**
     * Returns Billings Forentity.
     *
     * @return BillingsResponse[]|null
     */
    public function getBillingsForentity(): ?array
    {
        return $this->billingsForentity;
    }

    /**
     * Sets Billings Forentity.
     *
     * @maps billingsForentity
     *
     * @param BillingsResponse[]|null $billingsForentity
     */
    public function setBillingsForentity(?array $billingsForentity): void
    {
        $this->billingsForentity = $billingsForentity;
    }

    /**
     * Returns Change Requests.
     *
     * @return ChangeRequest[]|null
     */
    public function getChangeRequests(): ?array
    {
        return $this->changeRequests;
    }

    /**
     * Sets Change Requests.
     *
     * @maps changeRequests
     *
     * @param ChangeRequest[]|null $changeRequests
     */
    public function setChangeRequests(?array $changeRequests): void
    {
        $this->changeRequests = $changeRequests;
    }

    /**
     * Returns Contacts.
     *
     * @return ContactsResponse[]|null
     */
    public function getContacts(): ?array
    {
        return $this->contacts;
    }

    /**
     * Sets Contacts.
     *
     * @maps contacts
     *
     * @param ContactsResponse[]|null $contacts
     */
    public function setContacts(?array $contacts): void
    {
        $this->contacts = $contacts;
    }

    /**
     * Returns Credentials.
     *
     * @return CredentialsResponse[]|null
     */
    public function getCredentials(): ?array
    {
        return $this->credentials;
    }

    /**
     * Sets Credentials.
     *
     * @maps credentials
     *
     * @param CredentialsResponse[]|null $credentials
     */
    public function setCredentials(?array $credentials): void
    {
        $this->credentials = $credentials;
    }

    /**
     * Returns Disbursements.
     *
     * @return DisbursementsResponse[]|null
     */
    public function getDisbursements(): ?array
    {
        return $this->disbursements;
    }

    /**
     * Sets Disbursements.
     *
     * @maps disbursements
     *
     * @param DisbursementsResponse[]|null $disbursements
     */
    public function setDisbursements(?array $disbursements): void
    {
        $this->disbursements = $disbursements;
    }

    /**
     * Returns Decisions.
     *
     * @return DecisionsResponse[]|null
     */
    public function getDecisions(): ?array
    {
        return $this->decisions;
    }

    /**
     * Sets Decisions.
     *
     * @maps decisions
     *
     * @param DecisionsResponse[]|null $decisions
     */
    public function setDecisions(?array $decisions): void
    {
        $this->decisions = $decisions;
    }

    /**
     * Returns Embedded Finance.
     *
     * @return EmbeddedFinanceResponse[]|null
     */
    public function getEmbeddedFinance(): ?array
    {
        return $this->embeddedFinance;
    }

    /**
     * Sets Embedded Finance.
     *
     * @maps embeddedFinance
     *
     * @param EmbeddedFinanceResponse[]|null $embeddedFinance
     */
    public function setEmbeddedFinance(?array $embeddedFinance): void
    {
        $this->embeddedFinance = $embeddedFinance;
    }

    /**
     * Returns Entity Custom Fields.
     *
     * @return EntityCustomFieldsResponse[]|null
     */
    public function getEntityCustomFields(): ?array
    {
        return $this->entityCustomFields;
    }

    /**
     * Sets Entity Custom Fields.
     *
     * @maps entityCustomFields
     *
     * @param EntityCustomFieldsResponse[]|null $entityCustomFields
     */
    public function setEntityCustomFields(?array $entityCustomFields): void
    {
        $this->entityCustomFields = $entityCustomFields;
    }

    /**
     * Returns Entity Data.
     *
     * @return EntityDataResponse[]|null
     */
    public function getEntityData(): ?array
    {
        return $this->entityData;
    }

    /**
     * Sets Entity Data.
     *
     * @maps entityData
     *
     * @param EntityDataResponse[]|null $entityData
     */
    public function setEntityData(?array $entityData): void
    {
        $this->entityData = $entityData;
    }

    /**
     * Returns Entity Debts.
     *
     * @return EntityDebtsResponse[]|null
     */
    public function getEntityDebts(): ?array
    {
        return $this->entityDebts;
    }

    /**
     * Sets Entity Debts.
     *
     * @maps entityDebts
     *
     * @param EntityDebtsResponse[]|null $entityDebts
     */
    public function setEntityDebts(?array $entityDebts): void
    {
        $this->entityDebts = $entityDebts;
    }

    /**
     * Returns Entity Debts Toentity.
     *
     * @return EntityDebtsResponse[]|null
     */
    public function getEntityDebtsToentity(): ?array
    {
        return $this->entityDebtsToentity;
    }

    /**
     * Sets Entity Debts Toentity.
     *
     * @maps entityDebtsToentity
     *
     * @param EntityDebtsResponse[]|null $entityDebtsToentity
     */
    public function setEntityDebtsToentity(?array $entityDebtsToentity): void
    {
        $this->entityDebtsToentity = $entityDebtsToentity;
    }

    /**
     * Returns Entity Refs.
     *
     * @return EntityRefsResponse[]|null
     */
    public function getEntityRefs(): ?array
    {
        return $this->entityRefs;
    }

    /**
     * Sets Entity Refs.
     *
     * @maps entityRefs
     *
     * @param EntityRefsResponse[]|null $entityRefs
     */
    public function setEntityRefs(?array $entityRefs): void
    {
        $this->entityRefs = $entityRefs;
    }

    /**
     * Returns Entity Returns.
     *
     * @return EntityReturnsResponse[]|null
     */
    public function getEntityReturns(): ?array
    {
        return $this->entityReturns;
    }

    /**
     * Sets Entity Returns.
     *
     * @maps entityReturns
     *
     * @param EntityReturnsResponse[]|null $entityReturns
     */
    public function setEntityReturns(?array $entityReturns): void
    {
        $this->entityReturns = $entityReturns;
    }

    /**
     * Returns Entity Terms.
     *
     * @return EntityTermsResponse[]|null
     */
    public function getEntityTerms(): ?array
    {
        return $this->entityTerms;
    }

    /**
     * Sets Entity Terms.
     *
     * @maps entityTerms
     *
     * @param EntityTermsResponse[]|null $entityTerms
     */
    public function setEntityTerms(?array $entityTerms): void
    {
        $this->entityTerms = $entityTerms;
    }

    /**
     * Returns Entries Onentity.
     *
     * @return EntriesResponse[]|null
     */
    public function getEntriesOnentity(): ?array
    {
        return $this->entriesOnentity;
    }

    /**
     * Sets Entries Onentity.
     *
     * @maps entriesOnentity
     *
     * @param EntriesResponse[]|null $entriesOnentity
     */
    public function setEntriesOnentity(?array $entriesOnentity): void
    {
        $this->entriesOnentity = $entriesOnentity;
    }

    /**
     * Returns Fees.
     *
     * @return FeesResponse[]|null
     */
    public function getFees(): ?array
    {
        return $this->fees;
    }

    /**
     * Sets Fees.
     *
     * @maps fees
     *
     * @param FeesResponse[]|null $fees
     */
    public function setFees(?array $fees): void
    {
        $this->fees = $fees;
    }

    /**
     * Returns Forentity Fees.
     *
     * @return FeesResponse[]|null
     */
    public function getForentityFees(): ?array
    {
        return $this->forentityFees;
    }

    /**
     * Sets Forentity Fees.
     *
     * @maps forentityFees
     *
     * @param FeesResponse[]|null $forentityFees
     */
    public function setForentityFees(?array $forentityFees): void
    {
        $this->forentityFees = $forentityFees;
    }

    /**
     * Returns Forentity Profit Shares.
     *
     * @return ProfitSharesResponse[]|null
     */
    public function getForentityProfitShares(): ?array
    {
        return $this->forentityProfitShares;
    }

    /**
     * Sets Forentity Profit Shares.
     *
     * @maps forentityProfitShares
     *
     * @param ProfitSharesResponse[]|null $forentityProfitShares
     */
    public function setForentityProfitShares(?array $forentityProfitShares): void
    {
        $this->forentityProfitShares = $forentityProfitShares;
    }

    /**
     * Returns Funds.
     *
     * @return FundsResponse[]|null
     */
    public function getFunds(): ?array
    {
        return $this->funds;
    }

    /**
     * Sets Funds.
     *
     * @maps funds
     *
     * @param FundsResponse[]|null $funds
     */
    public function setFunds(?array $funds): void
    {
        $this->funds = $funds;
    }

    /**
     * Returns Holds.
     *
     * @return HoldsResponse[]|null
     */
    public function getHolds(): ?array
    {
        return $this->holds;
    }

    /**
     * Sets Holds.
     *
     * @maps holds
     *
     * @param HoldsResponse[]|null $holds
     */
    public function setHolds(?array $holds): void
    {
        $this->holds = $holds;
    }

    /**
     * Returns Invoice Parameters.
     *
     * @return InvoiceParametersResponse[]|null
     */
    public function getInvoiceParameters(): ?array
    {
        return $this->invoiceParameters;
    }

    /**
     * Sets Invoice Parameters.
     *
     * @maps invoiceParameters
     *
     * @param InvoiceParametersResponse[]|null $invoiceParameters
     */
    public function setInvoiceParameters(?array $invoiceParameters): void
    {
        $this->invoiceParameters = $invoiceParameters;
    }

    /**
     * Returns Notes.
     *
     * @return NotesResponse[]|null
     */
    public function getNotes(): ?array
    {
        return $this->notes;
    }

    /**
     * Sets Notes.
     *
     * @maps notes
     *
     * @param NotesResponse[]|null $notes
     */
    public function setNotes(?array $notes): void
    {
        $this->notes = $notes;
    }

    /**
     * Returns Org Entities.
     *
     * @return OrgEntitiesResponse[]|null
     */
    public function getOrgEntities(): ?array
    {
        return $this->orgEntities;
    }

    /**
     * Sets Org Entities.
     *
     * @maps orgEntities
     *
     * @param OrgEntitiesResponse[]|null $orgEntities
     */
    public function setOrgEntities(?array $orgEntities): void
    {
        $this->orgEntities = $orgEntities;
    }

    /**
     * Returns Omni Tokens.
     *
     * @return OmniTokensResponse[]|null
     */
    public function getOmniTokens(): ?array
    {
        return $this->omniTokens;
    }

    /**
     * Sets Omni Tokens.
     *
     * @maps omniTokens
     *
     * @param OmniTokensResponse[]|null $omniTokens
     */
    public function setOmniTokens(?array $omniTokens): void
    {
        $this->omniTokens = $omniTokens;
    }

    /**
     * Returns Payment Update Groups.
     *
     * @return PaymentUpdateGroupsResponse[]|null
     */
    public function getPaymentUpdateGroups(): ?array
    {
        return $this->paymentUpdateGroups;
    }

    /**
     * Sets Payment Update Groups.
     *
     * @maps paymentUpdateGroups
     *
     * @param PaymentUpdateGroupsResponse[]|null $paymentUpdateGroups
     */
    public function setPaymentUpdateGroups(?array $paymentUpdateGroups): void
    {
        $this->paymentUpdateGroups = $paymentUpdateGroups;
    }

    /**
     * Returns Payout Flows.
     *
     * @return PayoutFlowsResponse[]|null
     */
    public function getPayoutFlows(): ?array
    {
        return $this->payoutFlows;
    }

    /**
     * Sets Payout Flows.
     *
     * @maps payoutFlows
     *
     * @param PayoutFlowsResponse[]|null $payoutFlows
     */
    public function setPayoutFlows(?array $payoutFlows): void
    {
        $this->payoutFlows = $payoutFlows;
    }

    /**
     * Returns Payouts.
     *
     * @return PayoutsResponse[]|null
     */
    public function getPayouts(): ?array
    {
        return $this->payouts;
    }

    /**
     * Sets Payouts.
     *
     * @maps payouts
     *
     * @param PayoutsResponse[]|null $payouts
     */
    public function setPayouts(?array $payouts): void
    {
        $this->payouts = $payouts;
    }

    /**
     * Returns Pending Entries Onentity.
     *
     * @return PendingEntriesResponse[]|null
     */
    public function getPendingEntriesOnentity(): ?array
    {
        return $this->pendingEntriesOnentity;
    }

    /**
     * Sets Pending Entries Onentity.
     *
     * @maps pendingEntriesOnentity
     *
     * @param PendingEntriesResponse[]|null $pendingEntriesOnentity
     */
    public function setPendingEntriesOnentity(?array $pendingEntriesOnentity): void
    {
        $this->pendingEntriesOnentity = $pendingEntriesOnentity;
    }

    /**
     * Returns Pinless Debit Conversions.
     *
     * @return PinlessDebitConversionsResponse[]|null
     */
    public function getPinlessDebitConversions(): ?array
    {
        return $this->pinlessDebitConversions;
    }

    /**
     * Sets Pinless Debit Conversions.
     *
     * @maps pinlessDebitConversions
     *
     * @param PinlessDebitConversionsResponse[]|null $pinlessDebitConversions
     */
    public function setPinlessDebitConversions(?array $pinlessDebitConversions): void
    {
        $this->pinlessDebitConversions = $pinlessDebitConversions;
    }

    /**
     * Returns Profit Shares.
     *
     * @return ProfitSharesResponse[]|null
     */
    public function getProfitShares(): ?array
    {
        return $this->profitShares;
    }

    /**
     * Sets Profit Shares.
     *
     * @maps profitShares
     *
     * @param ProfitSharesResponse[]|null $profitShares
     */
    public function setProfitShares(?array $profitShares): void
    {
        $this->profitShares = $profitShares;
    }

    /**
     * Returns Reserve Entries Onentity.
     *
     * @return ReserveEntriesResponse[]|null
     */
    public function getReserveEntriesOnentity(): ?array
    {
        return $this->reserveEntriesOnentity;
    }

    /**
     * Sets Reserve Entries Onentity.
     *
     * @maps reserveEntriesOnentity
     *
     * @param ReserveEntriesResponse[]|null $reserveEntriesOnentity
     */
    public function setReserveEntriesOnentity(?array $reserveEntriesOnentity): void
    {
        $this->reserveEntriesOnentity = $reserveEntriesOnentity;
    }

    /**
     * Returns Reserves.
     *
     * @return ReservesResponse[]|null
     */
    public function getReserves(): ?array
    {
        return $this->reserves;
    }

    /**
     * Sets Reserves.
     *
     * @maps reserves
     *
     * @param ReservesResponse[]|null $reserves
     */
    public function setReserves(?array $reserves): void
    {
        $this->reserves = $reserves;
    }

    /**
     * Returns Revenue Boosts.
     *
     * @return RevenueBoostsResponse[]|null
     */
    public function getRevenueBoosts(): ?array
    {
        return $this->revenueBoosts;
    }

    /**
     * Sets Revenue Boosts.
     *
     * @maps revenueBoosts
     *
     * @param RevenueBoostsResponse[]|null $revenueBoosts
     */
    public function setRevenueBoosts(?array $revenueBoosts): void
    {
        $this->revenueBoosts = $revenueBoosts;
    }

    /**
     * Returns Rev Share Schedules Entity.
     *
     * @return RevShareSchedulesResponse[]|null
     */
    public function getRevShareSchedulesEntity(): ?array
    {
        return $this->revShareSchedulesEntity;
    }

    /**
     * Sets Rev Share Schedules Entity.
     *
     * @maps revShareSchedulesEntity
     *
     * @param RevShareSchedulesResponse[]|null $revShareSchedulesEntity
     */
    public function setRevShareSchedulesEntity(?array $revShareSchedulesEntity): void
    {
        $this->revShareSchedulesEntity = $revShareSchedulesEntity;
    }

    /**
     * Returns Rev Share Schedules Forentity.
     *
     * @return RevShareSchedulesResponse[]|null
     */
    public function getRevShareSchedulesForentity(): ?array
    {
        return $this->revShareSchedulesForentity;
    }

    /**
     * Sets Rev Share Schedules Forentity.
     *
     * @maps revShareSchedulesForentity
     *
     * @param RevShareSchedulesResponse[]|null $revShareSchedulesForentity
     */
    public function setRevShareSchedulesForentity(?array $revShareSchedulesForentity): void
    {
        $this->revShareSchedulesForentity = $revShareSchedulesForentity;
    }

    /**
     * Returns Rev Share Statements Entity.
     *
     * @return RevShareStatmentsResponse[]|null
     */
    public function getRevShareStatementsEntity(): ?array
    {
        return $this->revShareStatementsEntity;
    }

    /**
     * Sets Rev Share Statements Entity.
     *
     * @maps revShareStatementsEntity
     *
     * @param RevShareStatmentsResponse[]|null $revShareStatementsEntity
     */
    public function setRevShareStatementsEntity(?array $revShareStatementsEntity): void
    {
        $this->revShareStatementsEntity = $revShareStatementsEntity;
    }

    /**
     * Returns Rev Share Statements Forentity.
     *
     * @return RevShareStatmentsResponse[]|null
     */
    public function getRevShareStatementsForentity(): ?array
    {
        return $this->revShareStatementsForentity;
    }

    /**
     * Sets Rev Share Statements Forentity.
     *
     * @maps revShareStatementsForentity
     *
     * @param RevShareStatmentsResponse[]|null $revShareStatementsForentity
     */
    public function setRevShareStatementsForentity(?array $revShareStatementsForentity): void
    {
        $this->revShareStatementsForentity = $revShareStatementsForentity;
    }

    /**
     * Returns Secrets.
     *
     * @return SecretsResponse[]|null
     */
    public function getSecrets(): ?array
    {
        return $this->secrets;
    }

    /**
     * Sets Secrets.
     *
     * @maps secrets
     *
     * @param SecretsResponse[]|null $secrets
     */
    public function setSecrets(?array $secrets): void
    {
        $this->secrets = $secrets;
    }

    /**
     * Returns Statement Entries.
     *
     * @return StatementEntriesResponse[]|null
     */
    public function getStatementEntries(): ?array
    {
        return $this->statementEntries;
    }

    /**
     * Sets Statement Entries.
     *
     * @maps statementEntries
     *
     * @param StatementEntriesResponse[]|null $statementEntries
     */
    public function setStatementEntries(?array $statementEntries): void
    {
        $this->statementEntries = $statementEntries;
    }

    /**
     * Returns Statement Entries Onentity.
     *
     * @return StatementEntriesResponse[]|null
     */
    public function getStatementEntriesOnentity(): ?array
    {
        return $this->statementEntriesOnentity;
    }

    /**
     * Sets Statement Entries Onentity.
     *
     * @maps statementEntriesOnentity
     *
     * @param StatementEntriesResponse[]|null $statementEntriesOnentity
     */
    public function setStatementEntriesOnentity(?array $statementEntriesOnentity): void
    {
        $this->statementEntriesOnentity = $statementEntriesOnentity;
    }

    /**
     * Returns Statement Entries Forentity.
     *
     * @return StatementEntriesResponse[]|null
     */
    public function getStatementEntriesForentity(): ?array
    {
        return $this->statementEntriesForentity;
    }

    /**
     * Sets Statement Entries Forentity.
     *
     * @maps statementEntriesForentity
     *
     * @param StatementEntriesResponse[]|null $statementEntriesForentity
     */
    public function setStatementEntriesForentity(?array $statementEntriesForentity): void
    {
        $this->statementEntriesForentity = $statementEntriesForentity;
    }

    /**
     * Returns Subscriptions.
     *
     * @return SubscriptionsResponse[]|null
     */
    public function getSubscriptions(): ?array
    {
        return $this->subscriptions;
    }

    /**
     * Sets Subscriptions.
     *
     * @maps subscriptions
     *
     * @param SubscriptionsResponse[]|null $subscriptions
     */
    public function setSubscriptions(?array $subscriptions): void
    {
        $this->subscriptions = $subscriptions;
    }

    /**
     * Returns Statements Entity.
     *
     * @return StatementsResponse[]|null
     */
    public function getStatementsEntity(): ?array
    {
        return $this->statementsEntity;
    }

    /**
     * Sets Statements Entity.
     *
     * @maps statementsEntity
     *
     * @param StatementsResponse[]|null $statementsEntity
     */
    public function setStatementsEntity(?array $statementsEntity): void
    {
        $this->statementsEntity = $statementsEntity;
    }

    /**
     * Returns Statements Forentity.
     *
     * @return StatementsResponse[]|null
     */
    public function getStatementsForentity(): ?array
    {
        return $this->statementsForentity;
    }

    /**
     * Sets Statements Forentity.
     *
     * @maps statementsForentity
     *
     * @param StatementsResponse[]|null $statementsForentity
     */
    public function setStatementsForentity(?array $statementsForentity): void
    {
        $this->statementsForentity = $statementsForentity;
    }

    /**
     * Returns Safer Payments.
     *
     * @return SaferPaymentsResponse[]|null
     */
    public function getSaferPayments(): ?array
    {
        return $this->saferPayments;
    }

    /**
     * Sets Safer Payments.
     *
     * @maps saferPayments
     *
     * @param SaferPaymentsResponse[]|null $saferPayments
     */
    public function setSaferPayments(?array $saferPayments): void
    {
        $this->saferPayments = $saferPayments;
    }

    /**
     * Returns Vendor.
     *
     * @return VendorsResponse[]|null
     */
    public function getVendor(): ?array
    {
        return $this->vendor;
    }

    /**
     * Sets Vendor.
     *
     * @maps vendor
     *
     * @param VendorsResponse[]|null $vendor
     */
    public function setVendor(?array $vendor): void
    {
        $this->vendor = $vendor;
    }

    /**
     * Returns Merchant.
     */
    public function getMerchant(): ?MerchantsResponse
    {
        return $this->merchant;
    }

    /**
     * Sets Merchant.
     *
     * @maps merchant
     */
    public function setMerchant(?MerchantsResponse $merchant): void
    {
        $this->merchant = $merchant;
    }

    /**
     * Converts the EntitiesResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EntitiesResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EntitiesResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'ipCreated' => $this->ipCreated,
                'ipModified' => $this->ipModified,
                'clientIp' => $this->clientIp,
                'login' => $this->login,
                'parameter' => $this->parameter,
                'totalCreditDisbursements' => $this->totalCreditDisbursements,
                'type' => $this->type,
                'name' => $this->name,
                'displayName' => $this->displayName,
                'address1' => $this->address1,
                'address2' => $this->address2,
                'city' => $this->city,
                'state' => $this->state,
                'website' => $this->website,
                'zip' => $this->zip,
                'country' => $this->country,
                'timezone' => $this->timezone,
                'phone' => $this->phone,
                'customerPhone' => $this->customerPhone,
                'fax' => $this->fax,
                'email' => $this->email,
                'ein' => $this->ein,
                'einType' => $this->einType,
                'globalBusinessId' => $this->globalBusinessId,
                'globalBusinessType' => $this->globalBusinessType,
                'irsFilingName' => $this->irsFilingName,
                'locations' => $this->locations,
                'tcVersion' => $this->tcVersion,
                'tcDate' => $this->tcDate,
                'tcIp' => $this->tcIp,
                'tcAcceptDate' => $this->tcAcceptDate,
                'tcAcceptIp' => $this->tcAcceptIp,
                'custom' => $this->custom,
                'tinStatus' => $this->tinStatus,
                'public' => $this->public,
                'reserved' => $this->reserved,
                'pendingRiskCheck' => $this->pendingRiskCheck,
                'checkStage' => $this->checkStage,
                'industry' => $this->industry,
                'payoutSecondaryDescriptor' => $this->payoutSecondaryDescriptor,
                'currency' => $this->getCurrency(),
                'inactive' => $this->inactive,
                'frozen' => $this->frozen,
                'accounts' => $this->accounts,
                'adjustments' => $this->adjustments,
                'adjustmentsFromentity' => $this->adjustmentsFromentity,
                'adjustmentsOnentity' => $this->adjustmentsOnentity,
                'aggregations' => $this->aggregations,
                'ownedAppleDomains' => $this->ownedAppleDomains,
                'assessmentsOnentity' => $this->assessmentsOnentity,
                'billingModifiers' => $this->billingModifiers,
                'billings' => $this->billings,
                'billingsForentity' => $this->billingsForentity,
                'changeRequests' => $this->changeRequests,
                'contacts' => $this->contacts,
                'credentials' => $this->credentials,
                'disbursements' => $this->disbursements,
                'decisions' => $this->decisions,
                'embeddedFinance' => $this->embeddedFinance,
                'entityCustomFields' => $this->entityCustomFields,
                'entityData' => $this->entityData,
                'entityDebts' => $this->entityDebts,
                'entityDebtsToentity' => $this->entityDebtsToentity,
                'entityRefs' => $this->entityRefs,
                'entityReturns' => $this->entityReturns,
                'entityTerms' => $this->entityTerms,
                'entriesOnentity' => $this->entriesOnentity,
                'fees' => $this->fees,
                'forentityFees' => $this->forentityFees,
                'forentityProfitShares' => $this->forentityProfitShares,
                'funds' => $this->funds,
                'holds' => $this->holds,
                'invoiceParameters' => $this->invoiceParameters,
                'notes' => $this->notes,
                'orgEntities' => $this->orgEntities,
                'omniTokens' => $this->omniTokens,
                'paymentUpdateGroups' => $this->paymentUpdateGroups,
                'payoutFlows' => $this->payoutFlows,
                'payouts' => $this->payouts,
                'pendingEntriesOnentity' => $this->pendingEntriesOnentity,
                'pinlessDebitConversions' => $this->pinlessDebitConversions,
                'profitShares' => $this->profitShares,
                'reserveEntriesOnentity' => $this->reserveEntriesOnentity,
                'reserves' => $this->reserves,
                'revenueBoosts' => $this->revenueBoosts,
                'revShareSchedulesEntity' => $this->revShareSchedulesEntity,
                'revShareSchedulesForentity' => $this->revShareSchedulesForentity,
                'revShareStatementsEntity' => $this->revShareStatementsEntity,
                'revShareStatementsForentity' => $this->revShareStatementsForentity,
                'secrets' => $this->secrets,
                'statementEntries' => $this->statementEntries,
                'statementEntriesOnentity' => $this->statementEntriesOnentity,
                'statementEntriesForentity' => $this->statementEntriesForentity,
                'subscriptions' => $this->subscriptions,
                'statementsEntity' => $this->statementsEntity,
                'statementsForentity' => $this->statementsForentity,
                'saferPayments' => $this->saferPayments,
                'vendor' => $this->vendor,
                'merchant' => $this->merchant
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                          = $this->id;
        }
        if (isset($this->created)) {
            $json['created']                     = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']                    = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']                     =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']                    = $this->modifier;
        }
        if (isset($this->ipCreated)) {
            $json['ipCreated']                   = $this->ipCreated;
        }
        if (isset($this->ipModified)) {
            $json['ipModified']                  = $this->ipModified;
        }
        if (isset($this->clientIp)) {
            $json['clientIp']                    = $this->clientIp;
        }
        if (isset($this->login)) {
            $json['login']                       =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->login,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->parameter)) {
            $json['parameter']                   = $this->parameter;
        }
        if (isset($this->totalCreditDisbursements)) {
            $json['totalCreditDisbursements']    = $this->totalCreditDisbursements;
        }
        if (isset($this->type)) {
            $json['type']                        = EntityTypeEnum::checkValue($this->type);
        }
        if (isset($this->name)) {
            $json['name']                        = $this->name;
        }
        if (isset($this->displayName)) {
            $json['displayName']                 = $this->displayName;
        }
        if (isset($this->address1)) {
            $json['address1']                    = $this->address1;
        }
        if (isset($this->address2)) {
            $json['address2']                    = $this->address2;
        }
        if (isset($this->city)) {
            $json['city']                        = $this->city;
        }
        if (isset($this->state)) {
            $json['state']                       = $this->state;
        }
        if (isset($this->website)) {
            $json['website']                     = $this->website;
        }
        if (isset($this->zip)) {
            $json['zip']                         = $this->zip;
        }
        if (isset($this->country)) {
            $json['country']                     = EntityCountryEnum::checkValue($this->country);
        }
        if (isset($this->timezone)) {
            $json['timezone']                    = EntitiesTimezoneEnum::checkValue($this->timezone);
        }
        if (isset($this->phone)) {
            $json['phone']                       = $this->phone;
        }
        if (isset($this->customerPhone)) {
            $json['customerPhone']               = $this->customerPhone;
        }
        if (isset($this->fax)) {
            $json['fax']                         = $this->fax;
        }
        if (isset($this->email)) {
            $json['email']                       = $this->email;
        }
        if (isset($this->ein)) {
            $json['ein']                         = $this->ein;
        }
        if (isset($this->einType)) {
            $json['einType']                     = EntitiesEinTypeEnum::checkValue($this->einType);
        }
        if (isset($this->globalBusinessId)) {
            $json['globalBusinessId']            = $this->globalBusinessId;
        }
        if (isset($this->globalBusinessType)) {
            $json['globalBusinessType']          = GlobalBusinessTypeEnum::checkValue($this->globalBusinessType);
        }
        if (isset($this->irsFilingName)) {
            $json['irsFilingName']               = $this->irsFilingName;
        }
        if (isset($this->locations)) {
            $json['locations']                   = $this->locations;
        }
        if (isset($this->tcVersion)) {
            $json['tcVersion']                   = $this->tcVersion;
        }
        if (isset($this->tcDate)) {
            $json['tcDate']                      = $this->tcDate;
        }
        if (isset($this->tcIp)) {
            $json['tcIp']                        = $this->tcIp;
        }
        if (isset($this->tcAcceptDate)) {
            $json['tcAcceptDate']                = $this->tcAcceptDate;
        }
        if (isset($this->tcAcceptIp)) {
            $json['tcAcceptIp']                  = $this->tcAcceptIp;
        }
        if (isset($this->custom)) {
            $json['custom']                      = $this->custom;
        }
        if (isset($this->tinStatus)) {
            $json['tinStatus']                   = EntitiesTinStatusEnum::checkValue($this->tinStatus);
        }
        if (isset($this->public)) {
            $json['public']                      = EntitiesPublicEnum::checkValue($this->public);
        }
        if (isset($this->reserved)) {
            $json['reserved']                    = EntitiesReservedEnum::checkValue($this->reserved);
        }
        if (isset($this->pendingRiskCheck)) {
            $json['pendingRiskCheck']            = EntityPendingRiskCheckEnum::checkValue($this->pendingRiskCheck);
        }
        if (isset($this->checkStage)) {
            $json['checkStage']                  = EntityCheckStageEnum::checkValue($this->checkStage);
        }
        if (isset($this->industry)) {
            $json['industry']                    = $this->industry;
        }
        if (isset($this->payoutSecondaryDescriptor)) {
            $json['payoutSecondaryDescriptor']   = $this->payoutSecondaryDescriptor;
        }
        if (!empty($this->currency)) {
            $json['currency']                    = CurrencyEnum::checkValue($this->currency['value']);
        }
        if (isset($this->inactive)) {
            $json['inactive']                    = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']                      = FrozenEnum::checkValue($this->frozen);
        }
        if (isset($this->accounts)) {
            $json['accounts']                    = $this->accounts;
        }
        if (isset($this->adjustments)) {
            $json['adjustments']                 = $this->adjustments;
        }
        if (isset($this->adjustmentsFromentity)) {
            $json['adjustmentsFromentity']       = $this->adjustmentsFromentity;
        }
        if (isset($this->adjustmentsOnentity)) {
            $json['adjustmentsOnentity']         = $this->adjustmentsOnentity;
        }
        if (isset($this->aggregations)) {
            $json['aggregations']                = $this->aggregations;
        }
        if (isset($this->ownedAppleDomains)) {
            $json['ownedAppleDomains']           = $this->ownedAppleDomains;
        }
        if (isset($this->assessmentsOnentity)) {
            $json['assessmentsOnentity']         = $this->assessmentsOnentity;
        }
        if (isset($this->billingModifiers)) {
            $json['billingModifiers']            = $this->billingModifiers;
        }
        if (isset($this->billings)) {
            $json['billings']                    = $this->billings;
        }
        if (isset($this->billingsForentity)) {
            $json['billingsForentity']           = $this->billingsForentity;
        }
        if (isset($this->changeRequests)) {
            $json['changeRequests']              = $this->changeRequests;
        }
        if (isset($this->contacts)) {
            $json['contacts']                    = $this->contacts;
        }
        if (isset($this->credentials)) {
            $json['credentials']                 = $this->credentials;
        }
        if (isset($this->disbursements)) {
            $json['disbursements']               = $this->disbursements;
        }
        if (isset($this->decisions)) {
            $json['decisions']                   = $this->decisions;
        }
        if (isset($this->embeddedFinance)) {
            $json['embeddedFinance']             = $this->embeddedFinance;
        }
        if (isset($this->entityCustomFields)) {
            $json['entityCustomFields']          = $this->entityCustomFields;
        }
        if (isset($this->entityData)) {
            $json['entityData']                  = $this->entityData;
        }
        if (isset($this->entityDebts)) {
            $json['entityDebts']                 = $this->entityDebts;
        }
        if (isset($this->entityDebtsToentity)) {
            $json['entityDebtsToentity']         = $this->entityDebtsToentity;
        }
        if (isset($this->entityRefs)) {
            $json['entityRefs']                  = $this->entityRefs;
        }
        if (isset($this->entityReturns)) {
            $json['entityReturns']               = $this->entityReturns;
        }
        if (isset($this->entityTerms)) {
            $json['entityTerms']                 = $this->entityTerms;
        }
        if (isset($this->entriesOnentity)) {
            $json['entriesOnentity']             = $this->entriesOnentity;
        }
        if (isset($this->fees)) {
            $json['fees']                        = $this->fees;
        }
        if (isset($this->forentityFees)) {
            $json['forentityFees']               = $this->forentityFees;
        }
        if (isset($this->forentityProfitShares)) {
            $json['forentityProfitShares']       = $this->forentityProfitShares;
        }
        if (isset($this->funds)) {
            $json['funds']                       = $this->funds;
        }
        if (isset($this->holds)) {
            $json['holds']                       = $this->holds;
        }
        if (isset($this->invoiceParameters)) {
            $json['invoiceParameters']           = $this->invoiceParameters;
        }
        if (isset($this->notes)) {
            $json['notes']                       = $this->notes;
        }
        if (isset($this->orgEntities)) {
            $json['orgEntities']                 = $this->orgEntities;
        }
        if (isset($this->omniTokens)) {
            $json['omniTokens']                  = $this->omniTokens;
        }
        if (isset($this->paymentUpdateGroups)) {
            $json['paymentUpdateGroups']         = $this->paymentUpdateGroups;
        }
        if (isset($this->payoutFlows)) {
            $json['payoutFlows']                 = $this->payoutFlows;
        }
        if (isset($this->payouts)) {
            $json['payouts']                     = $this->payouts;
        }
        if (isset($this->pendingEntriesOnentity)) {
            $json['pendingEntriesOnentity']      = $this->pendingEntriesOnentity;
        }
        if (isset($this->pinlessDebitConversions)) {
            $json['pinlessDebitConversions']     = $this->pinlessDebitConversions;
        }
        if (isset($this->profitShares)) {
            $json['profitShares']                = $this->profitShares;
        }
        if (isset($this->reserveEntriesOnentity)) {
            $json['reserveEntriesOnentity']      = $this->reserveEntriesOnentity;
        }
        if (isset($this->reserves)) {
            $json['reserves']                    = $this->reserves;
        }
        if (isset($this->revenueBoosts)) {
            $json['revenueBoosts']               = $this->revenueBoosts;
        }
        if (isset($this->revShareSchedulesEntity)) {
            $json['revShareSchedulesEntity']     = $this->revShareSchedulesEntity;
        }
        if (isset($this->revShareSchedulesForentity)) {
            $json['revShareSchedulesForentity']  = $this->revShareSchedulesForentity;
        }
        if (isset($this->revShareStatementsEntity)) {
            $json['revShareStatementsEntity']    = $this->revShareStatementsEntity;
        }
        if (isset($this->revShareStatementsForentity)) {
            $json['revShareStatementsForentity'] = $this->revShareStatementsForentity;
        }
        if (isset($this->secrets)) {
            $json['secrets']                     = $this->secrets;
        }
        if (isset($this->statementEntries)) {
            $json['statementEntries']            = $this->statementEntries;
        }
        if (isset($this->statementEntriesOnentity)) {
            $json['statementEntriesOnentity']    = $this->statementEntriesOnentity;
        }
        if (isset($this->statementEntriesForentity)) {
            $json['statementEntriesForentity']   = $this->statementEntriesForentity;
        }
        if (isset($this->subscriptions)) {
            $json['subscriptions']               = $this->subscriptions;
        }
        if (isset($this->statementsEntity)) {
            $json['statementsEntity']            = $this->statementsEntity;
        }
        if (isset($this->statementsForentity)) {
            $json['statementsForentity']         = $this->statementsForentity;
        }
        if (isset($this->saferPayments)) {
            $json['saferPayments']               = $this->saferPayments;
        }
        if (isset($this->vendor)) {
            $json['vendor']                      = $this->vendor;
        }
        if (isset($this->merchant)) {
            $json['merchant']                    = $this->merchant;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
