<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class FeeApplicationEnum
{
    /**
     * The rule should apply to the fee and to the calculation of collections.
     */
    public const BOTH = 'both';

    /**
     * The rule should apply only to the fee itself.
     */
    public const FEE = 'fee';

    /**
     * The fee should be only used when calculating a collection.
     */
    public const COLLECTION = 'collection';

    private const _ALL_VALUES = [self::BOTH, self::FEE, self::COLLECTION];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for FeeApplicationEnum.");
    }
}
