<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class FeeRulesResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|FeesResponse|null
     */
    private $fee;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $application = FeeApplicationEnum::BOTH;

    /**
     * @var string|null
     */
    private $value;

    /**
     * @var string|null
     */
    private $grouping;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Fee.
     * The identifier of the Fee that this Fee Rule applies.
     *
     * @return string|FeesResponse|null
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Sets Fee.
     * The identifier of the Fee that this Fee Rule applies.
     *
     * @maps fee
     * @mapsBy anyOf(anyOf(string,FeesResponse),null)
     *
     * @param string|FeesResponse|null $fee
     */
    public function setFee($fee): void
    {
        $this->fee = $fee;
    }

    /**
     * Returns Name.
     * The name of this Fee Rule.
     * This field is stored as a text string and must be between 0 and 100 characters long.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of this Fee Rule.
     * This field is stored as a text string and must be between 0 and 100 characters long.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Description.
     * The description of this Fee Rule.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * The description of this Fee Rule.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Type.
     * The type of Fee Rule.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `AVSRESULT`
     * - `BIN`
     * - `BUSINESS`
     * - `CVVRESULT`
     * - `CORPORATE`
     * - `DYNAMICALLYROUTED`
     * - `EMV`
     * - `ENTITY`
     * - `EQUAL`
     * - `FRAUDSIGHTENABLED`
     * - `FUNDINGCURRENCYEQUAL`
     * - `FUNDINGCURRENCYNOTEQUAL`
     * - `FUNDINGCURRENCYMISMATCH`
     * - `FUNDINGENABLED`
     * - `GREATER`
     * - `IMPORTED`
     * - `INTERCHANGE`
     * - `INTERNATIONAL`
     * - `ISSUERCOUNTRY`
     * - `LESS`
     * - `MCC`
     * - `MERCHANTCOUNTRY`
     * - `METHOD`
     * - `METHODTYPE`
     * - `MISUSE`
     * - `NOTEQUAL`
     * - `ORIGIN`
     * - `OMNITOKENSENABLED`
     * - `PLATFORM`
     * - `RELATED`
     * - `RELATEDCEIL`
     * - `RELATEDDELAY`
     * - `RELATEDFLOOR`
     * - `SAMEDAY`
     * - `SETTLEDCURRENCYMISMATCH`
     * - `SIGNED`
     * - `SUBSCRIPTION`
     * - `SWIPED`
     * - `TAXFORM1099K`
     * - `TYPE`
     * - `3DSRESULT`
     * - `STATUS`
     * - `IC_RETAIN_PASSTHRU_REFUND`
     * - `SOFTPOS`
     *
     * </details>
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of Fee Rule.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `AVSRESULT`
     * - `BIN`
     * - `BUSINESS`
     * - `CVVRESULT`
     * - `CORPORATE`
     * - `DYNAMICALLYROUTED`
     * - `EMV`
     * - `ENTITY`
     * - `EQUAL`
     * - `FRAUDSIGHTENABLED`
     * - `FUNDINGCURRENCYEQUAL`
     * - `FUNDINGCURRENCYNOTEQUAL`
     * - `FUNDINGCURRENCYMISMATCH`
     * - `FUNDINGENABLED`
     * - `GREATER`
     * - `IMPORTED`
     * - `INTERCHANGE`
     * - `INTERNATIONAL`
     * - `ISSUERCOUNTRY`
     * - `LESS`
     * - `MCC`
     * - `MERCHANTCOUNTRY`
     * - `METHOD`
     * - `METHODTYPE`
     * - `MISUSE`
     * - `NOTEQUAL`
     * - `ORIGIN`
     * - `OMNITOKENSENABLED`
     * - `PLATFORM`
     * - `RELATED`
     * - `RELATEDCEIL`
     * - `RELATEDDELAY`
     * - `RELATEDFLOOR`
     * - `SAMEDAY`
     * - `SETTLEDCURRENCYMISMATCH`
     * - `SIGNED`
     * - `SUBSCRIPTION`
     * - `SWIPED`
     * - `TAXFORM1099K`
     * - `TYPE`
     * - `3DSRESULT`
     * - `STATUS`
     * - `IC_RETAIN_PASSTHRU_REFUND`
     * - `SOFTPOS`
     *
     * </details>
     *
     * @maps type
     * @factory \PayrixLib\Models\FeeRuleTypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Application.
     * Where the feeRule should apply.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `both` - **Both.** The rule should apply to the fee and to the calculation of collections.
     * - `fee` - **Fee.** The rule should apply only to the fee itself.
     * - `collection` - **Collection.** The fee should be only used when calculating a collection.
     *
     * </details>
     */
    public function getApplication(): ?string
    {
        return $this->application;
    }

    /**
     * Sets Application.
     * Where the feeRule should apply.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `both` - **Both.** The rule should apply to the fee and to the calculation of collections.
     * - `fee` - **Fee.** The rule should apply only to the fee itself.
     * - `collection` - **Collection.** The fee should be only used when calculating a collection.
     *
     * </details>
     *
     * @maps application
     * @factory \PayrixLib\Models\FeeApplicationEnum::checkValue
     */
    public function setApplication(?string $application): void
    {
        $this->application = $application;
    }

    /**
     * Returns Value.
     * The value to compare against when evaluating this Fee Rule.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * The value to compare against when evaluating this Fee Rule.
     *
     * @maps value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Returns Grouping.
     * A name for a group of rules to be applied in conjunction when evaluating this Fee Rule.
     * When grouping is used, the Fee will be allowed to be processed if at least one of the rules are
     * matched.
     */
    public function getGrouping(): ?string
    {
        return $this->grouping;
    }

    /**
     * Sets Grouping.
     * A name for a group of rules to be applied in conjunction when evaluating this Fee Rule.
     * When grouping is used, the Fee will be allowed to be processed if at least one of the rules are
     * matched.
     *
     * @maps grouping
     */
    public function setGrouping(?string $grouping): void
    {
        $this->grouping = $grouping;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Converts the FeeRulesResponse object to a human-readable string representation.
     *
     * @return string The string representation of the FeeRulesResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FeeRulesResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'fee' => $this->fee,
                'name' => $this->name,
                'description' => $this->description,
                'type' => $this->type,
                'application' => $this->application,
                'value' => $this->value,
                'grouping' => $this->grouping,
                'inactive' => $this->inactive,
                'frozen' => $this->frozen
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']          = $this->id;
        }
        if (isset($this->created)) {
            $json['created']     = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']    = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']     =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']    = $this->modifier;
        }
        if (isset($this->fee)) {
            $json['fee']         =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->fee,
                    'anyOf(anyOf(string,FeesResponse),null)'
                );
        }
        if (isset($this->name)) {
            $json['name']        = $this->name;
        }
        if (isset($this->description)) {
            $json['description'] = $this->description;
        }
        if (isset($this->type)) {
            $json['type']        = FeeRuleTypeEnum::checkValue($this->type);
        }
        if (isset($this->application)) {
            $json['application'] = FeeApplicationEnum::checkValue($this->application);
        }
        if (isset($this->value)) {
            $json['value']       = $this->value;
        }
        if (isset($this->grouping)) {
            $json['grouping']    = $this->grouping;
        }
        if (isset($this->inactive)) {
            $json['inactive']    = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']      = FrozenEnum::checkValue($this->frozen);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
