<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class FraudSightEnablementsPutRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $entity;

    /**
     * @var string
     */
    private $groupName;

    /**
     * @var string
     */
    private $description;

    /**
     * @param string $entity
     * @param string $groupName
     * @param string $description
     */
    public function __construct(string $entity, string $groupName, string $description)
    {
        $this->entity = $entity;
        $this->groupName = $groupName;
        $this->description = $description;
    }

    /**
     * Returns Entity.
     * The identifier of the Entity that fraudSightEnablements is associated to.
     */
    public function getEntity(): string
    {
        return $this->entity;
    }

    /**
     * Sets Entity.
     * The identifier of the Entity that fraudSightEnablements is associated to.
     *
     * @required
     * @maps entity
     */
    public function setEntity(string $entity): void
    {
        $this->entity = $entity;
    }

    /**
     * Returns Group Name.
     * The name of the group for this FraudSight enablement.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `PIECPA` - Post Network -Decision Non EMV CP & Inform remaining CP.
     * - `PICNP` - Post Network - Decision CNP only & Inform CP.
     * - `PACPA` - Post Network - Decision All CP Authorizations.
     * - `INCNP` - Pre Network -Decision Non-Recurring CNP & Inform CP.
     * - `PIKCPA` - Post Network -Decision Key Entered CP & Inform remaining CP.
     * - `IECNP` - Pre Network -Decision CNP and Non EMV CP & Inform remaining CP.
     * - `ACPA` - Pre Network - Decision All CP Authorizations.
     * - `PACNP` - Post Network - Decision All Authorizations (CNP & CP).
     * - `PIECNP` - Post Network -Decision CNP and Non EMV CP & Inform remaining CP.
     * - `IKCPA` - Pre Network -Decision Key Entered CP & Inform remaining CP.
     * - `ACNP` - Pre Network - Decision All Authorizations (CNP & CP).
     * - `PINCNP` - Post Network -Decision Non-Recurring CNP & Inform CP.
     * - `IECPA` - Pre Network -Decision Non EMV CP & Inform remaining CP.
     * - `ICNP` - Pre Network - Decision CNP only & Inform CP.
     *
     * </details>
     */
    public function getGroupName(): string
    {
        return $this->groupName;
    }

    /**
     * Sets Group Name.
     * The name of the group for this FraudSight enablement.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `PIECPA` - Post Network -Decision Non EMV CP & Inform remaining CP.
     * - `PICNP` - Post Network - Decision CNP only & Inform CP.
     * - `PACPA` - Post Network - Decision All CP Authorizations.
     * - `INCNP` - Pre Network -Decision Non-Recurring CNP & Inform CP.
     * - `PIKCPA` - Post Network -Decision Key Entered CP & Inform remaining CP.
     * - `IECNP` - Pre Network -Decision CNP and Non EMV CP & Inform remaining CP.
     * - `ACPA` - Pre Network - Decision All CP Authorizations.
     * - `PACNP` - Post Network - Decision All Authorizations (CNP & CP).
     * - `PIECNP` - Post Network -Decision CNP and Non EMV CP & Inform remaining CP.
     * - `IKCPA` - Pre Network -Decision Key Entered CP & Inform remaining CP.
     * - `ACNP` - Pre Network - Decision All Authorizations (CNP & CP).
     * - `PINCNP` - Post Network -Decision Non-Recurring CNP & Inform CP.
     * - `IECPA` - Pre Network -Decision Non EMV CP & Inform remaining CP.
     * - `ICNP` - Pre Network - Decision CNP only & Inform CP.
     *
     * </details>
     *
     * @required
     * @maps groupName
     * @factory \PayrixLib\Models\GroupNameEnum::checkValue
     */
    public function setGroupName(string $groupName): void
    {
        $this->groupName = $groupName;
    }

    /**
     * Returns Description.
     * The description of the Group Name.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * The description of the Group Name.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Converts the FraudSightEnablementsPutRequest object to a human-readable string representation.
     *
     * @return string The string representation of the FraudSightEnablementsPutRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FraudSightEnablementsPutRequest',
            ['entity' => $this->entity, 'groupName' => $this->groupName, 'description' => $this->description]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['entity']      = $this->entity;
        $json['groupName']   = GroupNameEnum::checkValue($this->groupName);
        $json['description'] = $this->description;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
