<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class FundingParameterTypeEnum
{
    /**
     * The id to use for boarding merchants that are card not present.
     */
    public const AGENTCNP = 'agentCnp';

    /**
     * The id to use for boarding merchants that are card present.
     */
    public const AGENTCP = 'agentCp';

    /**
     * Company credit identifier.
     */
    public const CREDITCOMPANYID = 'creditCompanyId';

    /**
     * Company debit identifier.
     */
    public const DEBITCOMPANYID = 'debitCompanyId';

    /**
     * Delay.
     */
    public const DELAY = 'delay';

    /**
     * Additional delay for off days.
     */
    public const OFFDAYSADDITIONALDELAY = 'offDaysAdditionalDelay';

    /**
     * The amount of time in days to wait before issuing a transfer, counted from the date of the first
     * item within the total settlement amount.
     */
    public const SETTLEMENTACCOUNTTRANSFERDELAY = 'settlementAccountTransferDelay';

    /**
     * Indication if during settlements credits should be transferred from the merchant's operating account.
     */
    public const SETTLEMENTACCOUNTTRANSFERENABLED = 'settlementAccountTransferEnabled';

    /**
     * Additional amount to keep at the merchant's operating account.
     */
    public const SETTLEMENTACCOUNTTRANSFERFLOAT = 'settlementAccountTransferFloat';

    /**
     * The maximum amount needed to transfer funds from merchant's operating account.
     */
    public const SETTLEMENTACCOUNTTRANSFERMAXIMUM = 'settlementAccountTransferMaximum';

    /**
     * The minimum amount needed to transfer funds from the merchant's operating account.
     */
    public const SETTLEMENTACCOUNTTRANSFERMINIMUM = 'settlementAccountTransferMinimum';

    /**
     * The percent amount to transfer from the total settlement amount.
     */
    public const SETTLEMENTACCOUNTTRANSFERPERCENT = 'settlementAccountTransferPercent';

    /**
     * The specified time to close a batch.
     */
    public const CUSTOMBATCHCLOSETIME = 'customBatchCloseTime';

    /**
     * 2 am late funding cutoff time.
     */
    public const LATEFUNDING = 'lateFunding';

    /**
     * 5 am funding cutoff time.
     */
    public const FIVEAMFUNDING = '5AmFunding';

    private const _ALL_VALUES = [
        self::AGENTCNP,
        self::AGENTCP,
        self::CREDITCOMPANYID,
        self::DEBITCOMPANYID,
        self::DELAY,
        self::OFFDAYSADDITIONALDELAY,
        self::SETTLEMENTACCOUNTTRANSFERDELAY,
        self::SETTLEMENTACCOUNTTRANSFERENABLED,
        self::SETTLEMENTACCOUNTTRANSFERFLOAT,
        self::SETTLEMENTACCOUNTTRANSFERMAXIMUM,
        self::SETTLEMENTACCOUNTTRANSFERMINIMUM,
        self::SETTLEMENTACCOUNTTRANSFERPERCENT,
        self::CUSTOMBATCHCLOSETIME,
        self::LATEFUNDING,
        self::FIVEAMFUNDING
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for FundingParameterTypeEnum.");
    }
}
