<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class FundingParametersResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|LoginsResponse|null
     */
    private $login;

    /**
     * @var string|EntitiesResponse|null
     */
    private $entity;

    /**
     * @var string|OrgsResponse|null
     */
    private $org;

    /**
     * @var string|DivisionsResponse|null
     */
    private $division;

    /**
     * @var string|PartitionsResponse|null
     */
    private $partition;

    /**
     * @var string|null
     */
    private $platform = FundingParameterPlatformEnum::ALL;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $value;

    /**
     * @var string|null
     */
    private $paymentMethods;

    /**
     * @var int|null
     */
    private $locked = FundingParameterLockedEnum::OFF;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Login.
     * The identifier of the Login that owns this fundingParameter resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The identifier of the Login that owns this fundingParameter resource.
     *
     * @maps login
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Entity.
     * The identifier of the Entity associated with this fundingParameter.
     *
     * @return string|EntitiesResponse|null
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Sets Entity.
     * The identifier of the Entity associated with this fundingParameter.
     *
     * @maps entity
     * @mapsBy anyOf(anyOf(string,EntitiesResponse),null)
     *
     * @param string|EntitiesResponse|null $entity
     */
    public function setEntity($entity): void
    {
        $this->entity = $entity;
    }

    /**
     * Returns Org.
     * The identifier of the Org associated with this fundingParameter.
     *
     * @return string|OrgsResponse|null
     */
    public function getOrg()
    {
        return $this->org;
    }

    /**
     * Sets Org.
     * The identifier of the Org associated with this fundingParameter.
     *
     * @maps org
     * @mapsBy anyOf(anyOf(string,OrgsResponse),null)
     *
     * @param string|OrgsResponse|null $org
     */
    public function setOrg($org): void
    {
        $this->org = $org;
    }

    /**
     * Returns Division.
     * The identifier of the Division associated with this fundingParameter.
     *
     * @return string|DivisionsResponse|null
     */
    public function getDivision()
    {
        return $this->division;
    }

    /**
     * Sets Division.
     * The identifier of the Division associated with this fundingParameter.
     *
     * @maps division
     * @mapsBy anyOf(anyOf(string,DivisionsResponse),null)
     *
     * @param string|DivisionsResponse|null $division
     */
    public function setDivision($division): void
    {
        $this->division = $division;
    }

    /**
     * Returns Partition.
     * The identifier of the Partition associated with this fundingParameter.
     *
     * @return string|PartitionsResponse|null
     */
    public function getPartition()
    {
        return $this->partition;
    }

    /**
     * Sets Partition.
     * The identifier of the Partition associated with this fundingParameter.
     *
     * @maps partition
     * @mapsBy anyOf(anyOf(string,PartitionsResponse),null)
     *
     * @param string|PartitionsResponse|null $partition
     */
    public function setPartition($partition): void
    {
        $this->partition = $partition;
    }

    /**
     * Returns Platform.
     * The identifier of the Platform associated with this fundingParameter.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `APPLE` - **The Apple Payment Processor.**
     * - `ELAVON` - **The Elavon processor.**
     * - `FIRSTDATA` - **The First Data processor.**
     * - `GOOGLE` - **The Google Payment Processor.**
     * - `VANTIV` - **The WorldPay (aka Vantiv or Litle) eComm (aka VAP) processor.**
     * - `VCORE` - **The WorldPay (aka Vantiv) Core processor.**
     * - `WELLSACH` - **The Wells Fargo ACH processor.**
     * - `WELLSFARGO` - **The Wells Fargo Merchant Services processor.**
     * - `WFSINGLE` - **The WFSINGLE processor.**
     * - `WORLDPAY` - **The WORLDPAY processor.**
     * - `TDBANKCA` - **External funding with TD Bank Canada via the Operating Account.**
     * - `all` - **All Platform Processor.**
     *
     * </details>
     */
    public function getPlatform(): ?string
    {
        return $this->platform;
    }

    /**
     * Sets Platform.
     * The identifier of the Platform associated with this fundingParameter.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `APPLE` - **The Apple Payment Processor.**
     * - `ELAVON` - **The Elavon processor.**
     * - `FIRSTDATA` - **The First Data processor.**
     * - `GOOGLE` - **The Google Payment Processor.**
     * - `VANTIV` - **The WorldPay (aka Vantiv or Litle) eComm (aka VAP) processor.**
     * - `VCORE` - **The WorldPay (aka Vantiv) Core processor.**
     * - `WELLSACH` - **The Wells Fargo ACH processor.**
     * - `WELLSFARGO` - **The Wells Fargo Merchant Services processor.**
     * - `WFSINGLE` - **The WFSINGLE processor.**
     * - `WORLDPAY` - **The WORLDPAY processor.**
     * - `TDBANKCA` - **External funding with TD Bank Canada via the Operating Account.**
     * - `all` - **All Platform Processor.**
     *
     * </details>
     *
     * @maps platform
     * @factory \PayrixLib\Models\FundingParameterPlatformEnum::checkValue
     */
    public function setPlatform(?string $platform): void
    {
        $this->platform = $platform;
    }

    /**
     * Returns Type.
     * The type of fundingParameter that we will be configuring.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `agentCnp` - **The id to use for boarding merchants that are card not present**
     * - `agentCp` - **The id to use for boarding merchants that are card present**
     * - `creditCompanyId` - **Company credit identifier**
     * - `debitCompanyId` - **Company debit identifier**
     * - `delay` - **Delay**
     * - `offDaysAdditionalDelay` - **Additional delay for off days.**
     * - `settlementAccountTransferDelay` - **The amount of time in days to wait before issuing a transfer,
     * will be counted from the date of the first item within the total settlement amount.**
     * - `settlementAccountTransferEnabled` - **Indication if during settlements credits should be
     * transferred from the merchant's operating account.**
     * - `settlementAccountTransferFloat` - **Additional amount to keep at the merchant's operating account.
     * **
     * - `settlementAccountTransferMaximum` - **The maximum amount needed to transfer funds from merchant's
     * operating account.**
     * - `settlementAccountTransferMinimum` - **The minimum amount needed to transfer funds from the
     * merchant's operating account.**
     * - `settlementAccountTransferPercent` - **The percent amount to transfer from the total settlement
     * amount.**
     * - `customBatchCloseTime` - **The specified time to close a batch**
     * - `lateFunding` - **2 am late funding cutoff time**
     * - `5AmFunding` - **5 am funding cutoff time**
     *
     * </details>
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of fundingParameter that we will be configuring.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `agentCnp` - **The id to use for boarding merchants that are card not present**
     * - `agentCp` - **The id to use for boarding merchants that are card present**
     * - `creditCompanyId` - **Company credit identifier**
     * - `debitCompanyId` - **Company debit identifier**
     * - `delay` - **Delay**
     * - `offDaysAdditionalDelay` - **Additional delay for off days.**
     * - `settlementAccountTransferDelay` - **The amount of time in days to wait before issuing a transfer,
     * will be counted from the date of the first item within the total settlement amount.**
     * - `settlementAccountTransferEnabled` - **Indication if during settlements credits should be
     * transferred from the merchant's operating account.**
     * - `settlementAccountTransferFloat` - **Additional amount to keep at the merchant's operating account.
     * **
     * - `settlementAccountTransferMaximum` - **The maximum amount needed to transfer funds from merchant's
     * operating account.**
     * - `settlementAccountTransferMinimum` - **The minimum amount needed to transfer funds from the
     * merchant's operating account.**
     * - `settlementAccountTransferPercent` - **The percent amount to transfer from the total settlement
     * amount.**
     * - `customBatchCloseTime` - **The specified time to close a batch**
     * - `lateFunding` - **2 am late funding cutoff time**
     * - `5AmFunding` - **5 am funding cutoff time**
     *
     * </details>
     *
     * @maps type
     * @factory \PayrixLib\Models\FundingParameterTypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Value.
     * The value of this type of fundingParameter.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * The value of this type of fundingParameter.
     *
     * @maps value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Returns Payment Methods.
     * The payment methods that the fundingParameter should apply to.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `amex` - **American Express**
     * - `visa` - **Visa**
     * - `masterCard` - **MasterCard**
     * - `diners` - **Diners Club**
     * - `discover` - **Discover**
     * - `paypal` - **PayPal**
     * - `debit` - **Debit**
     * - `checking` - **Personal checking**
     * - `savings` - **Personal savings**
     * - `corpChecking` - **Corporate checking**
     * - `corpSavings` - **Corporate savings**
     * - `gift` - **Gift card**
     * - `ebt` - **EBT (Electronic Benefits Transfer)**
     * - `wic` - **WIC (Women, Infants and Children)**
     *
     * </details>
     */
    public function getPaymentMethods(): ?string
    {
        return $this->paymentMethods;
    }

    /**
     * Sets Payment Methods.
     * The payment methods that the fundingParameter should apply to.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `amex` - **American Express**
     * - `visa` - **Visa**
     * - `masterCard` - **MasterCard**
     * - `diners` - **Diners Club**
     * - `discover` - **Discover**
     * - `paypal` - **PayPal**
     * - `debit` - **Debit**
     * - `checking` - **Personal checking**
     * - `savings` - **Personal savings**
     * - `corpChecking` - **Corporate checking**
     * - `corpSavings` - **Corporate savings**
     * - `gift` - **Gift card**
     * - `ebt` - **EBT (Electronic Benefits Transfer)**
     * - `wic` - **WIC (Women, Infants and Children)**
     *
     * </details>
     *
     * @maps paymentMethods
     * @factory \PayrixLib\Models\FundingParameterPaymentMethodsEnum::checkValue
     */
    public function setPaymentMethods(?string $paymentMethods): void
    {
        $this->paymentMethods = $paymentMethods;
    }

    /**
     * Returns Locked.
     * Whether this fundingParameter is locked or not.
     * If it is locked, then the value of this type of fundingParameter will prevail.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **OFF**
     * - `1` - **ON**
     *
     * </details>
     */
    public function getLocked(): ?int
    {
        return $this->locked;
    }

    /**
     * Sets Locked.
     * Whether this fundingParameter is locked or not.
     * If it is locked, then the value of this type of fundingParameter will prevail.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **OFF**
     * - `1` - **ON**
     *
     * </details>
     *
     * @maps locked
     * @factory \PayrixLib\Models\FundingParameterLockedEnum::checkValue
     */
    public function setLocked(?int $locked): void
    {
        $this->locked = $locked;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Converts the FundingParametersResponse object to a human-readable string representation.
     *
     * @return string The string representation of the FundingParametersResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FundingParametersResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'login' => $this->login,
                'entity' => $this->entity,
                'org' => $this->org,
                'division' => $this->division,
                'partition' => $this->partition,
                'platform' => $this->platform,
                'type' => $this->type,
                'value' => $this->value,
                'paymentMethods' => $this->paymentMethods,
                'locked' => $this->locked,
                'inactive' => $this->inactive,
                'frozen' => $this->frozen
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']             = $this->id;
        }
        if (isset($this->created)) {
            $json['created']        = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']       = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']        =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']       = $this->modifier;
        }
        if (isset($this->login)) {
            $json['login']          =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->login,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->entity)) {
            $json['entity']         =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->entity,
                    'anyOf(anyOf(string,EntitiesResponse),null)'
                );
        }
        if (isset($this->org)) {
            $json['org']            =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->org,
                    'anyOf(anyOf(string,OrgsResponse),null)'
                );
        }
        if (isset($this->division)) {
            $json['division']       =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->division,
                    'anyOf(anyOf(string,DivisionsResponse),null)'
                );
        }
        if (isset($this->partition)) {
            $json['partition']      =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->partition,
                    'anyOf(anyOf(string,PartitionsResponse),null)'
                );
        }
        if (isset($this->platform)) {
            $json['platform']       = FundingParameterPlatformEnum::checkValue($this->platform);
        }
        if (isset($this->type)) {
            $json['type']           = FundingParameterTypeEnum::checkValue($this->type);
        }
        if (isset($this->value)) {
            $json['value']          = $this->value;
        }
        if (isset($this->paymentMethods)) {
            $json['paymentMethods'] = FundingParameterPaymentMethodsEnum::checkValue($this->paymentMethods);
        }
        if (isset($this->locked)) {
            $json['locked']         = FundingParameterLockedEnum::checkValue($this->locked);
        }
        if (isset($this->inactive)) {
            $json['inactive']       = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']         = FrozenEnum::checkValue($this->frozen);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
