<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class InvoiceLineItemsPutRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $invoice;

    /**
     * @var string|null
     */
    private $invoiceItem;

    /**
     * @var int|null
     */
    private $quantity;

    /**
     * @var int|null
     */
    private $price;

    /**
     * @var int|null
     */
    private $discount;

    /**
     * Returns Invoice.
     * The identifier of the Invoice that owns this InvoiceLineItem.
     */
    public function getInvoice(): ?string
    {
        return $this->invoice;
    }

    /**
     * Sets Invoice.
     * The identifier of the Invoice that owns this InvoiceLineItem.
     *
     * @maps invoice
     */
    public function setInvoice(?string $invoice): void
    {
        $this->invoice = $invoice;
    }

    /**
     * Returns Invoice Item.
     * The identifier of the InvoiceItem associated with this InvoiceLineItem.
     */
    public function getInvoiceItem(): ?string
    {
        return $this->invoiceItem;
    }

    /**
     * Sets Invoice Item.
     * The identifier of the InvoiceItem associated with this InvoiceLineItem.
     *
     * @maps invoiceItem
     */
    public function setInvoiceItem(?string $invoiceItem): void
    {
        $this->invoiceItem = $invoiceItem;
    }

    /**
     * Returns Quantity.
     * The quantity purchased for this line item, specified as an integer.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * The quantity purchased for this line item, specified as an integer.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Price.
     * The price for each item, this field is specified as an integer in cents.
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * Sets Price.
     * The price for each item, this field is specified as an integer in cents.
     *
     * @maps price
     */
    public function setPrice(?int $price): void
    {
        $this->price = $price;
    }

    /**
     * Returns Discount.
     * The discount for the line item, this field is specified as an integer in cents.
     */
    public function getDiscount(): ?int
    {
        return $this->discount;
    }

    /**
     * Sets Discount.
     * The discount for the line item, this field is specified as an integer in cents.
     *
     * @maps discount
     */
    public function setDiscount(?int $discount): void
    {
        $this->discount = $discount;
    }

    /**
     * Converts the InvoiceLineItemsPutRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InvoiceLineItemsPutRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InvoiceLineItemsPutRequest',
            [
                'invoice' => $this->invoice,
                'invoiceItem' => $this->invoiceItem,
                'quantity' => $this->quantity,
                'price' => $this->price,
                'discount' => $this->discount
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->invoice)) {
            $json['invoice']     = $this->invoice;
        }
        if (isset($this->invoiceItem)) {
            $json['invoiceItem'] = $this->invoiceItem;
        }
        if (isset($this->quantity)) {
            $json['quantity']    = $this->quantity;
        }
        if (isset($this->price)) {
            $json['price']       = $this->price;
        }
        if (isset($this->discount)) {
            $json['discount']    = $this->discount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
