<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class InvoiceLineItemsPostRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $invoice;

    /**
     * @var string
     */
    private $invoiceItem;

    /**
     * @var int|null
     */
    private $quantity = 1;

    /**
     * @var array
     */
    private $price = [];

    /**
     * @var array
     */
    private $discount = [];

    /**
     * @param string $invoice
     * @param string $invoiceItem
     */
    public function __construct(string $invoice, string $invoiceItem)
    {
        $this->invoice = $invoice;
        $this->invoiceItem = $invoiceItem;
    }

    /**
     * Returns Invoice.
     * The identifier of the Invoice that owns this InvoiceLineItem.
     */
    public function getInvoice(): string
    {
        return $this->invoice;
    }

    /**
     * Sets Invoice.
     * The identifier of the Invoice that owns this InvoiceLineItem.
     *
     * @required
     * @maps invoice
     */
    public function setInvoice(string $invoice): void
    {
        $this->invoice = $invoice;
    }

    /**
     * Returns Invoice Item.
     * The identifier of the InvoiceItem associated with this InvoiceLineItem.
     */
    public function getInvoiceItem(): string
    {
        return $this->invoiceItem;
    }

    /**
     * Sets Invoice Item.
     * The identifier of the InvoiceItem associated with this InvoiceLineItem.
     *
     * @required
     * @maps invoiceItem
     */
    public function setInvoiceItem(string $invoiceItem): void
    {
        $this->invoiceItem = $invoiceItem;
    }

    /**
     * Returns Quantity.
     * The quantity purchased for this line item, specified as an integer.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * The quantity purchased for this line item, specified as an integer.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Price.
     * The price for each item, this field is specified as an integer in cents.
     */
    public function getPrice(): ?int
    {
        if (count($this->price) == 0) {
            return null;
        }
        return $this->price['value'];
    }

    /**
     * Sets Price.
     * The price for each item, this field is specified as an integer in cents.
     *
     * @maps price
     */
    public function setPrice(?int $price): void
    {
        $this->price['value'] = $price;
    }

    /**
     * Unsets Price.
     * The price for each item, this field is specified as an integer in cents.
     */
    public function unsetPrice(): void
    {
        $this->price = [];
    }

    /**
     * Returns Discount.
     * The discount for the line item, this field is specified as an integer in cents.
     */
    public function getDiscount(): ?int
    {
        if (count($this->discount) == 0) {
            return null;
        }
        return $this->discount['value'];
    }

    /**
     * Sets Discount.
     * The discount for the line item, this field is specified as an integer in cents.
     *
     * @maps discount
     */
    public function setDiscount(?int $discount): void
    {
        $this->discount['value'] = $discount;
    }

    /**
     * Unsets Discount.
     * The discount for the line item, this field is specified as an integer in cents.
     */
    public function unsetDiscount(): void
    {
        $this->discount = [];
    }

    /**
     * Converts the InvoiceLineItemsPostRequest object to a human-readable string representation.
     *
     * @return string The string representation of the InvoiceLineItemsPostRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InvoiceLineItemsPostRequest',
            [
                'invoice' => $this->invoice,
                'invoiceItem' => $this->invoiceItem,
                'quantity' => $this->quantity,
                'price' => $this->getPrice(),
                'discount' => $this->getDiscount()
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['invoice']      = $this->invoice;
        $json['invoiceItem']  = $this->invoiceItem;
        if (isset($this->quantity)) {
            $json['quantity'] = $this->quantity;
        }
        if (!empty($this->price)) {
            $json['price']    = $this->price['value'];
        }
        if (!empty($this->discount)) {
            $json['discount'] = $this->discount['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
