<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class InvoiceLineItemsResponseResult implements \JsonSerializable
{
    /**
     * @var InvoiceLineItemsResponseItem|null
     */
    private $response;

    /**
     * Returns Response.
     */
    public function getResponse(): ?InvoiceLineItemsResponseItem
    {
        return $this->response;
    }

    /**
     * Sets Response.
     *
     * @maps response
     */
    public function setResponse(?InvoiceLineItemsResponseItem $response): void
    {
        $this->response = $response;
    }

    /**
     * Converts the InvoiceLineItemsResponseResult object to a human-readable string representation.
     *
     * @return string The string representation of the InvoiceLineItemsResponseResult object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('InvoiceLineItemsResponseResult', ['response' => $this->response]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->response)) {
            $json['response'] = $this->response;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
