<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class MerchantsNaicsEnum
{
    /**
     * Agriculture, Forestry, Fishing and Hunting
     */
    public const AGRICULTURE = '11';

    /**
     * Mining, Quarrying, and Oil and Gas Extraction
     */
    public const MINING = '21';

    /**
     * Utilities
     */
    public const UTILITIES = '22';

    /**
     * Construction
     */
    public const CONSTRUCTION = '23';

    /**
     * Manufacturing
     */
    public const MANUFACTURING = '31-33';

    /**
     * Wholesale Trade
     */
    public const WHOLESALETRADE = '41';

    /**
     * Retail Trade
     */
    public const RETAILTRADE = '44-45';

    /**
     * Transportation and Warehousing
     */
    public const TRANSPORTATIONWAREHOUSING = '48-49';

    /**
     * Information
     */
    public const INFORMATION = '51';

    /**
     * Finance and Insurance
     */
    public const FINANCEINSURANCE = '52';

    /**
     * Real Estate and Property Rental / Leasing
     */
    public const REALESTATE = '53';

    /**
     * Professional, Scientific, and Technical Services
     */
    public const PROFESSIONALSERVICES = '54';

    /**
     * Management of Companies and Enterprises
     */
    public const MANAGEMENT = '55';

    /**
     * Administrative and Support and Waste Management and Remediation Services
     */
    public const ADMINISTRATIVESUPPORT = '56';

    /**
     * Educational Services
     */
    public const EDUCATIONALSERVICES = '61';

    /**
     * Health Care and Social Assistance
     */
    public const HEALTHCARE = '62';

    /**
     * Arts, Entertainment, and Recreation
     */
    public const ARTSENTERTAINMENT = '71';

    /**
     * Accommodation and Food Services
     */
    public const ACCOMMODATIONFOOD = '72';

    /**
     * Other Services (except Public Administration)
     */
    public const OTHERSERVICES = '81';

    /**
     * Public Administration
     */
    public const PUBLICADMINISTRATION = '91/92';

    private const _ALL_VALUES = [
        self::AGRICULTURE,
        self::MINING,
        self::UTILITIES,
        self::CONSTRUCTION,
        self::MANUFACTURING,
        self::WHOLESALETRADE,
        self::RETAILTRADE,
        self::TRANSPORTATIONWAREHOUSING,
        self::INFORMATION,
        self::FINANCEINSURANCE,
        self::REALESTATE,
        self::PROFESSIONALSERVICES,
        self::MANAGEMENT,
        self::ADMINISTRATIVESUPPORT,
        self::EDUCATIONALSERVICES,
        self::HEALTHCARE,
        self::ARTSENTERTAINMENT,
        self::ACCOMMODATIONFOOD,
        self::OTHERSERVICES,
        self::PUBLICADMINISTRATION
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for MerchantsNaicsEnum.");
    }
}
