<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class MerchantEnvironmentEnum
{
    /**
     * Supermarkets / Grocery.
     */
    public const SUPERMARKET = 'supermarket';

    /**
     * Mail Order / Telephone Order.
     */
    public const MOTO = 'moto';

    /**
     * Card Present Environment.
     */
    public const CARDPRESENT = 'cardPresent';

    /**
     * Fuel / Gas Stations.
     */
    public const FUEL = 'fuel';

    /**
     * Service Stations.
     */
    public const SERVICESTATION = 'serviceStation';

    /**
     * Restaurants.
     */
    public const RESTAURANT = 'restaurant';

    /**
     * eCommerce / Online Sales.
     */
    public const ECOMMERCE = 'ecommerce';

    private const _ALL_VALUES = [
        self::SUPERMARKET,
        self::MOTO,
        self::CARDPRESENT,
        self::FUEL,
        self::SERVICESTATION,
        self::RESTAURANT,
        self::ECOMMERCE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for MerchantEnvironmentEnum.");
    }
}
