<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class MerchantResultsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|null
     */
    private $merchant;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $platform;

    /**
     * @var string|null
     */
    private $message;

    /**
     * @var string|null
     */
    private $boardingProcessID;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Merchant.
     * The merchant associated with this merchant result.
     */
    public function getMerchant(): ?string
    {
        return $this->merchant;
    }

    /**
     * Sets Merchant.
     * The merchant associated with this merchant result.
     *
     * @maps merchant
     */
    public function setMerchant(?string $merchant): void
    {
        $this->merchant = $merchant;
    }

    /**
     * Returns Type.
     * The type of this merchant result
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `general` - **General use for unspecified type.**
     * - `internal` - **An internal failure result message.**
     * - `data` - **Missing merchant boarding related data failure message.**
     * - `legal` - **Result message related to legal matters.**
     * - `denial` - **Merchant boarding denial result message.**
     * - `platform` - **Processor boarding failure result message.**
     * - `platformNote` - **Processor note from merchant boarding.**
     *
     * </details>
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of this merchant result
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `general` - **General use for unspecified type.**
     * - `internal` - **An internal failure result message.**
     * - `data` - **Missing merchant boarding related data failure message.**
     * - `legal` - **Result message related to legal matters.**
     * - `denial` - **Merchant boarding denial result message.**
     * - `platform` - **Processor boarding failure result message.**
     * - `platformNote` - **Processor note from merchant boarding.**
     *
     * </details>
     *
     * @maps type
     * @factory \PayrixLib\Models\MerchantTypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Platform.
     * The platform used to process this resource.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `APPLE` - **The Apple Payment Processor.**
     * - `ELAVON` - **The Elavon processor.**
     * - `FIRSTDATA` - **The FirstData processor.**
     * - `GOOGLE` - **The Google Payment Processor.**
     * - `VANTIV` - **The WorldPay (aka Vantiv or Litle) eComm (aka VAP) processor.**
     * - `VCORE` - **The WorldPay (aka Vantiv) Core processor.**
     * - `TDBANKCA` - **External funding with TD Bank Canada via the Operating Account.**
     * - `WELLSACH` - **The Wells Fargo ACH processor.**
     * - `WELLSFARGO` - **The Wells Fargo Merchant Services processor.**
     * - `WFSINGLE` - **The WFSINGLE processor.**
     * - `WORLDPAY` - **The WORLDPAY processor.**
     *
     * </details>
     */
    public function getPlatform(): ?string
    {
        return $this->platform;
    }

    /**
     * Sets Platform.
     * The platform used to process this resource.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `APPLE` - **The Apple Payment Processor.**
     * - `ELAVON` - **The Elavon processor.**
     * - `FIRSTDATA` - **The FirstData processor.**
     * - `GOOGLE` - **The Google Payment Processor.**
     * - `VANTIV` - **The WorldPay (aka Vantiv or Litle) eComm (aka VAP) processor.**
     * - `VCORE` - **The WorldPay (aka Vantiv) Core processor.**
     * - `TDBANKCA` - **External funding with TD Bank Canada via the Operating Account.**
     * - `WELLSACH` - **The Wells Fargo ACH processor.**
     * - `WELLSFARGO` - **The Wells Fargo Merchant Services processor.**
     * - `WFSINGLE` - **The WFSINGLE processor.**
     * - `WORLDPAY` - **The WORLDPAY processor.**
     *
     * </details>
     *
     * @maps platform
     * @factory \PayrixLib\Models\PlatformModelEnum::checkValue
     */
    public function setPlatform(?string $platform): void
    {
        $this->platform = $platform;
    }

    /**
     * Returns Message.
     * The message of this merchant result.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * The message of this merchant result.
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Boarding Process ID.
     * Unique identification number that refers merchant.
     */
    public function getBoardingProcessID(): ?string
    {
        return $this->boardingProcessID;
    }

    /**
     * Sets Boarding Process ID.
     * Unique identification number that refers merchant.
     *
     * @maps boardingProcessID
     */
    public function setBoardingProcessID(?string $boardingProcessID): void
    {
        $this->boardingProcessID = $boardingProcessID;
    }

    /**
     * Converts the MerchantResultsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the MerchantResultsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MerchantResultsResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'merchant' => $this->merchant,
                'type' => $this->type,
                'platform' => $this->platform,
                'message' => $this->message,
                'boardingProcessID' => $this->boardingProcessID
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                = $this->id;
        }
        if (isset($this->created)) {
            $json['created']           = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']          = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']           =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']          = $this->modifier;
        }
        if (isset($this->merchant)) {
            $json['merchant']          = $this->merchant;
        }
        if (isset($this->type)) {
            $json['type']              = MerchantTypeEnum::checkValue($this->type);
        }
        if (isset($this->platform)) {
            $json['platform']          = PlatformModelEnum::checkValue($this->platform);
        }
        if (isset($this->message)) {
            $json['message']           = $this->message;
        }
        if (isset($this->boardingProcessID)) {
            $json['boardingProcessID'] = $this->boardingProcessID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
