<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class MerchantsSaqTypeEnum
{
    /**
     * Card-not-present merchants (e-commerce or mail/telephone-order) with PCI DSS-validated third-party
     * payments service provider(s) and does not store cardholder data.
     */
    public const SAQA = 'SAQ-A';

    /**
     * E-commerce merchants with PCI DSS-validated third-party payments service provider(s) with a website
     * that doesn't directly collect cardholder data, but may impact it in some way, and does not store
     * cardholder data.
     */
    public const SAQAEP = 'SAQ-A-EP';

    /**
     * Merchants with imprint machines or standalone, dial-out terminals that do not store cardholder data.
     */
    public const SAQB = 'SAQ-B';

    /**
     * Merchants with standalone, PTS-approved payment terminals that have an IP connection to the payment
     * processor, but do not store cardholder data.
     */
    public const SAQBIP = 'SAQ-B-IP';

    /**
     * Merchants that enter single transactions manually into an internet-based terminal hosted by PCI DSS-
     * validated third-party payments service provider(s) and does not store cardholder data.
     */
    public const SAQCVT = 'SAQ-C-VT';

    /**
     * Merchants with payment application systems connected to the internet that do not store cardholder
     * data.
     */
    public const SAQC = 'SAQ-C';

    /**
     * Merchants with hardware-only payment terminals managed by a PCI SSC-listed P2PE solution, and does
     * not store cardholder data.
     */
    public const SAQP2PEHW = 'SAQ-P2PE-HW';

    /**
     * Generic field for all Merchants that do not fall under the requirements for any above SAQ types.
     */
    public const SAQD = 'SAQ-D';

    private const _ALL_VALUES =
        [self::SAQA, self::SAQAEP, self::SAQB, self::SAQBIP, self::SAQCVT, self::SAQC, self::SAQP2PEHW, self::SAQD];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for MerchantsSaqTypeEnum.");
    }
}
