<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class MessageThreadsPutRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $login;

    /**
     * @var string|null
     */
    private $forlogin;

    /**
     * @var string|null
     */
    private $hold;

    /**
     * @var string|null
     */
    private $entityReturn;

    /**
     * @var string|null
     */
    private $opposingMessageThread;

    /**
     * @var string|null
     */
    private $folder;

    /**
     * @var string|null
     */
    private $sender;

    /**
     * @var string|null
     */
    private $recipient;

    /**
     * @var string|null
     */
    private $subject;

    /**
     * Returns Login.
     * The identifier of the Login that owns this messageThreads resource.
     */
    public function getLogin(): ?string
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The identifier of the Login that owns this messageThreads resource.
     *
     * @maps login
     */
    public function setLogin(?string $login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Forlogin.
     * The identifier of the receiving Login of this messageThreads resource.
     */
    public function getForlogin(): ?string
    {
        return $this->forlogin;
    }

    /**
     * Sets Forlogin.
     * The identifier of the receiving Login of this messageThreads resource.
     *
     * @maps forlogin
     */
    public function setForlogin(?string $forlogin): void
    {
        $this->forlogin = $forlogin;
    }

    /**
     * Returns Hold.
     * The identifier of the Hold that is related to this messageThread.
     */
    public function getHold(): ?string
    {
        return $this->hold;
    }

    /**
     * Sets Hold.
     * The identifier of the Hold that is related to this messageThread.
     *
     * @maps hold
     */
    public function setHold(?string $hold): void
    {
        $this->hold = $hold;
    }

    /**
     * Returns Entity Return.
     * This field has the ID from the EntityReturns table that hold ACH returns for disbursements or eCheck
     * txns.
     */
    public function getEntityReturn(): ?string
    {
        return $this->entityReturn;
    }

    /**
     * Sets Entity Return.
     * This field has the ID from the EntityReturns table that hold ACH returns for disbursements or eCheck
     * txns.
     *
     * @maps entityReturn
     */
    public function setEntityReturn(?string $entityReturn): void
    {
        $this->entityReturn = $entityReturn;
    }

    /**
     * Returns Opposing Message Thread.
     * Specifies whether this is the opposing MessageThread.
     */
    public function getOpposingMessageThread(): ?string
    {
        return $this->opposingMessageThread;
    }

    /**
     * Sets Opposing Message Thread.
     * Specifies whether this is the opposing MessageThread.
     *
     * @maps opposingMessageThread
     */
    public function setOpposingMessageThread(?string $opposingMessageThread): void
    {
        $this->opposingMessageThread = $opposingMessageThread;
    }

    /**
     * Returns Folder.
     * Free-form text. By default, a messageThread resource is set as 'default'.
     */
    public function getFolder(): ?string
    {
        return $this->folder;
    }

    /**
     * Sets Folder.
     * Free-form text. By default, a messageThread resource is set as 'default'.
     *
     * @maps folder
     */
    public function setFolder(?string $folder): void
    {
        $this->folder = $folder;
    }

    /**
     * Returns Sender.
     * Free-form text that represents the name of the sender of a messageThread resource.
     */
    public function getSender(): ?string
    {
        return $this->sender;
    }

    /**
     * Sets Sender.
     * Free-form text that represents the name of the sender of a messageThread resource.
     *
     * @maps sender
     */
    public function setSender(?string $sender): void
    {
        $this->sender = $sender;
    }

    /**
     * Returns Recipient.
     * Free-form text that represents the name of the recipient of a messageThread resource.
     */
    public function getRecipient(): ?string
    {
        return $this->recipient;
    }

    /**
     * Sets Recipient.
     * Free-form text that represents the name of the recipient of a messageThread resource.
     *
     * @maps recipient
     */
    public function setRecipient(?string $recipient): void
    {
        $this->recipient = $recipient;
    }

    /**
     * Returns Subject.
     * Free-form text for adding a subject to a messageThread resource.
     */
    public function getSubject(): ?string
    {
        return $this->subject;
    }

    /**
     * Sets Subject.
     * Free-form text for adding a subject to a messageThread resource.
     *
     * @maps subject
     */
    public function setSubject(?string $subject): void
    {
        $this->subject = $subject;
    }

    /**
     * Converts the MessageThreadsPutRequest object to a human-readable string representation.
     *
     * @return string The string representation of the MessageThreadsPutRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MessageThreadsPutRequest',
            [
                'login' => $this->login,
                'forlogin' => $this->forlogin,
                'hold' => $this->hold,
                'entityReturn' => $this->entityReturn,
                'opposingMessageThread' => $this->opposingMessageThread,
                'folder' => $this->folder,
                'sender' => $this->sender,
                'recipient' => $this->recipient,
                'subject' => $this->subject
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->login)) {
            $json['login']                 = $this->login;
        }
        if (isset($this->forlogin)) {
            $json['forlogin']              = $this->forlogin;
        }
        if (isset($this->hold)) {
            $json['hold']                  = $this->hold;
        }
        if (isset($this->entityReturn)) {
            $json['entityReturn']          = $this->entityReturn;
        }
        if (isset($this->opposingMessageThread)) {
            $json['opposingMessageThread'] = $this->opposingMessageThread;
        }
        if (isset($this->folder)) {
            $json['folder']                = $this->folder;
        }
        if (isset($this->sender)) {
            $json['sender']                = $this->sender;
        }
        if (isset($this->recipient)) {
            $json['recipient']             = $this->recipient;
        }
        if (isset($this->subject)) {
            $json['subject']               = $this->subject;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
