<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class ReservesPutRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $login;

    /**
     * @var string|null
     */
    private $org;

    /**
     * @var string|null
     */
    private $division;

    /**
     * @var string|null
     */
    private $partition;

    /**
     * @var string|null
     */
    private $level;

    /**
     * @var string|null
     */
    private $entity;

    /**
     * @var string|null
     */
    private $hold;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var int|null
     */
    private $percent;

    /**
     * @var string|null
     */
    private $release;

    /**
     * @var int|null
     */
    private $releaseFactor;

    /**
     * @var int|null
     */
    private $start;

    /**
     * @var int|null
     */
    private $finish;

    /**
     * @var int|null
     */
    private $max;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * Returns Login.
     * The Login that owns this resource.
     */
    public function getLogin(): ?string
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The Login that owns this resource.
     *
     * @maps login
     */
    public function setLogin(?string $login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Org.
     * The identifier of the Org that this Reserve's resource applies to. If you set this field, then the
     * Reserve applies to all Entities in the Org.
     */
    public function getOrg(): ?string
    {
        return $this->org;
    }

    /**
     * Sets Org.
     * The identifier of the Org that this Reserve's resource applies to. If you set this field, then the
     * Reserve applies to all Entities in the Org.
     *
     * @maps org
     */
    public function setOrg(?string $org): void
    {
        $this->org = $org;
    }

    /**
     * Returns Division.
     * The division on which this reserve applies.
     */
    public function getDivision(): ?string
    {
        return $this->division;
    }

    /**
     * Sets Division.
     * The division on which this reserve applies.
     *
     * @maps division
     */
    public function setDivision(?string $division): void
    {
        $this->division = $division;
    }

    /**
     * Returns Partition.
     * The partition on which this reserve applies.
     */
    public function getPartition(): ?string
    {
        return $this->partition;
    }

    /**
     * Sets Partition.
     * The partition on which this reserve applies.
     *
     * @maps partition
     */
    public function setPartition(?string $partition): void
    {
        $this->partition = $partition;
    }

    /**
     * Returns Level.
     * The hierarchical level for this reserve setting.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `admin` - **Admin User.**
     * - `division` - **Division-level User.**
     * - `merchant` - **Merchant-level User.**
     * - `partition` - **Partition-level User.**
     *
     * </details>
     */
    public function getLevel(): ?string
    {
        return $this->level;
    }

    /**
     * Sets Level.
     * The hierarchical level for this reserve setting.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `admin` - **Admin User.**
     * - `division` - **Division-level User.**
     * - `merchant` - **Merchant-level User.**
     * - `partition` - **Partition-level User.**
     *
     * </details>
     *
     * @maps level
     * @factory \PayrixLib\Models\ReservesLevelEnum::checkValue
     */
    public function setLevel(?string $level): void
    {
        $this->level = $level;
    }

    /**
     * Returns Entity.
     * The identifier of the Entity that this Reserve applies to.
     */
    public function getEntity(): ?string
    {
        return $this->entity;
    }

    /**
     * Sets Entity.
     * The identifier of the Entity that this Reserve applies to.
     *
     * @maps entity
     */
    public function setEntity(?string $entity): void
    {
        $this->entity = $entity;
    }

    /**
     * Returns Hold.
     * The entity hold from which this reserve was generated.
     */
    public function getHold(): ?string
    {
        return $this->hold;
    }

    /**
     * Sets Hold.
     * The entity hold from which this reserve was generated.
     *
     * @maps hold
     */
    public function setHold(?string $hold): void
    {
        $this->hold = $hold;
    }

    /**
     * Returns Name.
     * The name of this Reserve. This field is stored as a text string and must be between 1 and 100
     * characters long.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of this Reserve. This field is stored as a text string and must be between 1 and 100
     * characters long.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Description.
     * A description of this Reserve. This field is stored as a text string and must be between 0 and 100
     * characters long.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * A description of this Reserve. This field is stored as a text string and must be between 0 and 100
     * characters long.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Percent.
     * The percentage of funds to reserve, expressed in basis points. For example, 25.3% is expressed as
     * '2530'.
     */
    public function getPercent(): ?int
    {
        return $this->percent;
    }

    /**
     * Sets Percent.
     * The percentage of funds to reserve, expressed in basis points. For example, 25.3% is expressed as
     * '2530'.
     *
     * @maps percent
     */
    public function setPercent(?int $percent): void
    {
        $this->percent = $percent;
    }

    /**
     * Returns Release.
     * The schedule that determines when the funds in this Reserve should be released, which can have valid
     * values such as never, days, weeks, months, or years.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `never` - **Never.**
     * - `days` - **Daily. The funds are released every day.**
     * - `weeks` - **Weekly. The funds are released every week.**
     * - `months` - **Monthly. The funds are released every month.**
     * - `years` - **Annually. The funds are released every year.**
     *
     * </details>
     */
    public function getRelease(): ?string
    {
        return $this->release;
    }

    /**
     * Sets Release.
     * The schedule that determines when the funds in this Reserve should be released, which can have valid
     * values such as never, days, weeks, months, or years.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `never` - **Never.**
     * - `days` - **Daily. The funds are released every day.**
     * - `weeks` - **Weekly. The funds are released every week.**
     * - `months` - **Monthly. The funds are released every month.**
     * - `years` - **Annually. The funds are released every year.**
     *
     * </details>
     *
     * @maps release
     * @factory \PayrixLib\Models\ReservesReleaseEnum::checkValue
     */
    public function setRelease(?string $release): void
    {
        $this->release = $release;
    }

    /**
     * Returns Release Factor.
     * A multiplier that you can use to adjust the schedule set in the 'release' field, which is specified
     * as an integer and its value determines how the schedule is multiplied.
     */
    public function getReleaseFactor(): ?int
    {
        return $this->releaseFactor;
    }

    /**
     * Sets Release Factor.
     * A multiplier that you can use to adjust the schedule set in the 'release' field, which is specified
     * as an integer and its value determines how the schedule is multiplied.
     *
     * @maps releaseFactor
     */
    public function setReleaseFactor(?int $releaseFactor): void
    {
        $this->releaseFactor = $releaseFactor;
    }

    /**
     * Returns Start.
     * The date on which this Reserve resource should start reserving funds from the Entity or Org. The
     * date is specified as an eight digit string in YYYYMMDD format, for example, '20160120' for January
     * 20, 2016.
     */
    public function getStart(): ?int
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * The date on which this Reserve resource should start reserving funds from the Entity or Org. The
     * date is specified as an eight digit string in YYYYMMDD format, for example, '20160120' for January
     * 20, 2016.
     *
     * @maps start
     */
    public function setStart(?int $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns Finish.
     * The date on which this Reserve resource should stop reserving funds from the Entity or Org. The date
     * is specified as an eight digit string in YYYYMMDD format, for example, '20160120' for January 20,
     * 2016.
     */
    public function getFinish(): ?int
    {
        return $this->finish;
    }

    /**
     * Sets Finish.
     * The date on which this Reserve resource should stop reserving funds from the Entity or Org. The date
     * is specified as an eight digit string in YYYYMMDD format, for example, '20160120' for January 20,
     * 2016.
     *
     * @maps finish
     */
    public function setFinish(?int $finish): void
    {
        $this->finish = $finish;
    }

    /**
     * Returns Max.
     * The maximum amount to reserve.
     */
    public function getMax(): ?int
    {
        return $this->max;
    }

    /**
     * Sets Max.
     * The maximum amount to reserve.
     *
     * @maps max
     */
    public function setMax(?int $max): void
    {
        $this->max = $max;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Converts the ReservesPutRequest object to a human-readable string representation.
     *
     * @return string The string representation of the ReservesPutRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ReservesPutRequest',
            [
                'login' => $this->login,
                'org' => $this->org,
                'division' => $this->division,
                'partition' => $this->partition,
                'level' => $this->level,
                'entity' => $this->entity,
                'hold' => $this->hold,
                'name' => $this->name,
                'description' => $this->description,
                'percent' => $this->percent,
                'release' => $this->release,
                'releaseFactor' => $this->releaseFactor,
                'start' => $this->start,
                'finish' => $this->finish,
                'max' => $this->max,
                'inactive' => $this->inactive,
                'frozen' => $this->frozen
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->login)) {
            $json['login']         = $this->login;
        }
        if (isset($this->org)) {
            $json['org']           = $this->org;
        }
        if (isset($this->division)) {
            $json['division']      = $this->division;
        }
        if (isset($this->partition)) {
            $json['partition']     = $this->partition;
        }
        if (isset($this->level)) {
            $json['level']         = ReservesLevelEnum::checkValue($this->level);
        }
        if (isset($this->entity)) {
            $json['entity']        = $this->entity;
        }
        if (isset($this->hold)) {
            $json['hold']          = $this->hold;
        }
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        if (isset($this->description)) {
            $json['description']   = $this->description;
        }
        if (isset($this->percent)) {
            $json['percent']       = $this->percent;
        }
        if (isset($this->release)) {
            $json['release']       = ReservesReleaseEnum::checkValue($this->release);
        }
        if (isset($this->releaseFactor)) {
            $json['releaseFactor'] = $this->releaseFactor;
        }
        if (isset($this->start)) {
            $json['start']         = $this->start;
        }
        if (isset($this->finish)) {
            $json['finish']        = $this->finish;
        }
        if (isset($this->max)) {
            $json['max']           = $this->max;
        }
        if (isset($this->inactive)) {
            $json['inactive']      = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']        = FrozenEnum::checkValue($this->frozen);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
