<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class SessionsPostRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $login;

    /**
     * @var int|null
     */
    private $public;

    /**
     * @var int|null
     */
    private $token;

    /**
     * @var int|null
     */
    private $mfaAuthenticated;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * Returns Login.
     * The Login that owns this resource.
     */
    public function getLogin(): ?string
    {
        return $this->login;
    }

    /**
     * Sets Login.
     * The Login that owns this resource.
     *
     * @maps login
     */
    public function setLogin(?string $login): void
    {
        $this->login = $login;
    }

    /**
     * Returns Public.
     * Whether this Session should have access to only public resources.
     * All other resources are private. <details> <summary>Valid Values</summary>
     * - `0` - **Session can also access private resources.**
     * - `1` - **Session can only access public resources.**
     * </details>
     */
    public function getPublic(): ?int
    {
        return $this->public;
    }

    /**
     * Sets Public.
     * Whether this Session should have access to only public resources.
     * All other resources are private. <details> <summary>Valid Values</summary>
     * - `0` - **Session can also access private resources.**
     * - `1` - **Session can only access public resources.**
     * </details>
     *
     * @maps public
     * @factory \PayrixLib\Models\SessionPublicEnum::checkValue
     */
    public function setPublic(?int $public): void
    {
        $this->public = $public;
    }

    /**
     * Returns Token.
     * Whether or not an AuthToken is required as part of the authentication when this Apikey is used.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **The authToken mechanism is disabled.**
     * - `1` - **The authToken mechanism is required for 'POST' and 'DELETE' requests.**
     *
     * </details>
     */
    public function getToken(): ?int
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * Whether or not an AuthToken is required as part of the authentication when this Apikey is used.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **The authToken mechanism is disabled.**
     * - `1` - **The authToken mechanism is required for 'POST' and 'DELETE' requests.**
     *
     * </details>
     *
     * @maps token
     * @factory \PayrixLib\Models\SessionTokenEnum::checkValue
     */
    public function setToken(?int $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Mfa Authenticated.
     * Whether or not the MFA is enabled.. <details> <summary>Valid Values</summary>
     * - `0` - **MFA is disabled.**
     * - `1` - **MFA is enabled.**
     * </details>
     */
    public function getMfaAuthenticated(): ?int
    {
        return $this->mfaAuthenticated;
    }

    /**
     * Sets Mfa Authenticated.
     * Whether or not the MFA is enabled.. <details> <summary>Valid Values</summary>
     * - `0` - **MFA is disabled.**
     * - `1` - **MFA is enabled.**
     * </details>
     *
     * @maps mfaAuthenticated
     * @factory \PayrixLib\Models\SessionMfaAuthenticatedEnum::checkValue
     */
    public function setMfaAuthenticated(?int $mfaAuthenticated): void
    {
        $this->mfaAuthenticated = $mfaAuthenticated;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Converts the SessionsPostRequest object to a human-readable string representation.
     *
     * @return string The string representation of the SessionsPostRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SessionsPostRequest',
            [
                'login' => $this->login,
                'public' => $this->public,
                'token' => $this->token,
                'mfaAuthenticated' => $this->mfaAuthenticated,
                'inactive' => $this->inactive,
                'frozen' => $this->frozen
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->login)) {
            $json['login']            = $this->login;
        }
        if (isset($this->public)) {
            $json['public']           = SessionPublicEnum::checkValue($this->public);
        }
        if (isset($this->token)) {
            $json['token']            = SessionTokenEnum::checkValue($this->token);
        }
        if (isset($this->mfaAuthenticated)) {
            $json['mfaAuthenticated'] = SessionMfaAuthenticatedEnum::checkValue($this->mfaAuthenticated);
        }
        if (isset($this->inactive)) {
            $json['inactive']         = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']           = FrozenEnum::checkValue($this->frozen);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
