<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class StatementsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|BillingsResponse|null
     */
    private $billing;

    /**
     * @var string|EntitiesResponse|null
     */
    private $entity;

    /**
     * @var int|null
     */
    private $start;

    /**
     * @var int|null
     */
    private $finish;

    /**
     * @var string|null
     */
    private $status = StatementStatusEnum::PENDING;

    /**
     * @var int|null
     */
    private $totalPaid;

    /**
     * @var int|null
     */
    private $total;

    /**
     * @var array
     */
    private $currency = ['value' => CurrencyEnum::USD];

    /**
     * @var string|EntitiesResponse|null
     */
    private $forentity;

    /**
     * @var DisbursementsResponse[]|null
     */
    private $disbursements;

    /**
     * @var EntriesResponse[]|null
     */
    private $entries;

    /**
     * @var PendingEntriesResponse[]|null
     */
    private $pendingEntries;

    /**
     * @var StatementEntriesResponse[]|null
     */
    private $statementEntries;

    /**
     * @var TxnsResponse[]|null
     */
    private $txns;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Billing.
     * The identifier of the Billing of this statement resource.
     *
     * @return string|BillingsResponse|null
     */
    public function getBilling()
    {
        return $this->billing;
    }

    /**
     * Sets Billing.
     * The identifier of the Billing of this statement resource.
     *
     * @maps billing
     * @mapsBy anyOf(anyOf(string,BillingsResponse),null)
     *
     * @param string|BillingsResponse|null $billing
     */
    public function setBilling($billing): void
    {
        $this->billing = $billing;
    }

    /**
     * Returns Entity.
     * The paying entity for which this statement applies.
     *
     * @return string|EntitiesResponse|null
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Sets Entity.
     * The paying entity for which this statement applies.
     *
     * @maps entity
     * @mapsBy anyOf(anyOf(string,EntitiesResponse),null)
     *
     * @param string|EntitiesResponse|null $entity
     */
    public function setEntity($entity): void
    {
        $this->entity = $entity;
    }

    /**
     * Returns Start.
     * The date on which this Statement period should start. The date is specified as an eight digit string
     * in YYYYMMDD format, for example, '20160120' for January 20, 2016.
     */
    public function getStart(): ?int
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * The date on which this Statement period should start. The date is specified as an eight digit string
     * in YYYYMMDD format, for example, '20160120' for January 20, 2016.
     *
     * @maps start
     */
    public function setStart(?int $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns Finish.
     * The date on which this Statement period should finish. The date is specified as an eight digit
     * string in YYYYMMDD format, for example, '20160120' for January 20, 2016.
     */
    public function getFinish(): ?int
    {
        return $this->finish;
    }

    /**
     * Sets Finish.
     * The date on which this Statement period should finish. The date is specified as an eight digit
     * string in YYYYMMDD format, for example, '20160120' for January 20, 2016.
     *
     * @maps finish
     */
    public function setFinish(?int $finish): void
    {
        $this->finish = $finish;
    }

    /**
     * Returns Status.
     * The current status of the statement.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `pending` - **Statement amount is owed and is pending payment.**
     * - `processing` - **A payment is processing for this statement, pending completion.**
     * - `partiallyPaid` - **The statement was partially paid, some amount is still outstanding.**
     * - `paid` - **The statement was paid in full.**
     * - `partiallyCancelled` - **The statement was partially cancelled, some amount is still outstanding.
     * **
     * - `cancelled` - **The statement was completely cancelled and is no longer due for payment.**
     *
     * </details>
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The current status of the statement.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `pending` - **Statement amount is owed and is pending payment.**
     * - `processing` - **A payment is processing for this statement, pending completion.**
     * - `partiallyPaid` - **The statement was partially paid, some amount is still outstanding.**
     * - `paid` - **The statement was paid in full.**
     * - `partiallyCancelled` - **The statement was partially cancelled, some amount is still outstanding.
     * **
     * - `cancelled` - **The statement was completely cancelled and is no longer due for payment.**
     *
     * </details>
     *
     * @maps status
     * @factory \PayrixLib\Models\StatementStatusEnum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Total Paid.
     * The total paid amount for this statement, specified as an integer in cents.
     */
    public function getTotalPaid(): ?int
    {
        return $this->totalPaid;
    }

    /**
     * Sets Total Paid.
     * The total paid amount for this statement, specified as an integer in cents.
     *
     * @maps totalPaid
     */
    public function setTotalPaid(?int $totalPaid): void
    {
        $this->totalPaid = $totalPaid;
    }

    /**
     * Returns Total.
     * The total amount for this statement. This field is specified as an integer in cents.
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * The total amount for this statement. This field is specified as an integer in cents.
     *
     * @maps total
     */
    public function setTotal(?int $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Currency.
     * The currency for this statement. See <a href="https://www.iban.com/currency-codes"
     * target="_blank">Currency codes</a>  for all valid values.
     */
    public function getCurrency(): ?string
    {
        if (count($this->currency) == 0) {
            return null;
        }
        return $this->currency['value'];
    }

    /**
     * Sets Currency.
     * The currency for this statement. See <a href="https://www.iban.com/currency-codes"
     * target="_blank">Currency codes</a>  for all valid values.
     *
     * @maps currency
     * @factory \PayrixLib\Models\CurrencyEnum::checkValue
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency['value'] = $currency;
    }

    /**
     * Unsets Currency.
     * The currency for this statement. See <a href="https://www.iban.com/currency-codes"
     * target="_blank">Currency codes</a>  for all valid values.
     */
    public function unsetCurrency(): void
    {
        $this->currency = [];
    }

    /**
     * Returns Forentity.
     * The payee entity of the statement.
     *
     * @return string|EntitiesResponse|null
     */
    public function getForentity()
    {
        return $this->forentity;
    }

    /**
     * Sets Forentity.
     * The payee entity of the statement.
     *
     * @maps forentity
     * @mapsBy anyOf(anyOf(string,EntitiesResponse),null)
     *
     * @param string|EntitiesResponse|null $forentity
     */
    public function setForentity($forentity): void
    {
        $this->forentity = $forentity;
    }

    /**
     * Returns Disbursements.
     *
     * @return DisbursementsResponse[]|null
     */
    public function getDisbursements(): ?array
    {
        return $this->disbursements;
    }

    /**
     * Sets Disbursements.
     *
     * @maps disbursements
     *
     * @param DisbursementsResponse[]|null $disbursements
     */
    public function setDisbursements(?array $disbursements): void
    {
        $this->disbursements = $disbursements;
    }

    /**
     * Returns Entries.
     *
     * @return EntriesResponse[]|null
     */
    public function getEntries(): ?array
    {
        return $this->entries;
    }

    /**
     * Sets Entries.
     *
     * @maps entries
     *
     * @param EntriesResponse[]|null $entries
     */
    public function setEntries(?array $entries): void
    {
        $this->entries = $entries;
    }

    /**
     * Returns Pending Entries.
     *
     * @return PendingEntriesResponse[]|null
     */
    public function getPendingEntries(): ?array
    {
        return $this->pendingEntries;
    }

    /**
     * Sets Pending Entries.
     *
     * @maps pendingEntries
     *
     * @param PendingEntriesResponse[]|null $pendingEntries
     */
    public function setPendingEntries(?array $pendingEntries): void
    {
        $this->pendingEntries = $pendingEntries;
    }

    /**
     * Returns Statement Entries.
     *
     * @return StatementEntriesResponse[]|null
     */
    public function getStatementEntries(): ?array
    {
        return $this->statementEntries;
    }

    /**
     * Sets Statement Entries.
     *
     * @maps statementEntries
     *
     * @param StatementEntriesResponse[]|null $statementEntries
     */
    public function setStatementEntries(?array $statementEntries): void
    {
        $this->statementEntries = $statementEntries;
    }

    /**
     * Returns Txns.
     *
     * @return TxnsResponse[]|null
     */
    public function getTxns(): ?array
    {
        return $this->txns;
    }

    /**
     * Sets Txns.
     *
     * @maps txns
     *
     * @param TxnsResponse[]|null $txns
     */
    public function setTxns(?array $txns): void
    {
        $this->txns = $txns;
    }

    /**
     * Converts the StatementsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the StatementsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'StatementsResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'billing' => $this->billing,
                'entity' => $this->entity,
                'start' => $this->start,
                'finish' => $this->finish,
                'status' => $this->status,
                'totalPaid' => $this->totalPaid,
                'total' => $this->total,
                'currency' => $this->getCurrency(),
                'forentity' => $this->forentity,
                'disbursements' => $this->disbursements,
                'entries' => $this->entries,
                'pendingEntries' => $this->pendingEntries,
                'statementEntries' => $this->statementEntries,
                'txns' => $this->txns
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->created)) {
            $json['created']          = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']         = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']          =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']         = $this->modifier;
        }
        if (isset($this->billing)) {
            $json['billing']          =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->billing,
                    'anyOf(anyOf(string,BillingsResponse),null)'
                );
        }
        if (isset($this->entity)) {
            $json['entity']           =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->entity,
                    'anyOf(anyOf(string,EntitiesResponse),null)'
                );
        }
        if (isset($this->start)) {
            $json['start']            = $this->start;
        }
        if (isset($this->finish)) {
            $json['finish']           = $this->finish;
        }
        if (isset($this->status)) {
            $json['status']           = StatementStatusEnum::checkValue($this->status);
        }
        if (isset($this->totalPaid)) {
            $json['totalPaid']        = $this->totalPaid;
        }
        if (isset($this->total)) {
            $json['total']            = $this->total;
        }
        if (!empty($this->currency)) {
            $json['currency']         = CurrencyEnum::checkValue($this->currency['value']);
        }
        if (isset($this->forentity)) {
            $json['forentity']        =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->forentity,
                    'anyOf(anyOf(string,EntitiesResponse),null)'
                );
        }
        if (isset($this->disbursements)) {
            $json['disbursements']    = $this->disbursements;
        }
        if (isset($this->entries)) {
            $json['entries']          = $this->entries;
        }
        if (isset($this->pendingEntries)) {
            $json['pendingEntries']   = $this->pendingEntries;
        }
        if (isset($this->statementEntries)) {
            $json['statementEntries'] = $this->statementEntries;
        }
        if (isset($this->txns)) {
            $json['txns']             = $this->txns;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
