<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use PayrixLib\ApiHelper;
use stdClass;

class SubscriptionTokensResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $modified;

    /**
     * @var string|LoginsResponse|null
     */
    private $creator;

    /**
     * @var string|null
     */
    private $modifier;

    /**
     * @var string|SubscriptionsResponse|null
     */
    private $subscription;

    /**
     * @var string|TokensResponse|null
     */
    private $token;

    /**
     * @var int|null
     */
    private $inactive = InactiveEnum::ACTIVE;

    /**
     * @var int|null
     */
    private $frozen = FrozenEnum::NOTFROZEN;

    /**
     * Returns Id.
     * The ID of this resource.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of this resource.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time at which this resource was created. The format should be YYYY-MM-DD HH:MM:SS.SSSS
     *
     * @maps created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     */
    public function getModified(): ?string
    {
        return $this->modified;
    }

    /**
     * Sets Modified.
     * The date and time at which this resource was modified. The format should be YYYY-MM-DD HH:MM:SS.
     * SSSS
     *
     * @maps modified
     */
    public function setModified(?string $modified): void
    {
        $this->modified = $modified;
    }

    /**
     * Returns Creator.
     * The identifier of the Login that created this resource.
     *
     * @return string|LoginsResponse|null
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * The identifier of the Login that created this resource.
     *
     * @maps creator
     * @mapsBy anyOf(anyOf(string,LoginsResponse),null)
     *
     * @param string|LoginsResponse|null $creator
     */
    public function setCreator($creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Modifier.
     * The identifier of the Login that last modified this resource.
     */
    public function getModifier(): ?string
    {
        return $this->modifier;
    }

    /**
     * Sets Modifier.
     * The identifier of the Login that last modified this resource.
     *
     * @maps modifier
     */
    public function setModifier(?string $modifier): void
    {
        $this->modifier = $modifier;
    }

    /**
     * Returns Subscription.
     * The identifier of the Subscription resource that this Subscription Token is associated with. This is
     * the Subscription that the Token identified in the 'token' field of this resource is responsible for
     * paying for.
     *
     * @return string|SubscriptionsResponse|null
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    /**
     * Sets Subscription.
     * The identifier of the Subscription resource that this Subscription Token is associated with. This is
     * the Subscription that the Token identified in the 'token' field of this resource is responsible for
     * paying for.
     *
     * @maps subscription
     * @mapsBy anyOf(anyOf(string,SubscriptionsResponse),null)
     *
     * @param string|SubscriptionsResponse|null $subscription
     */
    public function setSubscription($subscription): void
    {
        $this->subscription = $subscription;
    }

    /**
     * Returns Token.
     * The identifier of the Token resource that this Subscription Token is associated with. This resource
     * identifies the means of payment for the Subscription identified in the 'subscription' field of this
     * resource.
     *
     * @return string|TokensResponse|null
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * The identifier of the Token resource that this Subscription Token is associated with. This resource
     * identifies the means of payment for the Subscription identified in the 'subscription' field of this
     * resource.
     *
     * @maps token
     * @mapsBy anyOf(anyOf(string,TokensResponse),null)
     *
     * @param string|TokensResponse|null $token
     */
    public function setToken($token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     */
    public function getInactive(): ?int
    {
        return $this->inactive;
    }

    /**
     * Sets Inactive.
     * Whether this resource is marked as inactive.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Active**
     * - `1` - **Inactive**
     *
     * </details>
     *
     * @maps inactive
     * @factory \PayrixLib\Models\InactiveEnum::checkValue
     */
    public function setInactive(?int $inactive): void
    {
        $this->inactive = $inactive;
    }

    /**
     * Returns Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     */
    public function getFrozen(): ?int
    {
        return $this->frozen;
    }

    /**
     * Sets Frozen.
     * Whether this resource is marked as frozen.
     *
     * <details>
     * <summary>Valid Values</summary>
     *
     * - `0` - **Not Frozen**
     * - `1` - **Frozen**
     *
     * </details>
     *
     * @maps frozen
     * @factory \PayrixLib\Models\FrozenEnum::checkValue
     */
    public function setFrozen(?int $frozen): void
    {
        $this->frozen = $frozen;
    }

    /**
     * Converts the SubscriptionTokensResponse object to a human-readable string representation.
     *
     * @return string The string representation of the SubscriptionTokensResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SubscriptionTokensResponse',
            [
                'id' => $this->id,
                'created' => $this->created,
                'modified' => $this->modified,
                'creator' => $this->creator,
                'modifier' => $this->modifier,
                'subscription' => $this->subscription,
                'token' => $this->token,
                'inactive' => $this->inactive,
                'frozen' => $this->frozen
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']           = $this->id;
        }
        if (isset($this->created)) {
            $json['created']      = $this->created;
        }
        if (isset($this->modified)) {
            $json['modified']     = $this->modified;
        }
        if (isset($this->creator)) {
            $json['creator']      =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->creator,
                    'anyOf(anyOf(string,LoginsResponse),null)'
                );
        }
        if (isset($this->modifier)) {
            $json['modifier']     = $this->modifier;
        }
        if (isset($this->subscription)) {
            $json['subscription'] =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->subscription,
                    'anyOf(anyOf(string,SubscriptionsResponse),null)'
                );
        }
        if (isset($this->token)) {
            $json['token']        =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->token,
                    'anyOf(anyOf(string,TokensResponse),null)'
                );
        }
        if (isset($this->inactive)) {
            $json['inactive']     = InactiveEnum::checkValue($this->inactive);
        }
        if (isset($this->frozen)) {
            $json['frozen']       = FrozenEnum::checkValue($this->frozen);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
