<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class SubscriptionOriginEnum
{
    /**
     * Customer will be subscribing through eCommerce.
     */
    public const ECOMMERCE = 2;

    /**
     * Customer will be subscribing by Mail Order/Telephone.
     */
    public const MAILORDERTELEPHONE = 3;

    /**
     * Originated with Apple Pay.
     */
    public const APPLEPAY = 4;

    /**
     * Originated as a Successful 3D Secure transaction.
     */
    public const SUCCESSFUL3DSECURE = 5;

    /**
     * Originated as an Attempted 3D Secure transaction.
     */
    public const ATTEMPTED3DSECURE = 6;

    /**
     * Originated in a Payframe.
     */
    public const PAYFRAME = 8;

    private const _ALL_VALUES = [
        self::ECOMMERCE,
        self::MAILORDERTELEPHONE,
        self::APPLEPAY,
        self::SUCCESSFUL3DSECURE,
        self::ATTEMPTED3DSECURE,
        self::PAYFRAME
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|int $value Value or a list/map of values to be checked
     *
     * @return array|null|int Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for SubscriptionOriginEnum.");
    }
}
