<?php

declare(strict_types=1);

/*
 * Payrix
 *
 * This file was automatically generated by Worldpay.
 */

namespace PayrixLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class VerificationRefActionEnum
{
    /**
     * No action.
     */
    public const NONE = '0';

    /**
     * Block txn, will never be processed. The Entity is sent to the manual review queue.
     */
    public const BLOCK = '1';

    /**
     * Hold txn, will not be captured.
     */
    public const HOLD = '3';

    /**
     * Reserve txn, funds should be reserved.
     */
    public const RESERVE = '4';

    /**
     * Block current activity, no change for merchant.
     */
    public const LIMIT = '5';

    /**
     * Passed decision(s). Will not be set anywhere, will only be used for integration purposes.
     */
    public const PASS = '6';

    /**
     * PostReviewOnly.
     */
    public const POSTREVIEWONLY = '8';

    /**
     * manualReview.
     */
    public const MANUALREVIEW = 'manualReview';

    /**
     * approved.
     */
    public const APPROVED = 'approved';

    /**
     * declined.
     */
    public const DECLINED = 'declined';

    private const _ALL_VALUES = [
        self::NONE,
        self::BLOCK,
        self::HOLD,
        self::RESERVE,
        self::LIMIT,
        self::PASS,
        self::POSTREVIEWONLY,
        self::MANUALREVIEW,
        self::APPROVED,
        self::DECLINED
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for VerificationRefActionEnum.");
    }
}
